<?php
$languageNames = array(
'el' => 'Griyego',
'en-gb' => 'Ingles (UK)',
'es' => 'Espanyol',
'hi' => 'Hindi',
'it' => 'Italyano',
'ja' => 'Japanese',
'nl' => 'Olandes',
'ru' => 'Russian',
'sl' => 'Slovenian',
'sr' => 'Serbian',
'sv' => 'Swedish',
'swb' => 'Comorian',
'tr' => 'Turkish',
'uk' => 'Ukranian',
'yue' => 'Cantonese',
'zh' => 'Chinese',
'zh-hans' => 'Chinese (pinasimple)',
'zh-hant' => 'Chinese (tradisyunal)',
);
