<?php
abstract class WikiaParserTagController extends WikiaController {

	/**
	 * Simple counter used in generating markers' ids
	 * @var int
	 */
	private $count = 1;

	/**
	 * An array with markers ids and real output for our tags
	 * @var array
	 */
	protected $markers = [];

	/**
	 * @desc Hook function registered in $wgHooks['ParserFirstCallInit'][] which should always return true
	 *
	 * @param Parser $parser
	 * @return Boolean true
	 */
	abstract public static function onParserFirstCallInit( Parser $parser );

	/**
	 * @desc Hook function registered in $wgHooks['ParserAfterTidy'][] which should always return true
	 *
	 * @param Parser $parser
	 * @param String $text
	 * @return Boolean true
	 */
	abstract public function onParserAfterTidy( Parser &$parser, &$text );

	/**
	 * @desc Checks if parameter from parameters array is valid
	 *
	 * @param String|Mixed $paramValue value of the parameter
	 * @param WikiaValidator $validator
	 * @param String $errorMessage reference to a string variable which will get error message if one occurs
	 *
	 * @return bool
	 */
	public function isTagParamValid( $paramValue, WikiaValidator $validator, &$errorMessage ) {
		$isValid = $validator->isValid( $paramValue );

		if( !$isValid ) {
			$errorMessage = $validator->getError()->getMsg();
		}

		return $isValid;
	}

	/**
	 * @desc Factory method to create validators for params
	 * if should return WikiaValidatorAlwaysTrue if validator can't be created or won't be used
	 *
	 * @param String $paramName
	 * @return WikiaValidator
	 */
	abstract protected function buildParamValidator( $paramName );

	/**
	 * @desc Generates unique strings which will be placed instead of tags
	 *
	 * @param Parser $parser
	 * @return string
	 */
	protected function generateMarkerId( Parser $parser ) {
		$wikiaParserMarkerSufix = '-WIKIA-PARSER-MARKER-' . $this->count;
		$this->count++;
		return $parser->uniqPrefix() . $wikiaParserMarkerSufix . "-\x7f";
	}

	/**
	 * @desc Adds output which will replaced unique strings which replaced tags in the article
	 *
	 * @param String $markerId id generated by generateMarkerId()
	 * @param $output
	 */
	protected function addMarkerOutput( $markerId, $output ) {
		if( !empty( $this->wg->ArticleAsJson ) && $output instanceof WikiaResponse ) {
			$this->markers[$markerId] = trim( json_encode( $output->toString() ), "\"" );
		} else {
			$this->markers[$markerId] = $output->toString();
		}
	}

	public function getMarkers() {
		return $this->markers;
	}
}
