<?php
/**
 * Internationalisation for Uniwiki/Layouts extension
 *
 * @file
 * @ingroup Extensions
 */

$messages = array();

/** English */
$messages['en'] = array(
	'layouts-desc' => 'Populate newly-created pages with editable "layouts" to encourage a common structure for pages',
	'layouts_title' => 'Create a page',
	'layouts_chooselayout' => 'Choose a layout for $1:',
	'layouts_nolayout' => 'No layout',
	'layouts_continue' => 'Continue',
	'layouts_choosecategory' => 'Choose a category for $1:',
	'layouts_unknown' => 'Unknown',
	'layouts_tagline' => 'This page was generated by the \'\'\'$1\'\'\' layout.',
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags'
);

/** Message documentation (Message documentation)
 * @author Bennylin
 * @author Fryed-peach
 * @author Purodha
 * @author Siebrand
 * @author Umherirrender
 */
$messages['qqq'] = array(
	'layouts-desc' => '{{desc}}',
	'layouts_title' => '{{Identical|Createpage}}',
	'layouts_continue' => '{{Identical|Continue}}',
	'layouts_unknown' => '{{Identical|Unknown}}',
	'layouts-layoutcategorypage' => '{{optional}}',
);

/** Afrikaans (Afrikaans)
 * @author Naudefj
 */
$messages['af'] = array(
	'layouts_title' => "Skep 'n bladsy",
	'layouts_continue' => 'Volgende',
	'layouts_unknown' => 'Onbekend',
);

/** Gheg Albanian (Gegë)
 * @author Mdupont
 */
$messages['aln'] = array(
	'layouts-desc' => 'Rrituni me të sapo-krijuar faqet me "Layouts editable" për të inkurajuar një strukturë të përbashkët për faqe',
	'layouts_title' => 'Krijo një faqe',
	'layouts_chooselayout' => 'Zgjidhni një plan urbanistik për $1:',
	'layouts_nolayout' => 'Nuk ka plan urbanistik',
	'layouts_continue' => 'Vazhdoj',
	'layouts_choosecategory' => 'Zgjidhni një kategori për $1:',
	'layouts_unknown' => 'I panjohur',
	'layouts_tagline' => "Kjo faqe është e gjeneruar nga '''$1''' layout.",
);

/** Arabic (العربية)
 * @author Meno25
 * @author Ouda
 */
$messages['ar'] = array(
	'layouts-desc' => 'يضيف للصفحات المنشأة حديثا "هيئات" يمكن تعديلها لتشجيع هيكل متشابه للصفحات',
	'layouts_title' => 'إنشاء صفحة',
	'layouts_chooselayout' => 'أختار تنسيق ل$1',
	'layouts_nolayout' => 'لا يوجد تصميم',
	'layouts_continue' => 'أستمرار',
	'layouts_choosecategory' => 'أختار تصنيف ل$1',
	'layouts_unknown' => 'غير معروف',
	'layouts_tagline' => "هذه الصفحة تم توليدها بواسطة هيئة '''$1'''.",
);

/** Aramaic (ܐܪܡܝܐ)
 * @author Basharh
 */
$messages['arc'] = array(
	'layouts_title' => 'ܒܪܝ ܦܐܬܐ',
	'layouts_unknown' => 'ܠܐ ܝܕܝܥܐ',
);

/** Egyptian Spoken Arabic (مصرى)
 * @author Meno25
 * @author Ouda
 * @author Ramsis II
 */
$messages['arz'] = array(
	'layouts-desc' => 'يضيف للصفحات المنشأة حديثا "هيئات" يمكن تعديلها لتشجيع هيكل متشابه للصفحات',
	'layouts_title' => 'ابتدى صفحه',
	'layouts_chooselayout' => 'أختار تنسيق ل$1',
	'layouts_nolayout' => 'لا يوجد تصميم',
	'layouts_continue' => 'استمر',
	'layouts_choosecategory' => 'اختار تصنيف لـ $1:',
	'layouts_unknown' => 'مش معروف',
	'layouts_tagline' => "هذه الصفحة تم توليدها بواسطة هيئة '''$1'''.",
);

/** Belarusian (Taraškievica orthography) (‪Беларуская (тарашкевіца)‬)
 * @author EugeneZelenko
 * @author Jim-by
 * @author Red Winged Duck
 */
$messages['be-tarask'] = array(
	'layouts-desc' => 'Запаўняе новыя старонкі «макетамі» для заахвочваньня ўжываньня агульнай структуры старонак',
	'layouts_title' => 'Стварыць старонку',
	'layouts_chooselayout' => 'Выбар макету для $1:',
	'layouts_nolayout' => 'Няма макету',
	'layouts_continue' => 'Працягваць',
	'layouts_choosecategory' => 'Выбар катэгорыі для $1:',
	'layouts_unknown' => 'Невядомы',
	'layouts_tagline' => "Гэта старонка была створаная з дапамогай макету '''$1'''.",
);

/** Bulgarian (Български)
 * @author DCLXVI
 */
$messages['bg'] = array(
	'layouts-desc' => 'Запълване на новосъздадените страници с редактируеми формати за насърчаване на обща структура за страниците',
	'layouts_title' => 'Създаване на страница',
	'layouts_chooselayout' => 'Избиране на формат за $1:',
	'layouts_nolayout' => 'Без формат',
	'layouts_continue' => 'Продължаване',
	'layouts_choosecategory' => 'Избиране на категория за $1:',
	'layouts_tagline' => "Тази страница е създадена с формат '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Bengali (বাংলা)
 * @author Bellayet
 */
$messages['bn'] = array(
	'layouts_title' => 'পাতা তৈরি কর',
	'layouts_unknown' => 'অজানা',
);

/** Breton (Brezhoneg)
 * @author Fulup
 */
$messages['br'] = array(
	'layouts-desc' => 'Poblañ ar pajennoù nevez-krouet gant ur "pajennaozañ" kemmus a-benn broudañ kaout ur framm boutin d\'an holl bajennoù',
	'layouts_title' => 'Krouiñ ur bajenn',
	'layouts_chooselayout' => 'Dibab ar pajennaozañ evit $1 :',
	'layouts_nolayout' => 'Tamm pajennaozañ ebet',
	'layouts_continue' => "Kenderc'hel",
	'layouts_choosecategory' => 'Krouiñ ur rummad evit $1 :',
	'layouts_unknown' => 'Dianav',
	'layouts_tagline' => "Savet eo bet ar bajenn-mañ gant ar pajennaozañ '''$1'''",
);

/** Bosnian (Bosanski)
 * @author CERminator
 */
$messages['bs'] = array(
	'layouts-desc' => 'Puni novonapravljene stranice za "izgledima" koji se mogu uređivati da bi ohrabrili pravljenje stranica standardizovane strukture',
	'layouts_title' => 'Napravi stranicu',
	'layouts_chooselayout' => 'Izaberi izgled za $1:',
	'layouts_nolayout' => 'Bez izgleda',
	'layouts_continue' => 'Nastavi',
	'layouts_choosecategory' => 'Izaberi kategoriju za $1:',
	'layouts_unknown' => 'Nepoznato',
	'layouts_tagline' => "Ova stranica je generisana putem '''$1''' izgleda.",
);

/** Catalan (Català)
 * @author SMP
 * @author Solde
 * @author Ssola
 */
$messages['ca'] = array(
	'layouts-desc' => "Omplir les pàgines recentment creades amb estructures (''layouts'') modificables per a fomentar una estructura comú a les pàgines",
	'layouts_title' => 'Crea una pàgina',
	'layouts_chooselayout' => 'Escolliu un format per a $1:',
	'layouts_nolayout' => 'Sense format',
	'layouts_continue' => 'Continua',
	'layouts_choosecategory' => 'Escolliu una categoria per a $1:',
	'layouts_unknown' => 'Desconegut',
	'layouts_tagline' => "Aquesta pàgina va ser generada pel format '''$1'''.",
);

/** Sorani (کوردی)
 * @author Marmzok
 */
$messages['ckb'] = array(
	'layouts_title' => 'دروست‌کردنی لاپەڕەیەک',
	'layouts_continue' => 'درێژەدان',
	'layouts_choosecategory' => 'هاوپۆلێک هەڵبژێرە بۆ $1:',
	'layouts_unknown' => 'نەناسراو',
);

/** Czech (Česky)
 * @author Matěj Grabovský
 */
$messages['cs'] = array(
	'layouts-desc' => 'Naplní nově vytvořené stránky rozloženinami, které je možné upravovat, aby se posilnila společná struktura stránek',
	'layouts_title' => 'Vytvořit stránku',
	'layouts_chooselayout' => 'Vyberte rozložení pro $1:',
	'layouts_nolayout' => 'Žádné rozložení',
	'layouts_continue' => 'Pokračovat',
	'layouts_choosecategory' => 'Vyberte kategorii pro $1:',
	'layouts_unknown' => 'Neznámé',
	'layouts_tagline' => "Tato stránku byla vytvořena s rozložením '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** German (Deutsch)
 * @author ChrisiPK
 * @author Melancholie
 */
$messages['de'] = array(
	'layouts-desc' => 'Bestückt frisch erzeugte Seiten mit bearbeitbaren „Gestaltungen“, um eine einheitliche Struktur von Seiten zu fördern',
	'layouts_title' => 'Neue Seite erstellen',
	'layouts_chooselayout' => 'Suche ein Format für $1 aus:',
	'layouts_nolayout' => 'Kein Format',
	'layouts_continue' => 'Weiter',
	'layouts_choosecategory' => 'Suche eine Kategorie für $1 aus:',
	'layouts_unknown' => 'Unbekannt',
	'layouts_tagline' => "Diese Seite wurde mit dem '''$1'''-Layout erstellt.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** German (formal address) (‪Deutsch (Sie-Form)‬)
 * @author Imre
 */
$messages['de-formal'] = array(
	'layouts_chooselayout' => 'Suchen Sie ein Format für $1 aus:',
	'layouts_choosecategory' => 'Suchen Sie eine Kategorie für $1 aus:',
);

/** Lower Sorbian (Dolnoserbski)
 * @author Michawiki
 */
$messages['dsb'] = array(
	'layouts-desc' => 'Pśipóra rowno napórane boki z wobźěłujobnymi "wugótowanjami", aby spěchował jadnotnu strukturu za boki',
	'layouts_title' => 'Bok napóraś',
	'layouts_chooselayout' => 'Wugótowanje za $1 wubraś:',
	'layouts_nolayout' => 'Žedno wugótowanje',
	'layouts_continue' => 'Dalej',
	'layouts_choosecategory' => 'Kategoriju za $1 wubraś:',
	'layouts_unknown' => 'Njeznaty',
	'layouts_tagline' => "Toś ten bok jo se napórał z wugótowanim '''$1'''.",
);

/** Greek (Ελληνικά)
 * @author Consta
 * @author Omnipaedista
 * @author ZaDiak
 */
$messages['el'] = array(
	'layouts_title' => 'Δημιουργία μιας σελίδας',
	'layouts_chooselayout' => 'Επιλογή ενός σχεδιαγράμματος για τον $1:',
	'layouts_nolayout' => 'Κανένα σχεδιάγραμμα',
	'layouts_continue' => 'Συνέχεια',
	'layouts_choosecategory' => 'Επιλογή μιας κατηγορίας για τον $1:',
	'layouts_unknown' => 'Άγνωστο',
	'layouts_tagline' => "Αυτή η σελίδα δημιουργήθηκε από το σχεδιάγραμμα '''$1'''.",
);

/** Esperanto (Esperanto)
 * @author Melancholie
 * @author Yekrats
 */
$messages['eo'] = array(
	'layouts_title' => 'Krei paĝon',
	'layouts_chooselayout' => 'Elektu aspekton por $1:',
	'layouts_nolayout' => 'Nenia aranĝo',
	'layouts_continue' => 'Daŭrigi',
	'layouts_choosecategory' => 'Selekti kategorion por $1:',
	'layouts_unknown' => 'Nekonata',
	'layouts_tagline' => "Ĉi tiu paĝo estis generita de la aranĝo '''$1'''.",
);

/** Spanish (Español)
 * @author Sanbec
 */
$messages['es'] = array(
	'layouts-desc' => 'Rellenar las páginas recién creadas con «estructuras» editables para fomentar una estructura común en las páginas',
	'layouts_title' => 'Crear una página',
	'layouts_chooselayout' => 'Selecciona un Diseño para $1:',
	'layouts_nolayout' => 'Sin diseño',
	'layouts_continue' => 'Continuar',
	'layouts_choosecategory' => 'Elige una Categoría para $1:',
	'layouts_unknown' => 'Desconocido',
	'layouts_tagline' => 'Esta página se generó con el diseño <strong>$1</strong>.',
);

/** Estonian (Eesti)
 * @author Avjoska
 */
$messages['et'] = array(
	'layouts_title' => 'Loo lehekülg',
	'layouts_continue' => 'Jätka',
	'layouts_choosecategory' => 'Vali $1 jaoks kategooria:',
	'layouts_unknown' => 'Tundmatu',
);

/** Basque (Euskara)
 * @author Theklan
 */
$messages['eu'] = array(
	'layouts-desc' => 'Orrialde sortu berriak aldatu daitezkeen "egiturekin" populatzen ditu, orrialdeek egitura komunak izan ditzaten',
	'layouts_title' => 'Orrialde bat sortu',
	'layouts_chooselayout' => '$1(r)entzat itxura bat aukeratu:',
	'layouts_nolayout' => 'Ez dago itxurarik',
	'layouts_continue' => 'Jarraitu',
	'layouts_choosecategory' => '$1(r)entzat kategoria bat aukeratu:',
	'layouts_unknown' => 'Ezezaguna',
	'layouts_tagline' => "'''$1''' itxurak orrialde hau sortu du.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Finnish (Suomi)
 * @author Cimon Avaro
 * @author Crt
 * @author Silvonen
 * @author Str4nd
 */
$messages['fi'] = array(
	'layouts-desc' => 'Esitäyttää vastaluodut sivut muokattavilla "sabluunoilla" yhdenmukaisten sivujen pohjarakenteiden kannustamiseksi',
	'layouts_title' => 'Luo sivu',
	'layouts_chooselayout' => 'Valitse ulkoasu kohteelle $1:',
	'layouts_nolayout' => 'Ei ulkoasua',
	'layouts_continue' => 'Jatka',
	'layouts_choosecategory' => 'Valitse luokka kohteelle $1:',
	'layouts_unknown' => 'Tuntematon',
	'layouts_tagline' => "Tämän sivun tuotti '''$1''' ulkoasumuoto.",
);

/** French (Français)
 * @author Grondin
 * @author IAlex
 * @author Sherbrooke
 * @author Verdy p
 */
$messages['fr'] = array(
	'layouts-desc' => 'Remplit les pages nouvellement créées à l’aide de « mises en page » modifiables afin d’encourager une structure homogène à toutes les pages',
	'layouts_title' => 'Créer une page',
	'layouts_chooselayout' => 'Choisir une mise en page pour $1 :',
	'layouts_nolayout' => 'Aucune mise en page',
	'layouts_continue' => 'Continuer',
	'layouts_choosecategory' => 'Choisir une catégorie pour $1 :',
	'layouts_unknown' => 'Inconnu',
	'layouts_tagline' => "Cette page a été générée avec la mise en page '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Franco-Provençal (Arpetan)
 * @author Cedric31
 * @author ChrisPtDe
 */
$messages['frp'] = array(
	'layouts_title' => 'Fâre una pâge',
	'layouts_chooselayout' => 'Chouèsir una misa en pâge por $1 :',
	'layouts_nolayout' => 'Gins de misa en pâge',
	'layouts_continue' => 'Continuar',
	'layouts_choosecategory' => 'Chouèsir una catègorie por $1 :',
	'layouts_unknown' => 'Encognu',
	'layouts_tagline' => "Ceta pâge at étâ fêta avouéc la misa en pâge '''$1'''.",
);

/** Irish (Gaeilge)
 * @author Alison
 */
$messages['ga'] = array(
	'layouts_continue' => 'Lean',
);

/** Galician (Galego)
 * @author Toliño
 */
$messages['gl'] = array(
	'layouts-desc' => 'Poboar as páxinas novas creadas con distribucións editables para fomentar unha estrutura común para as páxinas',
	'layouts_title' => 'Crear unha páxina',
	'layouts_chooselayout' => 'Escolla unha distribución para "$1":',
	'layouts_nolayout' => 'Sen distribución',
	'layouts_continue' => 'Continuar',
	'layouts_choosecategory' => 'Escolla unha categoría para "$1":',
	'layouts_unknown' => 'Descoñecido',
	'layouts_tagline' => "Esta páxina foi xerada coa distribución '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Ancient Greek (Ἀρχαία ἑλληνικὴ)
 * @author Crazymadlover
 * @author Omnipaedista
 */
$messages['grc'] = array(
	'layouts_title' => 'Ποιεῖν δέλτον τινά',
	'layouts_continue' => 'Συνεχίζειν',
	'layouts_unknown' => 'Ἄγνωτος',
);

/** Swiss German (Alemannisch)
 * @author Als-Holder
 */
$messages['gsw'] = array(
	'layouts-desc' => 'Fiegt nej aagleite Syte bearbeitbari „Gstaltige“ zue go ne einheitligi Struktur vu Syte z ferdere',
	'layouts_title' => 'Neji Syte aalege',
	'layouts_chooselayout' => 'Suech e Format us fir $1:',
	'layouts_nolayout' => 'Kei Format',
	'layouts_continue' => 'Wyter',
	'layouts_choosecategory' => 'Suech e Kategorie uus fir $1:',
	'layouts_unknown' => 'Nit bekannt',
	'layouts_tagline' => "Die Syte isch mit em '''$1'''-Layout aagleit wore.",
);

/** Hebrew (עברית)
 * @author Rotemliss
 * @author YaronSh
 */
$messages['he'] = array(
	'layouts-desc' => 'הוספת "פריסות" הניתנות לעריכה לדפים חדשים כדי לעודד מבנה נפוץ לדפים',
	'layouts_title' => 'יצירת דף',
	'layouts_chooselayout' => 'בחרו בפריסה עבור $1:',
	'layouts_nolayout' => 'ללא פריסה',
	'layouts_continue' => 'המשך',
	'layouts_choosecategory' => 'בחרו קטגוריה עבור $1:',
	'layouts_unknown' => 'לא ידוע',
	'layouts_tagline' => "הדף נוצר על ידי הפריסה '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Croatian (Hrvatski)
 * @author SpeedyGonsales
 */
$messages['hr'] = array(
	'layouts_continue' => 'Nastavi',
	'layouts_choosecategory' => 'Odaberite kategoriju za $1:',
	'layouts_unknown' => 'Nepoznato',
	'layouts_tagline' => "Ova stranica je generirana od '''$1''' izgleda (''layouta'').",
);

/** Upper Sorbian (Hornjoserbsce)
 * @author Michawiki
 */
$messages['hsb'] = array(
	'layouts-desc' => 'Wuhotuj nowowutworjene strony z wobdźěłujomne  "wuhotowanja", zo by jednotnu strukturu za strony spěchował',
	'layouts_title' => 'Stronu wutworić',
	'layouts_chooselayout' => 'Wubjer wuhotowanje za $1:',
	'layouts_nolayout' => 'Žane wuhotowanje',
	'layouts_continue' => 'Dale',
	'layouts_choosecategory' => 'Wubjer kategoriju za $1:',
	'layouts_unknown' => 'Njeznaty',
	'layouts_tagline' => "Tuta strona bu z wuhotowanjom '''$1''' wutworjena.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Hungarian (Magyar)
 * @author Dani
 * @author Glanthor Reviol
 */
$messages['hu'] = array(
	'layouts-desc' => 'Az újonnan létrehozott lapok feltöltése szerkeszthető „oldaltervvel”, a lapok egységes struktúrájának elősegítésére',
	'layouts_title' => 'Lap létrehozása',
	'layouts_chooselayout' => '$1 oldaltervének kiválasztása:',
	'layouts_nolayout' => 'Nincs oldalterv',
	'layouts_continue' => 'Folytatás',
	'layouts_choosecategory' => 'Válaszd ki $1 kategóriáját:',
	'layouts_unknown' => 'Ismeretlen',
	'layouts_tagline' => "Ez a lap a(z) '''$1''' oldalterv felhasználásával lett generálva.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Interlingua (Interlingua)
 * @author McDutchie
 */
$messages['ia'] = array(
	'layouts-desc' => 'Insere in cata pagina novemente create un "disposition" modificabile pro incoragiar un structura commun a tote le paginas',
	'layouts_title' => 'Crear un pagina',
	'layouts_chooselayout' => 'Selige un disposition pro $1:',
	'layouts_nolayout' => 'Nulle disposition',
	'layouts_continue' => 'Continuar',
	'layouts_choosecategory' => 'Selige un categoria pro $1:',
	'layouts_unknown' => 'Incognite',
	'layouts_tagline' => "Iste pagina ha essite generate con le disposition '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Modificaretiquettasdepaginas',
);

/** Indonesian (Bahasa Indonesia)
 * @author Bennylin
 */
$messages['id'] = array(
	'layouts-desc' => 'Tambahkan ke halaman yang baru dengan "layout" standar untuk menyeragamkan struktur halaman',
	'layouts_title' => 'Buat halaman',
	'layouts_chooselayout' => 'Pilih sebuah "layout" untuk $1:',
	'layouts_nolayout' => '"Layout" tidak ada',
	'layouts_continue' => 'Lanjutkan',
	'layouts_choosecategory' => 'Pilih kategori untuk $1:',
	'layouts_unknown' => 'Tidak diketahui',
	'layouts_tagline' => "Halaman ini ditambahkan oleh \"layout\" '''\$1'''.",
);

/** Igbo (Igbo)
 * @author Ukabia
 */
$messages['ig'] = array(
	'layouts_title' => 'Ké ihü',
	'layouts_continue' => 'Gawákwa',
	'layouts_unknown' => 'Nke námaghị',
);

/** Italian (Italiano)
 * @author Darth Kule
 */
$messages['it'] = array(
	'layouts-desc' => 'Riempie le pagine create di recente con "layout" modificabili per favorire una struttura comune per le pagine',
	'layouts_title' => 'Crea una pagina',
	'layouts_chooselayout' => 'Scegli un layout per $1:',
	'layouts_nolayout' => 'Nessun layout',
	'layouts_continue' => 'Continua',
	'layouts_choosecategory' => 'Scegli una categoria per $1:',
	'layouts_unknown' => 'Sconosciuto',
	'layouts_tagline' => "Questa pagina è stata generata dal layout '''$1'''.",
);

/** Japanese (日本語)
 * @author Fryed-peach
 * @author Hosiryuhosi
 */
$messages['ja'] = array(
	'layouts-desc' => 'ページ構成の共通化をすすめるため、編集可能な「レイアウト」を利用してページを新規作成できるようにする',
	'layouts_title' => 'ページを作成',
	'layouts_chooselayout' => '$1 のレイアウトを選択:',
	'layouts_nolayout' => 'レイアウトなし',
	'layouts_continue' => '続行',
	'layouts_choosecategory' => '$1 のカテゴリを選択:',
	'layouts_unknown' => '不明',
	'layouts_tagline' => "このページは '''$1''' レイアウトを利用して生成されました。",
);

/** Javanese (Basa Jawa)
 * @author Pras
 */
$messages['jv'] = array(
	'layouts_title' => 'Gawé kaca',
	'layouts_chooselayout' => "Pilih rancangan(''layout'') kanggo $1:",
	'layouts_nolayout' => "Ora ana rancangan (''layout'')",
	'layouts_continue' => 'Terusaké',
	'layouts_choosecategory' => 'Pilih kategori kanggo $1:',
	'layouts_unknown' => 'Ora diweruhi',
	'layouts_tagline' => "Kaca iki kacipta nganggo rancangan '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Tagkacasunting',
);

/** Georgian (ქართული)
 * @author Temuri rajavi
 */
$messages['ka'] = array(
	'layouts_title' => 'გვერდის შექმნა',
);

/** Khmer (ភាសាខ្មែរ)
 * @author Thearith
 */
$messages['km'] = array(
	'layouts_title' => 'បង្កើត​ទំព័រ​មួយ',
	'layouts_chooselayout' => 'ជ្រើសរើស​ប្លង់​មួយ​សម្រាប់ $1​៖',
	'layouts_nolayout' => 'មិនមាន​ប្លង់​ទេ',
	'layouts_continue' => 'បន្ត',
	'layouts_choosecategory' => 'ជ្រើរើស​ចំណាត់ក្រុម​មួយ​សម្រាប់ $1​៖',
	'layouts_unknown' => 'មិន​ត្រូវ​បាន​ស្គាល់',
	'layouts_tagline' => "ទំព័រ​នេះ​ត្រូវ​បាន​បង្កើតឡើង​ដោយ​ប្លង់ '''$1''' ។",
);

/** Colognian (Ripoarisch)
 * @author Purodha
 */
$messages['ksh'] = array(
	'layouts-desc' => 'Deit op jede neu aanjelaate Sigg en änderbaa „Läj_aut“ drop, ön ene einheitlijje Opbou för de Sigge ze fördere.',
	'layouts_title' => 'En neu Sigg aanlääje',
	'layouts_chooselayout' => 'Sök e Läj_aut för „$1“ uß:',
	'layouts_nolayout' => 'Keij Läj_aut',
	'layouts_continue' => 'Wigger',
	'layouts_choosecategory' => 'Söök en Saachjrupp för $1 us:',
	'layouts_unknown' => 'Onbikannt',
	'layouts_tagline' => "Hee die Sigg woode met dämm Läj_aut '''$1''' opjebout.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Luxembourgish (Lëtzebuergesch)
 * @author Robby
 */
$messages['lb'] = array(
	'layouts-desc' => 'Verännerbar "Layouten" op nei-ugeluechte Säiten setzen fir eng gemeinsam Struktur fir Säiten z\'ënnerstetzen',
	'layouts_title' => 'Eng Säit uleeën',
	'layouts_chooselayout' => 'E Layout fir $1 eraussichen:',
	'layouts_nolayout' => 'Kee Layout',
	'layouts_continue' => 'Weider',
	'layouts_choosecategory' => 'Wielt eng Kategorie fir $1:',
	'layouts_unknown' => 'Onbekannt',
	'layouts_tagline' => "Dës Säit gouf mam '''$1''' Layout generéiert.",
);

/** Eastern Mari (Олык Марий)
 * @author Сай
 */
$messages['mhr'] = array(
	'layouts_title' => 'Лаштыкым ышташ',
);

/** Macedonian (Македонски)
 * @author Bjankuloski06
 */
$messages['mk'] = array(
	'layouts-desc' => 'Пополни ги новосоздадените страници со уредливи „распореди“ за да поттикнете една иста структура за сите страници',
	'layouts_title' => 'Создај страница',
	'layouts_chooselayout' => 'Изберете распоред за $1:',
	'layouts_nolayout' => 'Без распоред',
	'layouts_continue' => 'Продолжи',
	'layouts_choosecategory' => 'Изберете категорија за $1:',
	'layouts_unknown' => 'Непознато',
	'layouts_tagline' => "Оваа страница е создадена со '''$1''' распоред.",
);

/** Mongolian (Монгол)
 * @author Chinneeb
 */
$messages['mn'] = array(
	'layouts_unknown' => 'Үл мэдэгдэх',
);

/** Malay (Bahasa Melayu)
 * @author Anakmalaysia
 */
$messages['ms'] = array(
	'layouts-desc' => 'Mengisi halaman yang baru diwujudkan dengan "tata letak" yang boleh disunting untuk menggalakkan struktur bersama untuk laman-laman',
	'layouts_title' => 'Cipta laman',
	'layouts_chooselayout' => 'Pilih tataletak untuk $1:',
	'layouts_nolayout' => 'Tiada tataletak',
	'layouts_continue' => 'Sambung',
	'layouts_choosecategory' => 'Pilih kategori untuk $1:',
	'layouts_unknown' => 'Tidak diketahui',
	'layouts_tagline' => "Laman ini dijana oleh tataletak '''$1'''.",
);

/** Erzya (Эрзянь)
 * @author Botuzhaleny-sodamo
 */
$messages['myv'] = array(
	'layouts_unknown' => 'Апак содань',
);

/** Norwegian (bokmål)‬ (‪Norsk (bokmål)‬)
 * @author Nghtwlkr
 */
$messages['nb'] = array(
	'layouts-desc' => 'Befolker nyopprettede sider med redigerbare «utforminger» for å fremme en fellesstruktur for sider',
	'layouts_title' => 'Opprett en side',
	'layouts_chooselayout' => 'Velg et utseende for $1:',
	'layouts_nolayout' => 'Inget utseende',
	'layouts_continue' => 'Fortsett',
	'layouts_choosecategory' => 'Velg en kategori for $1:',
	'layouts_unknown' => 'Ukjent',
	'layouts_tagline' => "Denne siden ble opprettet med utseende '''$1'''.",
);

/** Dutch (Nederlands)
 * @author Siebrand
 */
$messages['nl'] = array(
	'layouts-desc' => "Vult nieuw aangemaakte pagina's met bewerkbare sjablonen om een gelijkvormige structuur voor pagina's aan te moedigen",
	'layouts_title' => 'Pagina aanmaken',
	'layouts_chooselayout' => 'Kies een sjabloon voor $1:',
	'layouts_nolayout' => 'Geen sjabloon',
	'layouts_continue' => 'Volgende',
	'layouts_choosecategory' => 'Kies een categorie voor $1:',
	'layouts_unknown' => 'Onbekend',
	'layouts_tagline' => "Deze pagina is aangemaakt met het sjabloon '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagelabels',
);

/** Norwegian Nynorsk (‪Norsk (nynorsk)‬)
 * @author Harald Khan
 */
$messages['nn'] = array(
	'layouts-desc' => 'Folkeset nyoppretta sider med «utformingar» som kan verta endra for å oppmoda til ein fellesstruktur for sider',
	'layouts_title' => 'Opprett ei sida',
	'layouts_chooselayout' => 'Vel ein utsjånad for $1:',
	'layouts_nolayout' => 'Ingen utsjånad',
	'layouts_continue' => 'Hald fram',
	'layouts_choosecategory' => 'Vel ein kategori for $1:',
	'layouts_unknown' => 'Ukjend',
	'layouts_tagline' => "Denne sida vart oppretta med utforminga '''$1'''.",
);

/** Occitan (Occitan)
 * @author Cedric31
 */
$messages['oc'] = array(
	'layouts-desc' => 'Poblar las paginas creadas novèlament amb de « mesas en pagina » modificablas per encoratjar una estructura comuna a totas las paginas',
	'layouts_title' => 'Crear una pagina',
	'layouts_chooselayout' => 'Causir una mesa en pagina per $1 :',
	'layouts_nolayout' => 'Pas cap de mesa en pagina',
	'layouts_continue' => 'Contunhar',
	'layouts_choosecategory' => 'Causir una categoria per $1 :',
	'layouts_unknown' => 'Desconegut',
	'layouts_tagline' => "Aquesta pagina es estada generida amb la mesa en pagina '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Punjabi (ਪੰਜਾਬੀ)
 * @author Aalam
 */
$messages['pa'] = array(
	'layouts_title' => 'ਇੱਕ ਸਫ਼ਾ ਬਣਾਉ',
	'layouts_chooselayout' => '$1 ਲਈ ਲੇਆਉਟ ਚੁਣੋ:',
	'layouts_nolayout' => 'ਕੋਈ ਲੇਆਉਟ ਨਹੀਂ',
	'layouts_continue' => 'ਜਾਰੀ ਰੱਖੋ',
	'layouts_choosecategory' => '$1 ਲਈ ਕੈਟਾਗਰੀ ਚੁਣੋ:',
	'layouts_unknown' => 'ਅਣਜਾਣ',
	'layouts_tagline' => "ਇਹ ਪੇਜ਼ ਨੂੰ '''$1''' ਲੇਆਉਟ ਨਾਲ ਤਿਆਰ ਕੀਤਾ ਗਿਆ ਹੈ।",
);

/** Deitsch (Deitsch)
 * @author Xqt
 */
$messages['pdc'] = array(
	'layouts_title' => 'Neies Blatt schtaerte',
	'layouts_continue' => 'Weider',
);

/** Polish (Polski)
 * @author Leinad
 * @author Sp5uhe
 */
$messages['pl'] = array(
	'layouts-desc' => 'Wypełnianie nowo utworzonych stron edytowalnym wzorem układu strony, w celu ujednolicania struktury stron',
	'layouts_title' => 'Utwórz stronę',
	'layouts_chooselayout' => 'Wybierz układ strony dla $1:',
	'layouts_nolayout' => 'Brak układu strony',
	'layouts_continue' => 'Kontynuuj',
	'layouts_choosecategory' => 'Wybierz kategorię dla $1:',
	'layouts_unknown' => 'Nieznany',
	'layouts_tagline' => "Ta strona została wygenerowana za pomocą układu strony '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Piedmontese (Piemontèis)
 * @author Dragonòt
 */
$messages['pms'] = array(
	'layouts-desc' => 'Vemp le neuve pàgine con "layouts" modificàbij për ancoragé na strutura comun-a dle pàgine',
	'layouts_title' => 'Crea na pàgina',
	'layouts_chooselayout' => 'Sern un layaut për $1:',
	'layouts_nolayout' => 'Pa gnun layaut',
	'layouts_continue' => 'Continua',
	'layouts_choosecategory' => 'Sern na categorìa për $1:',
	'layouts_unknown' => 'Pa conossù',
	'layouts_tagline' => "Sta pàgina-sì a l'é generà dal layout '''$1'''.",
);

/** Pashto (پښتو)
 * @author Ahmed-Najib-Biabani-Ibrahimkhel
 */
$messages['ps'] = array(
	'layouts_title' => 'يو مخ جوړول',
	'layouts_nolayout' => 'اډانه نشته',
	'layouts_choosecategory' => 'د $1 لپاره يوه وېشنيزه وټاکۍ:',
	'layouts_unknown' => 'ناجوت',
);

/** Portuguese (Português)
 * @author Malafaya
 * @author Waldir
 */
$messages['pt'] = array(
	'layouts-desc' => 'Preencher as páginas recém-criadas com modelos editáveis para fomentar uma estrutura comum para as páginas',
	'layouts_title' => 'Criar uma página',
	'layouts_chooselayout' => 'Escolha um modelo para $1:',
	'layouts_nolayout' => 'Nenhum modelo',
	'layouts_continue' => 'Continuar',
	'layouts_choosecategory' => 'Escolha uma categoria para $1:',
	'layouts_unknown' => 'Desconhecido',
	'layouts_tagline' => "Esta página foi gerada pelo modelo '''$1'''.",
);

/** Brazilian Portuguese (Português do Brasil)
 * @author Eduardo.mps
 */
$messages['pt-br'] = array(
	'layouts-desc' => 'Preencher as páginas recém-criadas com modelos editáveis para fomentar uma estrutura comum para as páginas',
	'layouts_title' => 'Criar uma página',
	'layouts_chooselayout' => 'Escolher um Layout para o $1:',
	'layouts_nolayout' => 'Sem layout',
	'layouts_continue' => 'Continuar',
	'layouts_choosecategory' => 'Escolher uma Categoria para o $1:',
	'layouts_unknown' => 'Desconhecido',
	'layouts_tagline' => 'Esta página foi gerada pelo layout <strong>$1</strong>.',
);

/** Romanian (Română)
 * @author Firilacroco
 * @author KlaudiuMihaila
 */
$messages['ro'] = array(
	'layouts_title' => 'Creează o pagină',
	'layouts_continue' => 'Continuă',
	'layouts_choosecategory' => 'Alegeți o categorie pentru $1:',
	'layouts_unknown' => 'Necunoscut',
);

/** Tarandíne (Tarandíne)
 * @author Joetaras
 */
$messages['roa-tara'] = array(
	'layouts-desc' => 'Popole pàggene nuève e ccrejate cu "disposiziune" cangiabbele pe \'ngoraggià \'na strutture comune pe le pàggene',
	'layouts_title' => "Ccreje 'na vosce",
	'layouts_chooselayout' => "Scacchie 'na disposizione pe $1:",
	'layouts_nolayout' => 'Nisciuna disposizione',
	'layouts_continue' => 'Condinue',
	'layouts_choosecategory' => "Scacchie 'a categorije pe $1:",
	'layouts_unknown' => 'Scanusciute',
	'layouts_tagline' => "Sta pàgene ga state generate da 'a disposizione '''$1'''.",
);

/** Russian (Русский)
 * @author Ferrer
 * @author Александр Сигачёв
 */
$messages['ru'] = array(
	'layouts-desc' => 'Заполняет вновь создаваемые страницы редактируемыми «макетами» с целью по поддерживать типовую структуру страниц.',
	'layouts_title' => 'Создать страницу',
	'layouts_chooselayout' => 'Выбор макета для $1:',
	'layouts_nolayout' => 'Нет макета',
	'layouts_continue' => 'Продолжить',
	'layouts_choosecategory' => 'Выбор категории для $1:',
	'layouts_unknown' => 'Неизвестно',
	'layouts_tagline' => "Эта страница была создана с помощью макета '''$1'''.",
);

/** Rusyn (Русиньскый)
 * @author Gazeb
 */
$messages['rue'] = array(
	'layouts_title' => 'Створити сторінку',
	'layouts_continue' => 'Продовжовати',
);

/** Sinhala (සිංහල)
 * @author Calcey
 */
$messages['si'] = array(
	'layouts-desc' => 'පිටු සඳහා පොදු ව්‍යුහයක් දිරිමත් කිරීමට සංස්කරණය කළ හැකි "පිරිසැලසුම්" සමඟ අළුතින්ම නිර්මාණය කළ පිටු ජනප්‍රිය කිරීම',
	'layouts_title' => 'පිටුවක් නිර්මාණය කරන්න',
	'layouts_chooselayout' => '$1 සඳහා පිරිසැලසුමක් තෝරාගන්න:',
	'layouts_nolayout' => 'පිරිසැලසුමක් නැත',
	'layouts_continue' => 'දිගටම කරගෙන යන්න',
	'layouts_choosecategory' => '$1 සඳහා ප්‍රවර්ගයක් තෝරාගන්න:',
	'layouts_unknown' => 'නාඳුනන',
	'layouts_tagline' => "'''$1''' පිරිසැලැස්ම මඟින් මෙම පිටුව ජනනය කරන ලදී.",
);

/** Slovak (Slovenčina)
 * @author Helix84
 */
$messages['sk'] = array(
	'layouts-desc' => 'Naplní novo vytvorené stránky rozloženiami, ktoré možno upravovať, aby sa posilnila spoločná štruktúra stránok',
	'layouts_title' => 'Vytvoriť stránku',
	'layouts_chooselayout' => 'Vyberte rozloženie pre $1:',
	'layouts_nolayout' => 'Žiadne rozloženie',
	'layouts_continue' => 'Pokračovať',
	'layouts_choosecategory' => 'Vyberte kategóriu pre $1:',
	'layouts_unknown' => 'Neznáme',
	'layouts_tagline' => "Túto stránku vytvorilo rozloženie '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Slovenian (Slovenščina)
 * @author Dbc334
 */
$messages['sl'] = array(
	'layouts-desc' => 'Obda na novo ustvarjene strani z uredljivimi »postavitvami«, ki vzpodbudijo skupno zgradbo strani',
	'layouts_title' => 'Ustvari stran',
	'layouts_chooselayout' => 'Izberite postavitev za $1:',
	'layouts_nolayout' => 'Ni postavitve',
	'layouts_continue' => 'Nadaljuj',
	'layouts_choosecategory' => 'Izberite kategorijo za $1:',
	'layouts_unknown' => 'Neznano',
	'layouts_tagline' => "Ta stran je bila ustvarjena s postavitvijo '''$1'''.",
);

/** Serbian (Cyrillic script) (‪Српски (ћирилица)‬)
 * @author Rancher
 * @author Михајло Анђелковић
 */
$messages['sr-ec'] = array(
	'layouts_title' => 'Направи чланак',
	'layouts_continue' => 'Настави',
	'layouts_choosecategory' => 'Изабери категорију за $1:',
	'layouts_unknown' => 'Непознато',
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Serbian (Latin script) (‪Srpski (latinica)‬)
 * @author Michaello
 */
$messages['sr-el'] = array(
	'layouts_title' => 'Napravi članak',
	'layouts_continue' => 'Nastavi',
	'layouts_choosecategory' => 'Izaberi kategoriju za $1:',
	'layouts_unknown' => 'Nepoznato',
	'layouts-layoutcategorypage' => 'MediaWiki:Editpagetags',
);

/** Seeltersk (Seeltersk)
 * @author Pyt
 */
$messages['stq'] = array(
	'layouts-desc' => 'Bestukket frisk moakede Sieden mäd beoarbaidboare „Gestaltengen“, uum ne eenhaidlike Struktur fon Sieden tou föärderjen',
	'layouts_title' => 'Näie Siede moakje',
	'layouts_chooselayout' => 'Säik n Formoat foar $1 uut:',
	'layouts_nolayout' => 'Neen Formoat',
	'layouts_continue' => 'Fääre',
	'layouts_choosecategory' => 'Säik ne Kategorie foar $1 uut:',
	'layouts_unknown' => 'Uunbekoand',
	'layouts_tagline' => "Disse Siede wuud mäd dät '''$1''' moaked.",
);

/** Swedish (Svenska)
 * @author Najami
 */
$messages['sv'] = array(
	'layouts_title' => 'Skapa en sida',
	'layouts_chooselayout' => 'Välj ett utseende för $1:',
	'layouts_nolayout' => 'Inget utseende',
	'layouts_continue' => 'Fortsätt',
	'layouts_choosecategory' => 'Välj en kategori för $1:',
	'layouts_unknown' => 'Okänd',
);

/** Tamil (தமிழ்)
 * @author Mahir78
 * @author TRYPPN
 */
$messages['ta'] = array(
	'layouts-desc' => "தொகுக்கக்கூடிய ''பக்கவடிமைப்பை'' புதிய பக்கங்கள் உருவாக்கும் போது ஒரு பொதுவான அமைப்பு கொண்ட பக்கங்களை உருவாக்க எல்லோருக்கும் தெரிவித்து ஊக்கப்படுத்துங்கள்",
	'layouts_title' => 'ஒரு பக்கத்தை உருவாக்கவும்',
	'layouts_chooselayout' => '$1 க்கான ஒரு இடைமுகப்பை தேர்ந்தெடுக்கவும்',
	'layouts_nolayout' => 'வடிவமைப்பு இல்லை',
	'layouts_continue' => 'தொடரவும்',
	'layouts_choosecategory' => '$1 க்கான ஒரு பகுப்பை தேர்ந்தெடுக்கவும்',
	'layouts_unknown' => 'தெரியாது',
	'layouts_tagline' => "இப்பக்கம் '''$1''' வடிவமைப்பின் மூலம் உருவாக்கப்பட்டுள்ளது.",
);

/** Telugu (తెలుగు)
 * @author Kiranmayee
 * @author Veeven
 */
$messages['te'] = array(
	'layouts_title' => 'ఒక పేజీని సృష్టించండి',
	'layouts_continue' => 'కొనసాగించు',
	'layouts_choosecategory' => '$1కి ఒక వర్గాన్ని ఎంచుకోండి:',
	'layouts_unknown' => 'అజ్ఞాతం',
	'layouts_tagline' => "ఈ పేజీ '''$1''' అమరిక ద్వారా తయారైంది.",
);

/** Turkmen (Türkmençe)
 * @author Hanberke
 */
$messages['tk'] = array(
	'layouts_title' => 'Sahypa döret',
	'layouts_nolayout' => 'Bezeg ýok',
	'layouts_continue' => 'Dowam et',
	'layouts_unknown' => 'Näbelli',
);

/** Tagalog (Tagalog)
 * @author AnakngAraw
 */
$messages['tl'] = array(
	'layouts-desc' => 'Panahanan (dagdagan pa ng laman) ang mga bagong likhang pahina na may maaaring baguhing mga "anyo ng pagkakalatag" upang makahimok ng isang karaniwang kayarian para sa mga pahina',
	'layouts_title' => 'Lumikha ng isang pahina',
	'layouts_chooselayout' => 'Pumili ng anyo ng pagkakalatag para sa $1:',
	'layouts_nolayout' => 'Walang anyo ng paglalatag',
	'layouts_continue' => 'Magpatuloy',
	'layouts_choosecategory' => 'Pumili ng isang kaurian para sa $1:',
	'layouts_unknown' => 'Hindi nalalaman',
	'layouts_tagline' => "Ginawa ang pahinang ito sa pamamagitan ng anyo ng pagkakalatag na '''$1'''.",
	'layouts-layoutcategorypage' => 'MediaWiki:Baguhinpahinamgatatak',
);

/** Turkish (Türkçe)
 * @author Joseph
 * @author Karduelis
 * @author Vito Genovese
 */
$messages['tr'] = array(
	'layouts-desc' => 'Sayfalar için ortak bir yapı aşılama amacıyla yeni oluşturulmuş sayfalara değiştirilebilir "tasarımlar" ekler',
	'layouts_title' => 'Bir sayfa oluştur',
	'layouts_chooselayout' => '$1 için bir düzen seçin:',
	'layouts_nolayout' => 'Düzen yok',
	'layouts_continue' => 'Devam',
	'layouts_choosecategory' => '$1 için bir kategori seçin:',
	'layouts_unknown' => 'Bilinmiyor',
	'layouts_tagline' => "Bu sayfa '''$1''' düzeni ile oluşturulmuştur.",
);

/** Ukrainian (Українська)
 * @author Prima klasy4na
 * @author Тест
 */
$messages['uk'] = array(
	'layouts_title' => 'Створити сторінку',
	'layouts_continue' => 'Продовжити',
	'layouts_choosecategory' => 'Вибір категорії для $1:',
);

/** Veps (Vepsän kel')
 * @author Triple-ADHD-AS
 * @author Игорь Бродский
 */
$messages['vep'] = array(
	'layouts-desc' => 'Täutab uded lehtesed redaktiruidud "šablonil", miše lehtpoliden tipine struktur oliži ühtejitte.',
	'layouts_title' => "Säta lehtpol'",
	'layouts_chooselayout' => 'Valikat maket $1-n täht:',
	'layouts_nolayout' => 'Eile maketad',
	'layouts_continue' => 'Jatkata',
	'layouts_choosecategory' => 'Valikat kategorii $1-n täht:',
	'layouts_unknown' => 'Tundmatoi',
	'layouts_tagline' => "Nece lehtpol' sätihe '''$1'''-maketan abul.",
);

/** Vietnamese (Tiếng Việt)
 * @author Minh Nguyen
 * @author Vinhtantran
 */
$messages['vi'] = array(
	'layouts-desc' => 'Tập hợp các trang mới được khởi tạo bằng "kiểu trình bày" cho phép thay đổi để khuyến khích một cấu trúc chung cho các trang',
	'layouts_title' => 'Tạo trang',
	'layouts_chooselayout' => 'Chọn một kiểu trình bày cho $1:',
	'layouts_nolayout' => 'Không có kiểu trình bày',
	'layouts_continue' => 'Tiếp tục',
	'layouts_choosecategory' => 'Chọn một thể loại cho $1:',
	'layouts_unknown' => 'Không biết',
	'layouts_tagline' => "Trang này được tạo ra theo cách trình bày '''$1'''.",
);

/** Volapük (Volapük)
 * @author Smeira
 */
$messages['vo'] = array(
	'layouts_title' => 'Jafön padi',
	'layouts_continue' => 'Föfiö!',
	'layouts_choosecategory' => 'Välön kladi pro $1:',
	'layouts_unknown' => 'Nesevädik',
);

/** Yiddish (ייִדיש)
 * @author פוילישער
 */
$messages['yi'] = array(
	'layouts_title' => 'שאַפֿן א בלאַט',
	'layouts_unknown' => 'אומבאַוואוסט',
);

/** Simplified Chinese (‪中文(简体)‬)
 * @author Gzdavidwong
 * @author Liangent
 * @author Wilsonmess
 * @author Xiaomingyan
 */
$messages['zh-hans'] = array(
	'layouts_title' => '创建页面',
	'layouts_chooselayout' => '为$1选择一个样式：',
	'layouts_nolayout' => '没有布局',
	'layouts_continue' => '继续',
	'layouts_choosecategory' => '为$1选择一个分类：',
	'layouts_unknown' => '未知',
);

/** Traditional Chinese (‪中文(繁體)‬)
 * @author Gzdavidwong
 * @author Liangent
 * @author Mark85296341
 * @author Wrightbus
 */
$messages['zh-hant'] = array(
	'layouts_title' => '建立一個頁面',
	'layouts_chooselayout' => '為$1選擇一個樣式：',
	'layouts_nolayout' => '沒有布局',
	'layouts_continue' => '繼續',
	'layouts_choosecategory' => '為 $1 選擇一個分類：',
	'layouts_unknown' => '未知',
);

