FROM artifactory.wikia-inc.com/sus/php-wikia-base:da4390f

ADD app /usr/wikia/slot1/current/src
ADD config /usr/wikia/slot1/current/config

RUN mkdir -p /usr/wikia/slot1/current/cache/messages
RUN chmod 777 /usr/wikia/slot1/current/cache/messages
RUN SERVER_ID=177 php maintenance/rebuildLocalisationCache.php --threads=4

USER nobody
