// Generated by CoffeeScript 1.6.1
(function() {
	var ResourceView,
		__hasProp = {}.hasOwnProperty,
		__extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

	ResourceView = (function(_super) {

		__extends(ResourceView, _super);

		function ResourceView() {
			return ResourceView.__super__.constructor.apply(this, arguments);
		}

		ResourceView.prototype.initialize = function() {};

		ResourceView.prototype.render = function() {
			var operation, _i, _len, _ref;
			$(this.el).html(Handlebars.templates.resource(this.model));
			this.number = 0;
			_ref = this.model.operationsArray;
			for (_i = 0, _len = _ref.length; _i < _len; _i++) {
				operation = _ref[_i];
				this.addOperation(operation);
			}
			return this;
		};

		ResourceView.prototype.addOperation = function(operation) {
			var operationView;
			operation.number = this.number;
			operationView = new OperationView({
				model: operation,
				tagName: 'li',
				className: 'endpoint'
			});
			$('.endpoints', $(this.el)).append(operationView.render().el);
			return this.number++;
		};

		return ResourceView;

	})(Backbone.View);

	window.ResourceView = ResourceView; // make it public
}).call(this);
