CKEDITOR.plugins.setLang( 'rte-link', RTE.config.language, {
	'add' :		window.mw.msg('rte-ck-link-add'),
        'error-badPageTitle' : window.mw.msg('rte-ck-error-badPageTitle'),
        'error-badUrl' :window.mw.msg('rte-ck-link-error-badUrl'),
        'error-title' :window.mw.msg('rte-ck-link-error-title'),
        'external-linkText' :window.mw.msg('rte-ck-link-external-linkText'),
        'external-numberedLink':window.mw.msg('rte-ck-link-numberedLink'),
        'external-tab' : window.mw.msg('rte-ck-link-tab'),
        'external-url': window.mw.msg('rte-ck-link-url'),
        'internal-linkText' :window.mw.msg('rte-ck-link-linkText'),
        'internal-pageName' :window.mw.msg('rte-ck-link-pageName'),
        'internal-tab' : window.mw.msg('rte-ck-link-tab'),
        'title' : window.mw.msg('rte-ck-link-title'),
        'label-target' : window.mw.msg('rte-ck-link-target'),
        'label-display' : window.mw.msg('rte-ck-link-display'),
        'label-internal' : window.mw.msg('rte-ck-link-internal'),
        'label-external' : window.mw.msg('rte-ck-link-external'),
        'status-checking' : window.mw.msg('rte-ck-link-status-checking'),
        'status-exists' : window.mw.msg('rte-ck-link-status-exists'),
        'status-notexists' : window.mw.msg('rte-ck-link-status-notexists'),
        'status-external' : window.mw.msg('rte-ck-link-external'),
	
	'unlink' :      window.mw.msg('rte-ck-unlink'),

	'toolbar' : window.mw.msg('rte-ck-link-toolbar'),
	'other' : window.mw.msg('rte-ck-link-other'),
	'menu' : window.mw.msg('rte-ck-link-menu'),
	'title' : window.mw.msg('rte-ck-link-title'),
	'info' : window.mw.msg('rte-ck-link-info'),
	'target' : window.mw.msg('rte-ck-link-target'),
	'upload' : window.mw.msg('rte-ck-link-upload'),
	'advanced' : window.mw.msg('rte-ck-link-advanced'),
	'type' : window.mw.msg('rte-ck-link-type'),
	'toUrl' : window.mw.msg('rte-ck-link-toUrl'),
	'toAnchor' : window.mw.msg('rte-ck-link-toAnchor'),
	'toEmail' : window.mw.msg('rte-ck-link-toEmail'),
	'targetFrame' : window.mw.msg('rte-ck-link-targetFrame'),
	'targetPopup' : window.mw.msg('rte-ck-link-targetPopup'),
	'targetFrameName' : window.mw.msg('rte-ck-link-targetFrameName'),
	'targetPopupName' : window.mw.msg('rte-ck-link-targetPopupName'),
	'popupFeatures' : window.mw.msg('rte-ck-link-popupFeatures'),
	'popupResizable' : window.mw.msg('rte-ck-link-popupResizable'),
	'popupStatusBar' : window.mw.msg('rte-ck-link-popupStatusBar'),
	'popupLocationBar' : window.mw.msg('rte-ck-link-popupLocationBar'),
	'popupToolbar' : window.mw.msg('rte-ck-link-popupToolbar'),
	'popupMenuBar' : window.mw.msg('rte-ck-link-popupMenuBar'),
	'popupFullScreen' : window.mw.msg('rte-ck-link-popupFullscreen'),
	'popupScrollBars' : window.mw.msg('rte-ck-link-popupScrollBars'),
	'popupDependent' : window.mw.msg('rte-ck-link-popupDependent'),
	'popupLeft' : window.mw.msg('rte-ck-link-popupLeft'),
	'popupTop' : window.mw.msg('rte-ck-link-popupTop'),
	'id' : window.mw.msg('rte-ck-link-id'),
	'langDir' : window.mw.msg('rte-ck-link-langDir'),
	'langDirLTR' : window.mw.msg('rte-ck-link-langDirLTR'),
	'langDirRTL' : window.mw.msg('rte-ck-link-langDirRTL'),
	'acccessKey' : window.mw.msg('rte-ck-link-acccessKey'),
	'name' : window.mw.msg('rte-ck-link-name'),
	'langCode' : window.mw.msg('rte-ck-link-langCode'),
	'tabIndex' : window.mw.msg('rte-ck-link-tabIndex'),
	'advisoryTitle' : window.mw.msg('rte-ck-link-advisoryTitle'),
	'advisoryContentType' : window.mw.msg('rte-ck-link-advisoryContentType'),
	'cssClasses' : window.mw.msg('rte-ck-link-cssClasses'),
	'charset' : window.mw.msg('rte-ck-link-charset'),
	'styles' : window.mw.msg('rte-ck-link-styles'),
	'rel' : window.mw.msg('rte-ck-link-rel'),
	'selectAnchor' : window.mw.msg('rte-ck-link-selectAnchor'),
	'anchorName' : window.mw.msg('rte-ck-link-anchorName'),
	'anchorId' : window.mw.msg('rte-ck-link-anchorId'),
	'emailAddress' : window.mw.msg('rte-ck-link-emailAddress'),
	'emailSubject' : window.mw.msg('rte-ck-link-emailSubject'),
	'emailBody' : window.mw.msg('rte-ck-link-emailBody'),
	'noAnchors' : window.mw.msg('rte-ck-link-noAnchors'),
	'noUrl' : window.mw.msg('rte-ck-link-noUrl'),
	'noEmail' : window.mw.msg('rte-ck-link-noEmail'),
} );
