require([
	'ext.wikia.adEngine.adContext',
	'ext.wikia.adEngine.wad.hmdRecLoader'
], function (adContext, hmdRecLoader) {
	var exportz = exportz || {};
	(function(exports) {
		"use strict";

		var conf = hmdRecLoader.getConfig();
		var exportz=exportz||{};

(function(k){k=k||{};(function(h){function b(){this.A="setup";this.s();window.addEventListener("message",this.F.bind(this))}h.m=b;b.prototype={s:function(){this.a={urls:{},homadUrls:{},originalUrls:{},scripts:{},eventlistener:[],generalEventlistener:[],iFrames:[],iFrameOnLoadHandler:{},iFrameUrl:"",trace:[],stack:[],errmsg:[]}},postMessage:function(a,d){try{a.contentWindow&&(a=a.contentWindow)}catch(e){}a&&a.postMessage&&a.postMessage(d,"*")},F:function(a){a&&a.data&&a.data.type&&"vpaid"==a.data.type&&
this.D(a.data)},D:function(a){if(this.a&&this.a.eventlistener)for(var d=this.a.eventlistener.length,e=0;e<d;e++)this.a&&this.a.eventlistener&&a.event==this.a.eventlistener[e].name&&this.a.eventlistener[e].cb(a)},j:function(a){a=a&&"number"===typeof a&&0<a?Math.round(a):10;for(var d="",e=0;e<a;e++)d+=String.fromCharCode((.5>Math.random()?65:97)+Math.floor(26*Math.random()));return d},h:function(a){var d=0,e,c;if(0===a.length)return d;for(e=0;e<a.length;e++)c=a.charCodeAt(e),d=(d<<5)-d+c,d|=0;return d},
G:function(a){function d(a){var c="",d,b;for(d=7;0<=d;d--)b=a>>>4*d&15,c+=b.toString(16);return c}function e(a,c){return a<<c|a>>>32-c}var c,b,q=Array(80),h=1732584193,n=4023233417,u=2562383102,w=271733878,k=3285377520,f,l,m,p,r;a=a&&"string"===typeof a?a:"";f=a.length;var v=[];for(c=0;c<f-3;c+=4)b=a.charCodeAt(c)<<24|a.charCodeAt(c+1)<<16|a.charCodeAt(c+2)<<8|a.charCodeAt(c+3),v.push(b);switch(f%4){case 0:c=2147483648;break;case 1:c=a.charCodeAt(f-1)<<24|8388608;break;case 2:c=a.charCodeAt(f-2)<<
24|a.charCodeAt(f-1)<<16|32768;break;case 3:c=a.charCodeAt(f-3)<<24|a.charCodeAt(f-2)<<16|a.charCodeAt(f-1)<<8|128}for(v.push(c);14!=v.length%16;)v.push(0);v.push(f>>>29);v.push(f<<3&4294967295);for(a=0;a<v.length;a+=16){for(c=0;16>c;c++)q[c]=v[a+c];for(c=16;79>=c;c++)q[c]=e(q[c-3]^q[c-8]^q[c-14]^q[c-16],1);b=h;f=n;l=u;m=w;p=k;for(c=0;19>=c;c++)r=e(b,5)+(f&l|~f&m)+p+q[c]+1518500249&4294967295,p=m,m=l,l=e(f,30),f=b,b=r;for(c=20;39>=c;c++)r=e(b,5)+(f^l^m)+p+q[c]+1859775393&4294967295,p=m,m=l,l=e(f,
30),f=b,b=r;for(c=40;59>=c;c++)r=e(b,5)+(f&l|f&m|l&m)+p+q[c]+2400959708&4294967295,p=m,m=l,l=e(f,30),f=b,b=r;for(c=60;79>=c;c++)r=e(b,5)+(f^l^m)+p+q[c]+3395469782&4294967295,p=m,m=l,l=e(f,30),f=b,b=r;h=h+b&4294967295;n=n+f&4294967295;u=u+l&4294967295;w=w+m&4294967295;k=k+p&4294967295}return(d(h)+d(n)+d(u)+d(w)+d(k)).toLowerCase()},b:function(a){for(var d="",b,c,z,h,k,n,u=0;u<a.length;)b=a.charCodeAt(u++),c=a.charCodeAt(u++),z=a.charCodeAt(u++),h=b>>2,b=(b&3)<<4|c>>4,k=(c&15)<<2|z>>6,n=z&63,isNaN(c)?
k=n=64:isNaN(z)&&(n=64),d=d+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(h)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(b)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(k)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(n);return d},fireEvent:function(a,d,b){var c;b.state=this.A;"function"===typeof window.CustomEvent?c=new CustomEvent(d,{detail:b}):(c=document.createEvent("CustomEvent"),
c.initCustomEvent(d,!1,!1,b));a.dispatchEvent(c)},u:function(a,d,b){d||(d="hdEvent");b||(b=window);this.fireEvent(b,d,a)},track:function(a,b,e){if(e)if(!homad||!homad.aa)window.setTimeout(function(){this.track(a,b,e)}.bind(this),500);else if(homad.isEnabled){a&&a.trim&&(a=a.trim());b&&b.trim&&(b=b.trim());var c=a+b;this.c||(this.c={});this.c[c]||(this.c[c]=0);this.c[c]++;10<this.c[c]||(c=homad.ga()+"?homad_track_key="+encodeURIComponent(a)+"&homad_track_value="+encodeURIComponent(b),homad.w(c,!0),
c=homad.w(c,!0),c.data.homad_url_prefix_alias="",c.data.homad_track_key="*"+encodeURIComponent(a)+"*",c.data.homad_track_value="*"+encodeURIComponent(b)+"*",homad.da(c,function(c){var e=!1;c=c.responseText;try{c=JSON.parse(c),c=c.data,c[0]==encodeURIComponent(a)&&(e=!0),c[1]&&c[1]!=encodeURIComponent(b)&&(e=!1)}catch(h){}e||this.track("stats_hd_trackcheck",(c[0]?c[0]:"")+(c[1]?c[1]:""),!0)}.bind(this)))}}}})(k);var y=k.m||y;new y;var h=new y;window.g=h;(function(h){function b(a){this.data=a||{}}h.l=
b;b.K=function(a,b){var e={},c;for(c in b)e[c]=b[c];for(c in a)e[c]=a[c];return e};b.C={code:"1000",type:"penalty",message:"",name:"penalty"};b.M={code:"1001",type:"mediaerror",message:"",name:"adError"};b.R={code:"1002",type:"vpaid",message:"",name:"vpaid"};b.I={code:"1003",type:"emptyVast",message:"",name:"adError"};b.T={code:"1004",type:"malformattedXML",message:"",name:"adError"};b.ea={code:"1005",type:"adStart",message:"",name:"adStart"};b.U={code:"1006",type:"adFirstQuartile",message:"",name:"adFirstQuartile"};
b.X={code:"1007",type:"adMidPoint",message:"",name:"adMidPoint"};b.fa={code:"1008",type:"adThirdQuartile",message:"",name:"adThirdQuartile"};b.g={code:"1009",type:"adComplete",message:"",name:"adComplete"};b.V={code:"1010",type:"adImpressionsCalled",message:"",name:"adImpression"};b.P={code:"1011",type:"vastLoadingFailed",message:"",name:"adError"};b.L={code:"1012",type:"noCreative",message:"",name:"adError"};b.J={code:"1013",type:"emptyVastFromHomadServerEvent",message:"",name:"adError"};b.S={code:"1014",
type:"wrapperLimitReached",message:"",name:"adError"};b.ia={code:"1015",type:"clickthrough",message:"",name:"adClick"};b.H={code:"1016",type:"continueContent",message:"",name:"continueContent"};b.ka={code:"1017",type:"contentPlayerPlay",message:"",name:"contentPlayerPlay"};b.ja={code:"1018",type:"contentPlayerPause",message:"",name:"contentPlayerPause"};b.ca={code:"1019",type:"adSkipped",message:"",name:"adSkipped"};b.ba={code:"1020",type:"adRequest",message:"",name:"adRequest"};b.Z={code:"1021",
type:"adPlay",message:"",name:"adPlay"};b.Y={code:"1022",type:"adPause",message:"",name:"adPause"};b.ha={code:"1023",type:"adTime",message:"",name:"adTime"};b.W={code:"1024",type:"adMeta",message:"",name:"adMeta"};b.O={code:"9001",type:"variableDeletedEvent",message:"",name:"variableDeletedEvent"};b.N={code:"9002",type:"noVariableSettingEvent",message:"",name:"noVariableSettingEvent"};b.prototype={}})(k);var G=k.l||G;(function(h){function b(){}h.o=b;b.prototype={h:function(a){var b=0,e,c,h;if(0==
a.length)return b;e=0;for(h=a.length;e<h;e++)c=a.charCodeAt(e),b=(b<<5)-b+c,b|=0;return Math.abs(b)},v:function(){return Math.round(Date.now()/1E3/3600/24)+navigator.appCodeName+navigator.appName+navigator.appVersion+navigator.userAgent+navigator.platform+(navigator.language||navigator.g||"x")},f:function(a){a=parseInt(a);if(65<=a&&90>=a||97<=a&&122>=a)return String.fromCharCode(a);if(0>=a)return"";if(65>a)return this.f(a+65);if(90<a)return this.f(Math.round(a/2))},reverse:function(a){for(var b="",
e=a.length-1,b="";0<=e;b+=a[e--]);return b},i:function(){for(var a=this.h(this.v()+""),a=(a+""+this.reverse(a+"")).match(/.{1,2}/g),b="",e=0;e<a.length;e++)b+=this.f(a[e]);0==b.length&&(b="zork");return b},B:function(){return this.i()+"2"}}})(k);var F=k.o||F;(function(){function k(){for(var b=document.getElementsByTagName("video"),a=0;a<b.length;a++){try{b[a]&&b[a].pause&&"function"==typeof b[a].pause&&b[a].pause()}catch(c){}b[a].parentNode.removeChild(b[a])}b=document.getElementsByTagName("object");
for(a=0;a<b.length;a++)b[a].parentNode.removeChild(b[a]);b=document.getElementsByClassName("video-wrapper");for(a=0;a<b.length;a++)b[a]&&b[a].parentNode&&b[a].parentNode.removeChild(b[a]);b=document.getElementsByClassName("videoplayer");for(a=0;a<b.length;a++)b[a]&&b[a].parentNode&&b[a].parentNode.removeChild(b[a]);if(window.self!=window.top)for(b=window.document;b.hasChildNodes();)b.removeChild(b.lastChild)}function b(){var b;if(b=y()){var a="fail-init-100.gif"+u();n(b,function(){},function(){},
{homad_url_prefix_alias:"homadvastimpressions",homad_url_suffix_base64:h.b(a),homad_url_suffix:a,homad_hash_guessed:"true"})}h.u(G.C);m&&"function"===typeof m?m():(k(),window.setInterval(k,500),window.setTimeout(k,1500))}function a(){if(D){var a=new XMLHttpRequest;a.onreadystatechange=function(){4==a.readyState&&200==a.status&&e("data:text/javascript;base64,"+h.b(a.responseText),b);4==a.readyState&&200!=a.status&&b()};a.open("GET","https://s3.amazonaws.com/homad-global-configs.schneevonmorgen.com/hd-main.js"+
w(),!0);a.send()}else e("https://s3.amazonaws.com/homad-global-configs.schneevonmorgen.com/hd-main.js"+w(),!1)}function d(){if(l)conf.startPlayer&&eval(conf.startPlayer),document.fp_error=!0,document.hd_ready=!0;else{if(D){var t=new XMLHttpRequest;t.onreadystatechange=function(){4==t.readyState&&200==t.status&&e("data:text/javascript;base64,"+h.b(t.responseText),a);4==t.readyState&&200!=t.status&&(E?b():a())};if(E){t.withCredentials=!0;t.open("POST",y(),!0);var d={homad_url_prefix_alias:"hgccfcache1svonmcom",
homad_url_suffix:"/hd-main.js"};d.homad_url_suffix_base64=h.b("hd-main.js");var f=d,d="",k;for(k in f)d+="&"+k+"="+encodeURIComponent(f[k]);d=d.substr(1);t.setRequestHeader("Content-type","application/x-www-form-urlencoded");t.send(d)}else t.open("GET","https://hgc-cf-cache-1.svonm.com/hd-main.js"+w(),!0),t.send()}else e("https://hgc-cf-cache-1.svonm.com/hd-main.js"+w(),!1);var m=new F;document.createEvent("CustomEvent");conf.version="20181129_1415_1247";H(function(){h.fireEvent(window,m.i(),conf)},
Math.round(400+200*Math.random()));c()}}function e(a,b){var c=document.createElement("script");c.type="text/javascript";c.src=a;c.onerror=b;document.head.firstChild?document.head.insertBefore(c,document.head.firstChild):document.head.appendChild(c)}function c(){var a=new F;I=C(function(){k()},Math.round(14E3+2E3*Math.random()));window.addEventListener(a.B(),function(a){window.clearTimeout(I);window.clearTimeout(a.detail.id)})}function z(a){n(y(),function(a){var c=document.createElement("script");
c.type="text/javascript";c.src="data:text/javascript;base64,"+h.b(a);c.onerror=b;document.head.firstChild?document.head.insertBefore(c,document.head.firstChild):document.head.appendChild(c);C(d,0)},b,{homad_url_prefix_alias:"s3homadglobalconfigs",homad_url_suffix_base64:h.b(a),homad_url_suffix:a,homad_hash_guessed:"true"},!0)}function q(a){l?d():(l=!f(a.enabled),a.hasOwnProperty("mainAsXHR")&&0==a.mainAsXHR&&(D=f(a.mainAsXHR)),a.hasOwnProperty("mainThroughHOMAD")&&(E=f(a.mainThroughHOMAD)),!l&&a.embedload?
z(a.embedload):d())}function B(a){p=a;l?d():(l=!f(a.enabled))?d():n(a.config,q,d)}function n(a,b,c,d,e){var f=new XMLHttpRequest;f.onreadystatechange=function(){if(b&&4==f.readyState&&200==f.status)if(e)b(f.responseText);else{var a={};try{a=J.parse(f.responseText)}catch(d){a.enabled="false"}b(a)}c&&4==f.readyState&&200!=f.status&&c(f)};try{if(d){f.open("POST",a,!0);a=d;d="";for(var h in a)d+="&"+h+"="+encodeURIComponent(a[h]);d=d.substr(1);f.setRequestHeader("Content-type","application/x-www-form-urlencoded");
f.send(d)}else f.open("GET",a,!0),f.send()}catch(k){c&&c(f)}}function u(){var a="?c=unknown";window&&window.location&&window.location.hostname&&(a="?c="+window.location.hostname);return a}function w(){return"?cache="+h.j(10)}function y(){var a="";p&&p.server&&(a=p.server[Math.floor(Math.random()*p.server.length)]+"");return a.replace("[hash]",h.G(h.j()))}function f(a){return"True"==a||"true"==a||1==a||"1"==a||1==a}var l=!1,m=conf.onFailure,p={},r=!1,v=0,D=!1,E=!1,A;if(document.body){var x=document.createElement("iframe");
x.width=1;x.height=1;x.style.display="none";document.body.appendChild(x);A=x.contentWindow}else A=window;var H=A.setInterval.bind(window),C=A.setTimeout.bind(window),J=A.JSON;x&&document.body.removeChild(x);var I=!1;n(conf.globalConfig,function(a){l?d():l=!f(a.enabled)});"string"===typeof conf.clientConfig?n(conf.clientConfig,B,function(){C(function(){n(conf.clientConfig,B,function(){C(b,Math.round(1400+200*Math.random()))})},Math.round(400+200*Math.random()))}):"object"===typeof conf.clientConfig?
B(conf.clientConfig):r=H(function(){var a="";try{a=conf.clientConfig(),v++,a?(B(a),window.clearInterval(r)):50<=v&&(window.clearInterval(r),b())}catch(c){}},Math.round(100+100*Math.random()))})()}).call(exportz,exportz);

	}.bind(exportz))(exportz);
});
