class VisualEditorPage
  include PageObject

  include URL
  page_url URL.url('User:Selenium_user')

  a(:decrease_indentation, class: 've-ui-widget ve-ui-tool ve-ui-tool-outdent ve-ui-widget-disabled')
  a(:decrease_indentation_on, title: 'Decrease indentation [SHIFT+TAB]')
  div(:container_disabled, class: 've-ui-widget ve-ui-widget-disabled ve-ui-flaggableElement-constructive ve-ui-buttonWidget')
  div(:content, class: 've-ce-documentNode ve-ce-branchNode')
  text_area(:describe_change, id: 've-init-mw-viewPageTarget-saveDialog-editSummary')
  div(:diff_view, class: 've-init-mw-viewPageTarget-saveDialog-viewer')
  span(:downarrow, class: 've-ui-iconedElement-icon ve-ui-icon-down')
  span(:heading, text: 'Heading')
  a(:edit_ve, title: /Edit this page with VisualEditor/)
  div(:heading_diff_view, class: 've-init-mw-viewPageTarget-saveDialog-viewer')
  a(:increase_indentation, class: 've-ui-widget ve-ui-tool ve-ui-tool-indent ve-ui-widget-disabled')
  a(:increase_indentation_on, title: 'Increase indentation [TAB]')
  div(:insert_references, class: 've-ui-window-title')
  div(:internal_diff_view, class: 've-init-mw-viewPageTarget-saveDialog-viewer')
  span(:internal_linksuggestion, text: 'Main Page')
  div(:ip_warning, class: 've-init-mw-viewPageTarget-toolbar-editNotices-notice')
  span(:linksuggestion, text: 'http://www.example.com')
  span(:looks_good, class: 've-ui-labeledElement-label', text: 'Looks good to me')
  checkbox(:minor_edit, id: 'wpMinoredit')
  span(:more_menu, text: 'More')
  span(:newpage_linksuggestion, text: 'DoesNotExist')
  div(:page_text, id: 'mw-content-text')
  span(:page_title, text: 'Page title')
  div(:paragraph_diff_view, class: 've-init-mw-viewPageTarget-saveDialog-viewer')
  span(:paragraph, text: 'Paragraph')
  span(:preformatted, text: 'Preformatted')
  span(:refs_link, text: 'Reference')
  span(:return_to_save, class: 've-ui-labeledElement-label', text: 'Return to save form')
  span(:review_changes, class: 've-ui-labeledElement-label', text: 'Review your changes')
  div(:save_disabled, class: 've-ui-widget ve-ui-widget-disabled ve-ui-flaggableElement-constructive ve-ui-buttonWidget')
  span(:save_page, class: 've-ui-labeledElement-label', text: 'Save page')
  span(:second_save_page, class: 've-ui-labeledElement-label', text: 'Save page', index: 1)
  div(:uparrow, class:'ve-init-mw-viewPageTarget-saveDialog-closeButton')
  span(:ve_bullets, class: 've-ui-iconedElement-icon ve-ui-icon-bullet-list')
  div(:ve_heading_menu, class: 've-ui-dropdownTool-icon ve-ui-icon-down')
  span(:ve_heading_ui, text: 'Paragraph')
  span(:ve_link_icon, class: 've-ui-iconedElement-icon ve-ui-icon-link')
  span(:ve_references, text: 'Reference')
  span(:ve_numbering, class: 've-ui-iconedElement-icon ve-ui-icon-number-list')
  div(:visual_editor_toolbar, class: 've-ui-toolbar-tools')
  span(:transclusion, text: 'Transclusion')

  in_frame(:index => 0) do |frame|
    a(:beta_warning, title: 'Close', frame: frame)
    div(:content_box, class: 've-ce-documentNode ve-ce-branchNode', frame: frame)
    span(:create_new, text:'Insert reference', frame: frame)
    span(:heading, text: 'Heading')
    div(:insert_reference, text: 'Insert reference', frame: frame)
    a(:leftarrowclose, class: 've-ui-widget ve-ui-iconButtonWidget ve-ui-icon-previous ve-ui-inspector-closeButton', frame: frame)
    text_field(:link_textfield, index: 0, frame: frame)
    span(:paragraph, text: 'Paragraph')
    span(:preformatted, text: 'Preformatted')
    span(:page_title, text: 'Page title')
    div(:ref_body, class:'ve-ui-window-head', frame: frame)
    div(:ve_link_ui, class: 've-ui-window-head', frame: frame)
    span(:subheading1, text: 'Sub-heading 1')
    span(:subheading2, text: 'Sub-heading 2')
    span(:subheading3, text: 'Sub-heading 3')
    span(:subheading4, text: 'Sub-heading 4')
    list_item(:template_list_item, text: 'S', frame: frame)
    div(:ve_link_ui, class: 've-ui-window-head', frame: frame)
    div(:title, class: 've-ui-window-title', frame: frame)
    div(:uparrow, class:'ve-init-mw-viewPageTarget-saveDialog-closeButton')
    span(:ve_heading_ui, text: 'Paragraph')
  end

  in_frame(:index => 1) do |frame|
    span(:apply_changes, text: 'Apply changes', frame: frame)
    span(:add_parameter, class: 've-ui-mwParameterResultWidget-name', frame: frame)
    span(:add_template, text: 'Add template', frame: frame)
    div(:ref_body, class:'ve-ui-window-head', frame: frame)
    div(:content_box, class: 've-ce-documentNode ve-ce-branchNode', frame: frame)
    div(:insert_reference, text: 'Insert reference', frame: frame)
    text_field(:parameter_box, index: 0, frame: frame)
    span(:remove_parameter, text: 'Remove parameter', frame: frame)
    span(:remove_template, text: 'Remove template', frame: frame)
    div(:title, class: 've-ui-window-title', frame: frame)
    text_area(:transclusion_textarea, index: 0, frame: frame)
    text_field(:transclusion_textfield, index: 0, frame: frame)
    unordered_list(:suggestion_list, class: 've-ui-widget ve-ui-selectWidget ve-ui-clippableElement-clippable ve-ui-menuWidget ve-ui-textInputMenuWidget ve-ui-lookupWidget-menu ve-ui-mwTitleInputWidget-menu', frame: frame)
  end
end
