<?php
if ( !defined( 'MEDIAWIKI' ) ) die();
/**
 * @file
 * @ingroup Extensions
 */

/**
 * Array mapping all editable settings to their type depending of their section
 * First two keys will be used to show sections
 * These settings are more or less in the same order as
 * http://www.mediawiki.org/wiki/Manual:Configuration_settings
 */
$settings = array(
	'site' => array(
		'site' => array(
			'wgSitename' => 'text',
			'wgLogo' => 'image-url',
			'wgSiteNotice' => 'text',
			'wgExtraSubtitle' => 'text',
			'wgBreakFrames' => 'bool',
			'wgSiteSupportPage' => 'text',
			'wgStyleVersion' => 'int',
		),
	),
	'features' => array(
		'features' => array(
			'wgUseExternalEditor' => 'bool',
			'wgUniversalEditButton' => 'bool',
			'wgPageShowWatchingUsers' => 'bool',
			'wgEdititis' => 'bool',
			'wgShowHostnames' => 'bool',
			'wgFixDoubleRedirects' => 'bool',
			'wgEnableAPI' => 'bool',
			'wgEnableWriteAPI' => 'bool',
			'wgUseTeX' => 'bool',
			'wgEnableHtmlDiff' => 'bool',
			'wgUseAutomaticEditSummaries' => 'bool',
			'wgUseTagFilter' => 'bool',
			'wgUseTrackbacks' => 'bool',
			'wgUseMetadataEdit' => 'bool',
			'wgMetadataWhitelist' => 'text',
		),
		'ajax' => array(
			'wgUseAjax' => 'bool',
			'wgAjaxExportList' => 'array',
			'wgAjaxUploadDestCheck' => 'bool',
			'wgAjaxWatch' => 'bool',
			'wgLivePreview' => 'bool',
		),
		'css-js' => array(
			'wgAllowUserCss' => 'bool',
			'wgAllowUserJs' => 'bool',
			'wgUseSiteCss' => 'bool',
			'wgUseSiteJs' => 'bool',
			'wgHandheldStyle' => 'text',
			'wgHandheldForIPhone' => 'bool',
		),
		'performance' => array(
			'wgAPIMaxDBRows' => 'int',
			'wgAPIMaxResultSize' => 'int',
			'wgAPIMaxUncachedDiffs' => 'int',
			'wgDisableQueryPages' => 'bool',
			'wgDisableQueryPageUpdate' => 'array',
			'wgDisableSearchContext' => 'bool',
			'wgDisableSearchUpdate' => 'bool',
			'wgDisableTextSearch' => 'bool',
			'wgMaximumMovedPages' => 'int',
			'wgMiserMode' => 'bool',
			'wgCompressRevisions' => 'bool',
			'wgUpdateRowsPerQuery' => 'int',
		),
	),
	'pages' => array(
		'pages' => array(
			'wgCapitalLinks' => 'bool',
			'wgMaxArticleSize' => 'int',
			'wgMaxRedirects' => 'int',
			'wgInvalidRedirectTargets' => 'array',
			'wgLegalTitleChars' => 'text',
		),
		'robots' => array(
			'wgArticleRobotPolicies' => 'array',
			'wgDefaultRobotPolicy' => 'text',
			'wgExemptFromUserRobotsControl' => 'array',
			'wgNoFollowLinks' => 'bool',
			'wgNoFollowDomainExceptions' => 'array',
		),
	),
	'namespaces' => array(
		'namespaces' => array(
			'wgContentNamespaces' => 'array',
			'wgExtraNamespaces' => 'array',
			'wgMetaNamespace' => 'text',
			'wgMetaNamespaceTalk' => 'text',
			'wgNamespaceAliases' => 'array',
			'wgNamespaceProtection' => 'array',
			'wgNamespaceRobotPolicies' => 'array',
			'wgNamespacesToBeSearchedDefault' => 'array',
			'wgNamespacesToBeSearchedProject' => 'array',
			'wgNamespacesWithSubpages' => 'array',
			'wgNoFollowNsExceptions' => 'array',
			'wgNonincludableNamespaces' => 'array',
			'wgSitemapNamespaces' => 'array',
		),
	),
	'groups' => array(
		'groups' => array(
			'wgAutopromote' => 'array',
			'wgImplicitGroups' => 'array',
			'wgGroupPermissions' => 'array',
			'wgAddGroups' => 'array',
			'wgRemoveGroups' => 'array',
			'wgGroupsAddToSelf' => 'array',
			'wgGroupsRemoveFromSelf' => 'array',
		),
	),
	'paths' => array(
		'paths' => array(
			'wgActionPaths' => 'array',
			'wgAppleTouchIcon' => 'text',
			'wgArticlePath' => 'text',
			'wgFavicon' => 'text',
			'wgMathDirectory' => 'text',
			'wgMathPath' => 'text',
			'wgRedirectScript' => 'text',
			'wgProto' => 'text',
			'wgScript' => 'text',
			'wgScriptExtension' => 'text',
			'wgScriptPath' => 'text',
			'wgServer' => 'text',
			'wgServerName' => 'text',
			'wgStyleDirectory' => 'text',
			'wgStylePath' => 'text',
			'wgStyleSheetPath' => 'text',
			'wgTmpDirectory' => 'text',
			'wgUploadBaseUrl' => 'text',
			'wgUploadDirectory' => 'text',
			'wgUploadNavigationUrl' => 'text',
			'wgUploadPath' => 'text',
			'wgUsePathInfo' => 'bool',
			'wgVariantArticlePath' => 'text',
		),
		'external-tools' => array(
			'wgDiff' => 'text',
			'wgDiff3' => 'text',
			'wgPhpCli' => 'text',
			'wgTexvc' => 'text',
			'wgExternalDiffEngine' => 'text',
		),
		'filesystem' => array(
			'wgDirectoryMode' => 'int',
			'wgSQLiteDataDirMode' => 'int',
			'wgMaxShellFileSize' => 'int',
			'wgMaxShellMemory' => 'int',
			'wgMaxShellTime' => 'int',
			'wgShellLocale' => 'text',
		),
	),
	'db' => array(
		'db' => array(
			'wgAllDBsAreLocalhost' => 'bool',
			'wgCheckDBSchema' => 'bool',
			'wgDBAvgStatusPoll' => 'int',
#			'wgDBconnection' => 'text', # This setting is deprecated and has an uncertain history. Best not to let people change it.
			'wgDBerrorLog' => 'text',
			'wgDBname' => 'text',
			'wgDBpassword' => 'text',
			'wgDBport' => 'int',
			'wgDBserver' => 'text',
			'wgDBtype' => array( 'mysql' => 'MySQL', 'postgres' => 'PostreSQL' ),
			'wgDBuser' => 'text',
#			'wgLegacySchemaConversion' => 'bool', # Really, really deprecated.
			'wgLocalDatabases' => 'array',
			'wgSearchType' => 'text',
			'wgSharedDB' => 'text',
			'wgSharedPrefix' => 'text',
			'wgSharedTables'  => 'array',
			'wgAntiLockFlags' => 'int',
			'wgUseDumbLinkUpdate' => 'bool',
		),
		'load-balancing' => array(
			'wgDBClusterTimeout' => 'int',
			'wgDBservers' => 'array',
			'wgDefaultExternalStore' => 'array',
			'wgExternalServers' => 'array',
			'wgLBFactoryConf' => 'array',
			'wgMasterWaitTimeout' => 'int',
			'wgSlaveLagCritical' => 'int',
			'wgSlaveLagWarning' => 'int',
		),
		'mysql' => array(
			'wgDBmysql4' => 'bool',
			'wgDBmysql5' => 'bool',
			'wgDBprefix' => 'text',
			'wgDBTableOptions' => 'text',
			'wgDBtransactions' => 'bool',
		),
		'postgres' => array(
			'wgDBmwschema' => 'text',
			'wgDBts2schema' => 'text',
		),
		'sqlite' => array(
			'wgSQLiteDataDir' => 'text',
		),
	),
	'email' => array(
		'email' => array(
			'wgEmailAuthentication' => 'bool',
			'wgEmergencyContact' => 'text',
			'wgEnableEmail' => 'bool',
			'wgEnableUserEmail' => 'bool',
			'wgNoReplyAddress' => 'text',
			'wgPasswordSender' => 'text',
			'wgPasswordReminderResendTime' => 'int',
			'wgSMTP' => 'array',
			'wgUserEmailUseReplyTo' => 'bool',
		),
		'enotif' => array(
			'wgEnotifFromEditor' => 'bool',
			'wgEnotifImpersonal' => 'bool',
			'wgEnotifMaxRecips' => 'int',
			'wgEnotifMinorEdits' => 'bool',
			'wgEnotifRevealEditorAddress' => 'bool',
			'wgEnotifUseJobQ' => 'bool',
			'wgEnotifUseRealName' => 'bool',
			'wgEnotifUserTalk' => 'bool',
			'wgEnotifWatchlist' => 'bool',
			'wgUsersNotifiedOnAllChanges' => 'array',
		),
	),
	'localization' => array(
		'localization' => array(
			'wgLanguageCode' => 'lang',
			'wgDefaultLanguageVariant' => 'text',
			'wgExtraLanguageNames' => 'array',
			'wgDisableLangConversion' => 'bool',
			'wgDisableTitleConversion' => 'bool',
			'wgUseDatabaseMessages' => 'bool',
			'wgForceUIMsgAsContentMsg' => 'array',
			'wgLoginLanguageSelector' => 'bool',
			'wgInputEncoding' => 'text',
			'wgLegacyEncoding' => 'text',
			'wgEditEncoding' => 'text',
			'wgOutputEncoding' => 'text',
			'wgTranslateNumerals' => 'bool',
			'wgUseDynamicDates' => 'bool',
			'wgAmericanDates' => 'bool',
		),
		'timezone' => array(
			'wgLocaltimezone' => 'text',
			'wgLocalTZoffset' => 'int',
		),
		'zh-conversion' => array(
			'wgUseZhdaemon' => 'bool',
			'wgZhdaemonHost' => 'text',
			'wgZhdaemonPort' => 'int',
		),
	),
	'output' => array(
		'output' => array(
			'wgDocType' => 'text',
			'wgDTD' => 'text',
			'wgMimeType' => 'text',
			'wgXhtmlDefaultNamespace' => 'text',
			'wgXhtmlNamespaces' => 'array',
			'wgDisableOutputCompression' => 'bool',
		),
	),
	'debug' => array(
		'debug' => array(
			'wgColorErrors' => 'bool',
			'wgDebugComments' => 'bool',
			'wgDebugDumpSql' => 'bool',
			'wgDebugLogFile' => 'text',
			'wgDebugLogGroups' => 'array',
			'wgDebugRawPage' => 'bool',
			'wgDebugLogPrefix' => 'text',
			'wgDebugRedirects' => 'bool',
			'wgLogQueries' => 'bool',
			'wgShowDebug' => 'bool',
			'wgShowExceptionDetails' => 'bool',
			'wgShowSQLErrors' => 'bool',
			'wgStatsMethod' => array( 'cache' => 'Cache', 'udp' => 'UDP', 0 => 'None' ),
		),
		'profiling' => array(
			'wgDebugFunctionEntry' => 'bool',
			'wgDebugProfiling' => 'bool',
			'wgDebugSquid' => 'bool',
			'wgProfileCallTree' => 'bool',
			'wgProfileLimit' => 'int',
			'wgProfileOnly' => 'bool',
			'wgProfilePerHost' => 'bool',
			'wgProfileToDatabase' => 'bool',
			'wgUDPProfilerHost' => 'text',
			'wgUDPProfilerPort' => 'int',
		),
	),
	'stats' => array(
		'stats' => array(
			'wgCountCategorizedImagesAsUsed' => 'bool',
			'wgDisableCounters' => 'bool',
			'wgHitcounterUpdateFreq' => 'int',
			'wgUseCommaCount' => 'bool',
			'wgWantedPagesThreshold' => 'int',
		),
	),
	'skin' => array(
		'skin' => array(
			'wgDefaultSkin' => 'text',
			'wgSkipSkin' => 'text',
			'wgSkipSkins' => 'array',
		),
	),
	'category' => array(
		'category' => array(
			'wgCategoryMagicGallery' => 'bool',
			'wgCategoryPagingLimit' => 'int',
			'wgCategoryPrefixedDefaultSortkey' => 'bool',
			'wgUseCategoryBrowser' => 'bool',
		),
	),
	'cache' => array(
		'cache' => array(
			'wgMainCacheType' => array( -1 => 'Anything', 0 => 'None',
	                            1 => 'DB', 2 => 'Memcached',
	                            3 => 'Accel', 4 => 'DBA' ),
	        'wgCacheEpoch' => 'text',
			'wgCachePages' => 'bool',
			'wgClockSkewFudge' => 'int',
			'wgFileCacheDirectory' => 'text',
			'wgForcedRawSMaxage' => 'int',
			'wgQueryCacheLimit' => 'int',
			'wgRevisionCacheExpiry' => 'int',
			'wgTranscludeCacheExpiry' => 'int',
			'wgUseFileCache' => 'bool',
			'wgUseGzip' => 'bool',
		),
		'pcache' => array(
			'wgParserCacheType' => array( -1 => 'Anything', 0 => 'None',
			                              1 => 'DB', 2 => 'Memcached',
			                              3 => 'Accel', 4 => 'DBA' ),
			'wgEnableParserCache' => 'bool',
			'wgEnableSidebarCache' => 'bool',
			'wgRenderHashAppend' => 'text',
			'wgSidebarCacheExpiry' => 'int',
			'wgUseETag' => 'bool',
		),
		'messagecache' => array(
			'wgMessageCacheType' => array( -1 => 'Anything', 0 => 'None',
			                               1 => 'DB', 2 => 'Memcached',
			                               3 => 'Accel', 4 => 'DBA' ),
			'wgEnableSerializedMessages' => 'bool',
			'wgLocalMessageCache' => 'text',
			'wgMsgCacheExpiry' => 'int',
			'wgCheckSerialized' => 'bool',
			'wgLocalMessageCacheSerialized' => 'bool',
			'wgMaxMsgCacheEntrySize' => 'int',
		),
		'memcached' => array(
#			'wgMemCachedDebug' => 'bool', # Does not appear to be a setting, just a global
			'wgMemCachedPersistent' => 'bool',
			'wgMemCachedServers' => 'array',
			'wgSessionsInMemcached' => 'bool',
			'wgUseMemCached' => 'bool',
		),
	),
	'interwiki' => array(
		'interwiki' => array(
			'wgImportSources' => 'array',
			'wgLocalInterwiki' => 'text',
			'wgHideInterlanguageLinks' => 'bool',
			'wgInterwikiMagic' => 'bool',
			'wgEnableScaryTranscluding' => 'bool',
			'wgDisableHardRedirects' => 'bool',
			'wgRedirectSources' => 'text',
			'wgInterwikiCache' => 'text',
			'wgInterwikiExpiry' => 'int',
			'wgInterwikiFallbackSite' => 'text',
			'wgInterwikiScopes' => 'int',
		),
	),
	'access' => array(
		'access' => array(
			'wgAccountCreationThrottle' => 'int',
			'wgAllowPageInfo' => 'bool',
			'wgDisabledActions' => 'array',
			'wgNewPasswordExpiry' => 'int',
			'wgEmailConfirmToEdit' => 'bool',
			'wgPasswordSalt' => 'bool',
			'wgReadOnly' => 'text',
			'wgReadOnlyFile' => 'text',
			'wgRestrictionTypes' => 'array',
			'wgRestrictionLevels' => 'array',
			'wgWhitelistRead' => 'array',
		),
		'block' => array(
			'wgBlockAllowsUTEdit' => 'bool',
			'wgSysopEmailBans' => 'bool',
			'wgSysopRangeBans' => 'bool',
			'wgSysopUserBans' => 'bool',
			'wgAutoblockExpiry' => 'int',
		),
		'filter' => array(
			'wgSpamRegex' => 'array',
			'wgSummarySpamRegex' => 'array',
			'wgFilterCallback' => 'text',
			'wgDeleteRevisionsLimit' => 'int',
			'wgPasswordAttemptThrottle' => 'array',
		),
		'rates' => array(
			'wgRateLimitLog' => 'text',
			'wgRateLimits' => 'array',
			'wgRateLimitsExcludedGroups' => 'array',
		),
	),
	'upload' => array(
		'upload' => array(
			'wgAjaxLicensePreview' => 'bool',
			'wgAllowCopyUploads' => 'bool',
			'wgCheckFileExtensions' => 'bool',
			'wgEnableUploads' => 'bool',
			'wgFileBlacklist' => 'array',
			'wgFileExtensions' => 'array',
			'wgFileStore' => 'array',
			'wgHashedUploadDirectory' => 'bool',
			'wgLocalFileRepo' => 'array',
			'wgRemoteUploads' => 'bool',
			'wgStrictFileExtensions' => 'bool',
			'wgUploadSizeWarning' => 'int',
			'wgMaxUploadSize' => 'int',
			'wgHTTPTimeout' => 'int',
			'wgHTTPProxy' => 'text',
		),
		'sharedupload' => array(
			'wgCacheSharedUploads' => 'bool',
			'wgForeignFileRepos' => 'array',
			'wgFetchCommonsDescriptions' => 'bool',
			'wgHashedSharedUploadDirectory' => 'bool',
			'wgRepositoryBaseUrl' => 'text',
			'wgSharedThumbnailScriptPath' => 'text',
			'wgSharedUploadDBname' => 'text',
			'wgSharedUploadDBprefix' => 'text',
			'wgSharedUploadDirectory' => 'text',
			'wgSharedUploadPath' => 'text',
			'wgUseSharedUploads' => 'bool',
		),
		'mime' => array(
			'wgVerifyMimeType' => 'bool',
			'wgLoadFileinfoExtension' => 'bool',
			'wgMimeDetectorCommand' => 'text',
			'wgMimeInfoFile' => 'text',
			'wgMimeTypeFile' => 'text',
			'wgTrivialMimeDetection' => 'bool',
			'wgJsMimeType' => 'text',
			'wgMimeTypeBlacklist' => 'array',
			'wgXMLMimeTypes' => 'array',
		),
	),
	'images' => array(
		'images' => array(
			'wgAllowImageMoving' => 'bool',
			'wgCustomConvertCommand' => 'text',
			'wgIgnoreImageErrors' => 'bool',
			'wgImageLimits' => 'array',
			'wgMaxAnimatedGifArea' => 'int',
			'wgMaxImageArea' => 'int',
			'wgMediaHandlers' => 'array',
			'wgShowEXIF' => 'bool',
			'wgTrustedMediaFormats' => 'array',
		),
		'thumbnail' => array(
			'wgTiffThumbnailType' => 'array',
			'wgThumbnailEpoch' => 'text',
			'wgThumbnailScriptPath' => 'text',
			'wgThumbUpright' => 'text',
			'wgGenerateThumbnailOnParse' => 'bool',
			'wgThumbLimits' => 'array',
		),
		'djvu' => array(
			'wgDjvuDump' => 'text',
			'wgDjvuOutputExtension' => 'text',
			'wgDjvuPostProcessor' => 'text',
			'wgDjvuRenderer' => 'text',
			'wgDjvuToXML' => 'text',
		),
		'imagemagick' => array(
			'wgImageMagickConvertCommand' => 'text',
			'wgImageMagickTempDir' => 'text',
			'wgSharpenParameter' => 'int',
			'wgSharpenReductionThreshold' => 'text',
			'wgUseImageMagick' => 'bool',
		),
		'svg' => array(
			'wgAllowTitlesInSVG' => 'bool',
			'wgSVGConverter' => 'text',
			'wgSVGConverterPath' => 'text',
			'wgSVGConverters' => 'array',
			'wgSVGMaxSize' => 'int',
		),
		'antivirus' => array(
			'wgAntivirus' => 'text',
			'wgAntivirusRequired' => 'bool',
			'wgAntivirusSetup' => 'array',
		),
	),
	'parser' => array(
		'parser' => array(
			'wgAllowDisplayTitle' => 'bool',
			'wgRestrictDisplayTitle' => 'bool',
			'wgAllowExternalImages' => 'bool',
			'wgAllowExternalImagesFrom' => 'text',
			'wgEnableImageWhitelist' => 'bool',
			'wgExpensiveParserFunctionLimit' => 'int',
			'wgExternalLinkTarget' => 'text',
			'wgCleanSignatures' => 'bool',
			'wgGrammarForms' => 'array',
			'wgLinkHolderBatchSize' => 'int',
			'wgMaxPPExpandDepth' => 'int',
			'wgMaxPPNodeCount' => 'int',
			'wgMaxTemplateDepth' => 'int',
			'wgMaxTocLevel' => 'int',
			'wgParserConf' => 'array',
			'wgParserCacheExpireTime' => 'int',
			'wgParserTestFiles' => 'array',
			'wgPreprocessorCacheThreshold' => 'int',
			'wgUrlProtocols' => 'array',
		),
		'html' => array(
			'wgRawHtml' => 'bool',
		),
		'tidy' => array(
			'wgAlwaysUseTidy' => 'bool',
			'wgDebugTidy' => 'bool',
			'wgTidyBin' => 'text',
			'wgTidyConf' => 'text',
			'wgTidyInternal' => 'bool',
			'wgTidyOpts' => 'text',
			'wgUseTidy' => 'bool',
			'wgValidateAllHtml' => 'bool',
		),
	),
	'specialpages' => array(
		'specialpages' => array(
			'wgAllowSpecialInclusion' => 'bool',
			'wgExportAllowHistory' => 'bool',
			'wgExportAllowListContributors' => 'bool',
			'wgExportFromNamespaces' => 'bool',
			'wgExportMaxHistory' => 'int',
			'wgExportMaxLinkDepth' => 'int',
			'wgExtraRandompageSQL' => 'text',
			'wgFilterLogTypes' => 'array',
			'wgImportTargetNamespace' => 'text',
			'wgLogActions' => 'array',
			'wgLogActionsHandlers' => 'array',
			'wgLogHeaders' => 'array',
			'wgLogNames' => 'array',
			'wgLogRestrictions' => 'array',
			'wgLogTypes' => 'array',
			'wgMaxRedirectLinksRetrieved' => 'int',
			'wgSortSpecialPages' => 'bool',
			'wgSpecialPageGroups' => 'array',
			'wgSpecialVersionShowHooks' => 'bool',
			'wgUseNPPatrol' => 'bool',
		),
		'recentchanges' => array(
			'wgAllowCategorizedRecentChanges' => 'bool',
			'wgPutIPinRC' => 'bool',
			'wgRCChangedSizeThreshold' => 'int',
			'wgRCFilterByAge' => 'bool',
			'wgRCLinkLimits' => 'array',
			'wgRCLinkDays' => 'array',
			'wgRCMaxAge' => 'int',
			'wgRCShowChangedSize' => 'bool',
			'wgRCShowWatchingUsers' => 'bool',
			'wgShowUpdatedMarker' => 'bool',
			'wgUseRCPatrol' => 'bool',
			'wgRC2UDPAddress' => 'text',
			'wgRC2UDPInterwikiPrefix' => 'bool',
			'wgRC2UDPOmitBots' => 'bool',
			'wgRC2UDPPort' => 'int',
			'wgRC2UDPPrefix' => 'text',
		),
	),
	'users' => array(
		'users' => array(
			'wgActiveUserDays' => 'int',
			'wgActiveUserEditCount' => 'int',
			'wgAutoConfirmAge' => 'int',
			'wgAutoConfirmCount' => 'int',
			'wgAllowRealName' => 'bool',
			'wgAllowUserSkin' => 'bool',
			'wgDefaultUserOptions' => 'array',
			'wgDisableAnonTalk' => 'bool',
			'wgMaxNameChars' => 'int',
			'wgMaxSigChars' => 'int',
			'wgMinimalPasswordLength' => 'int',
			'wgNewUserLog' => 'bool',
			'wgReservedUsernames' => 'array',
			'wgShowIPinHeader' => 'bool',
			'wgBrowserBlackList' => 'array',
		),
	),
	'cookie' => array(
		'cookie' => array(
			'wgCacheVaryCookies' => 'array',
			'wgCookieDomain' => 'text',
			'wgCookieExpiration' => 'int',
			'wgCookieHttpOnly' => 'bool',
			'wgCookiePath' => 'text',
			'wgCookiePrefix' => 'text',
			'wgCookieSecure' => 'bool',
			'wgDisableCookieCheck' => 'bool',
			'wgHttpOnlyBlacklist' => 'array',
			'wgSessionName' => 'text',
		),
	),
	'feed' => array(
		'feed' => array(
			'wgFeed' => 'bool',
			'wgFeedCacheTimeout' => 'int',
			'wgFeedDiffCutoff' => 'int',
			'wgFeedLimit' => 'int',
			'wgOverrideSiteFeed' => 'array',
		),
	),
	'copyright' => array(
		'copyright' => array(
			'wgCheckCopyrightUpload' => 'bool',
			'wgCopyrightIcon' => 'text',
			'wgEnableCreativeCommonsRdf' => 'bool',
			'wgEnableDublinCoreRdf' => 'bool',
			'wgMaxCredits' => 'int',
			'wgRightsIcon' => 'text',
			'wgRightsPage' => 'text',
			'wgRightsText' => 'text',
			'wgRightsUrl' => 'text',
			'wgShowCreditsIfMax' => 'bool',
			'wgUseCopyrightUpload' => 'bool',
		),
	),
	'search' => array(
		'search' => array(
			'wgAdvancedSearchHighlighting' => 'bool',
			'wgEnableMWSuggest' => 'bool',
			'wgGoToEdit' => 'bool',
			'wgMWSuggestTemplate' => 'text',
			'wgOpenSearchTemplate' => 'text',
			'wgSearchForwardUrl' => 'text',
			'wgSearchHighlightBoundaries' => 'text',
			'wgUseTwoButtonsSearchForm' => 'bool',
		),
	),
	'proxy' => array(
		'proxy' => array(
			'wgBlockOpenProxies' => 'bool',
			'wgEnableSorbs' => 'bool',
#			'wgProxyKey' => 'text', # Deprecated
			'wgProxyList' => 'array',
			'wgProxyMemcExpiry' => 'int',
			'wgProxyPorts' => 'array',
			'wgProxyScriptPath' => 'text',
			'wgProxyWhitelist' => 'array',
			'wgSecretKey' => 'text',
			'wgSorbsUrl' => 'text',
		),
	),
	'squid' => array(
		'squid' => array(
			'wgUseSquid' => 'bool',
			'wgInternalServer' => 'text',
			'wgMaxSquidPurgeTitles' => 'int',
			'wgSquidMaxage' => 'int',
			'wgSquidServers' => 'array',
			'wgSquidServersNoPurge' => 'array',
			'wgUseESI' => 'bool',
			'wgUsePrivateIPs' => 'bool',
		),
		'htcp' => array(
			'wgHTCPMulticastAddress' => 'text',
			'wgHTCPMulticastTTL' => 'int',
			'wgHTCPPort' => 'int',
		),
	),
	'job' => array(
		'job' => array(
			'wgJobRunRate' => 'int',
			'wgJobClasses' => 'array',
			'wgUpdateRowsPerJob' => 'int',
		),
	),
	'extension' => array(
		'extension' => array(
			'wgAllowSlowParserFunctions' => 'bool',
			'wgAPIListModules' => 'array',
			'wgAPIMetaModules' => 'array',
			'wgAPIModules' => 'array',
			'wgAPIPropModules' => 'array',
			'wgAutoloadClasses' => 'array',
			'wgAvailableRights' => 'array',
			'wgDisableInternalSearch' => 'bool',
			'wgExceptionHooks' => 'array',
			'wgExtensionAliasesFiles' => 'array',
			'wgExtensionCredits' => 'array',
			'wgExtensionFunctions' => 'array',
			'wgExtensionMessagesFiles' => 'array',
			'wgExternalStores' => 'array',
			'wgHooks' => 'array',
			'wgPagePropLinkInvalidations' => 'array',
			'wgParserOutputHooks' => 'array',
			'wgSpecialPageCacheUpdates' => 'array',
			'wgSpecialPages' => 'array',
			'wgSkinExtensionFunctions' => 'array',
		),
	),
);

/**
 * As there can be a lot of array types, try to define their type
 *
 * Types used:
 * - simple: single dimension array with numeric key
 * - assoc:  single dimension array with associative key => val
 * - ns-bool:   single dimension array with namespaces numbers in the key and a
 *              boolean value
 * - ns-text:   same as ns-bool but with a string in the value
 * - ns-simple: like simple, but values are restricted to namespaces index
 * - group-bool: two dimensions array with group name in first key, right name
 *               in the second and boolean value
 * - group-array: two dimensions array with group name in first key and then
 *                a 'simple' array
 * - array: other types of arrays not currenty supported
 */
$arrayDefs = array(
# Features
	'wgAjaxExportList' => 'simple',
	'wgDisableQueryPageUpdate' => 'simple',
# Pages
	'wgInvalidRedirectTargets' => 'simple',
	'wgArticleRobotPolicies' => 'assoc',
	'wgExemptFromUserRobotsControl' => 'ns-simple',
	'wgNoFollowDomainExceptions' => 'simple',
# Namespaces
	'wgContentNamespaces' => 'ns-simple',
	'wgExtraNamespaces' => 'assoc',
	'wgNamespaceAliases' => 'assoc',
	'wgNamespaceProtection' => 'ns-array',
	'wgNamespaceRobotPolicies' => 'ns-text',
	'wgNamespacesToBeSearchedDefault' => 'ns-bool',
	'wgNamespacesToBeSearchedProject' => 'ns-bool',
	'wgNamespacesWithSubpages' => 'ns-bool',
	'wgNoFollowNsExceptions' => 'ns-simple',
	'wgNonincludableNamespaces' => 'ns-simple',
	'wgSitemapNamespaces' => 'ns-simple',
# Groups
	'wgAutopromote' => 'promotion-conds',
	'wgImplicitGroups' => 'simple',
	'wgGroupPermissions' => 'group-bool',
	'wgAddGroups' => 'group-array',
	'wgRemoveGroups' => 'group-array',
	'wgGroupsAddToSelf' => 'group-array',
	'wgGroupsRemoveFromSelf' => 'group-array',
# Paths
	'wgActionPaths' => 'assoc',
# Db
	'wgLocalDatabases' => 'simple',
	'wgSharedTables'  => 'simple',
	'wgDBservers' => 'array',
	'wgDefaultExternalStore' => 'simple',
	'wgLBFactoryConf' => 'array',
	'wgExternalServers' => 'array',
# Email
	'wgSMTP' => 'assoc',
	'wgUsersNotifiedOnAllChanges' => 'simple',
# Localization
	'wgExtraLanguageNames' => 'assoc',
	'wgForceUIMsgAsContentMsg' => 'simple',
# Output
	'wgXhtmlNamespaces' => 'assoc',
# Debug
	'wgDebugLogGroups' => 'assoc',
# Skins
	'wgSkipSkins' => 'simple',
# Cache
	'wgMemCachedServers' => 'simple',
# Interwiki
	'wgImportSources' => 'simple',
# Access
	'wgDisabledActions' => 'simple',
	'wgRestrictionLevels' => 'simple',
	'wgRestrictionTypes' => 'simple',
	'wgWhitelistRead' => 'simple',
	'wgSpamRegex' => 'simple',
	'wgSummarySpamRegex' => 'simple',
	'wgRateLimits' => 'rate-limits',
	'wgRateLimitsExcludedGroups' => 'simple',
	'wgPasswordAttemptThrottle' => 'assoc',
# Uploads
	'wgFileBlacklist' => 'simple',
	'wgFileExtensions' => 'simple',
	'wgFileStore' => 'array',
	'wgLocalFileRepo' => 'assoc',
	'wgForeignFileRepos' => 'array',
	'wgMimeTypeBlacklist' => 'simple',
	'wgXMLMimeTypes' => 'assoc',
# Images
	'wgImageLimits' => 'simple-dual',
	'wgMediaHandlers' => 'assoc',
	'wgTrustedMediaFormats' => 'simple',
	'wgTiffThumbnailType' => 'simple',
	'wgThumbLimits' => 'simple',
	'wgSVGConverters' => 'assoc',
	'wgAntivirusSetup' => 'array',
# Parser
	'wgGrammarForms' => 'array',
	'wgParserConf' => 'assoc',
	'wgParserTestFiles' => 'simple',
	'wgUrlProtocols' => 'simple',
# Special pages
	'wgFilterLogTypes' => 'assoc',
	'wgLogActions' => 'assoc',
	'wgLogActionsHandlers' => 'assoc',
	'wgLogHeaders' => 'assoc',
	'wgLogNames' => 'assoc',
	'wgLogRestrictions' => 'assoc',
	'wgLogTypes' => 'simple',
	'wgSpecialPageGroups' => 'assoc',
	'wgRCLinkLimits' => 'simple',
	'wgRCLinkDays' => 'simple',
# Users
	'wgDefaultUserOptions' => 'assoc',
	'wgReservedUsernames' => 'simple',
	'wgBrowserBlackList' => 'simple',
# Feed
	'wgOverrideSiteFeed' => 'assoc',
# Proxies
	'wgProxyList' => 'simple',
	'wgProxyPorts' => 'simple',
	'wgProxyWhitelist' => 'simple',
# Squid
	'wgSquidServers' => 'simple',
	'wgSquidServersNoPurge' => 'simple',
# Cookie
	'wgCacheVaryCookies' => 'simple',
	'wgHttpOnlyBlacklist' => 'simple',
# Job
	'wgJobClasses' => 'assoc',
# Extensions
	'wgAPIListModules' => 'assoc',
	'wgAPIMetaModules' => 'assoc',
	'wgAPIModules' => 'assoc',
	'wgAPIPropModules' => 'assoc',
	'wgAvailableRights' => 'simple',
	'wgExceptionHooks' => 'array',
	'wgExtensionAliasesFiles' => 'array',
	'wgExtensionCredits' => 'array',
	'wgExtensionFunctions' => 'simple',
	'wgExtensionMessagesFiles' => 'assoc',
	'wgExternalStores' => 'simple',
	'wgSpecialPageCacheUpdates' => 'array',
	'wgSpecialPages' => 'assoc',
);

/**
 * Value to be used when setting matches empty()
 */
$emptyValues = array(
	'wgAppleTouchIcon' => false,
	'wgVariantArticlePath' => false,
	'wgDBerrorLog' => null,
	'wgSearchType' => null,
	'wgSharedDB' => null,
	'wgLegacyEncoding' => null,
	'wgDefaultLanguageVariant' => false,
	'wgExemptFromUserRobotsControl' => null,
	'wgExtraRandompageSQL' => false,
	'wgHandheldStyle' => false,
	'wgMetaNamespaceTalk' => false,
	'wgLocalMessageCache' => null,
	'wgInterwikiCache' => false,
	'wgReadOnly' => null,
	'wgRateLimitLog' => null,
	'wgSessionName' => false,
	'wgHTTPProxy' => false,
	'wgSharedThumbnailScriptPath' => false,
	'wgSharedUploadDBname' => false,
	'wgMimeDetectorCommand' => null,
	'wgCustomConvertCommand' => false,
	'wgTiffThumbnailType' => false,
	'wgThumbnailScriptPath' => false,
	'wgDjvuDump' => null,
	'wgDjvuRenderer' => null,
	'wgDjvuToXML' => null,
	'wgAntivirus' => null,
	'wgExternalLinkTarget' => false,
	'wgImportTargetNamespace' => null,
	'wgRC2UDPAddress' => false,
	'wgRC2UDPPort' => false,
	'wgRightsUrl' => null,
	'wgMWSuggestTemplate' => false,
	'wgOpenSearchTemplate' => false,
	'wgSearchForwardUrl' => null,
	'wgHTCPMulticastAddress' => false,
	'wgExternalDiffEngine' => false,
	'wgSearchType' => null,
	'wgLocaltimezone' => null,
	'wgLocalTZoffset' => null,
	'wgReadOnly' => null,
	'wgDjvuDump' => null,
	'wgAntivirus' => null,
	'wgImportTargetNamespace' => null,
	'wgCopyrightIcon' => null,
	'wgSearchForwardUrl' => null,
	'wgExemptFromUserRobotsControl' => null,
	'wgArticlePath' => false,

);

/**
 * Settings that can be modified only by users with 'configure-all' right
 */
$editRestricted = array(
# General
	'wgActionPaths',
	'wgAppleTouchIcon',
	'wgArticlePath',
	'wgDirectoryMode',
	'wgDiff',
	'wgDiff3',
	'wgFavicon',
	'wgMathDirectory',
	'wgMathPath',
	'wgProto',
	'wgRedirectScript',
	'wgScript',
	'wgScriptExtension',
	'wgScriptPath',
	'wgServer',
	'wgServerName',
	'wgStyleDirectory',
	'wgStylePath',
	'wgStyleSheetPath',
	'wgTmpDirectory',
	'wgUsePathInfo',
	'wgUploadBaseUrl',
	'wgUploadDirectory',
	'wgUploadNavigationUrl',
	'wgUploadPath',
	'wgVariantArticlePath',
# Db
	'wgAllDBsAreLocalhost',
	'wgCheckDBSchema',
	'wgDBAvgStatusPoll',
	'wgDBClusterTimeout',
	'wgDBerrorLog',
	'wgDBmwschema',
	'wgDBmysql5',
	'wgDBname',
	'wgDBpassword',
	'wgDBport',
	'wgDBprefix',
	'wgDBserver',
	'wgDBservers',
	'wgDBTableOptions',
	'wgDBtransactions',
	'wgDBts2schema',
	'wgDBtype',
	'wgDBuser',
	'wgDefaultExternalStore',
	'wgLBFactoryConf',
#	'wgLegacySchemaConversion',
	'wgLocalDatabases',
	'wgMasterWaitTimeout',
	'wgSearchType',
	'wgSharedDB',
	'wgSharedPrefix',
	'wgSharedTables',
	'wgSlaveLagCritical',
	'wgSlaveLagWarning',
	'wgSQLiteDataDir',
	'wgExternalServers',
# Emal
	'wgSMTP',
# Debug
	'wgDebugLogFile',
	'wgDebugLogGroups',
	'wgUDPProfilerHost',
	'wgUDPProfilerPort',
# Cache
	'wgFileCacheDirectory',
	'wgLocalMessageCache',
	'wgMemCachedServers',
# Access
	'wgAddGroups',
	'wgGroupPermissions',
	'wgGroupsAddToSelf',
	'wgGroupsRemoveFromSelf',
	'wgRemoveGroups',
	'wgReadOnlyFile',
# Rate limits
	'wgRateLimitLog',
# Proxies
#	'wgProxyKey', # Deprecated
	'wgProxyScriptPath',
	'wgSecretKey',
# Squid
	'wgInternalServer',
	'wgSquidServers',
	'wgSquidServersNoPurge',
# Img
	'wgFileStore',
	'wgHTTPProxy',
	'wgLocalFileRepo',
	'wgThumbnailScriptPath',
# Parser
	'wgTidyBin',
	'wgTidyConf',
# Special pages
	'wgRC2UDPAddress',
	'wgRC2UDPPort',
# Extensions
	'wgDisableInternalSearch',
	'wgExternalStores',
# htcp
	'wgHTCPMulticastAddress',
	'wgHTCPPort',
# Misc
	'wgMWSuggestTemplate',
	'wgOpenSearchTemplate',
);

/**
 * Settings that can be viewed only by users with 'viewconfig-all' right
 * because they can contain passwords
 */
$viewRestricted = array(
# Db
	'wgDBpassword',
	'wgDBservers',
	'wgLBFactoryConf',
	'wgExternalServers',
# Emal
	'wgSMTP',
# Proxy
	'wgProxyKey', # Deprecated
	'wgSecretKey',
);

/**
 * Array of settings that doesn't have to be modified, because they should only
 * be set by extensions, ...
 */
$notEditableSettings = array(
	'wgAPIListModules',
	'wgAPIMetaModules',
	'wgAPIModules',
	'wgAPIPropModules',
	'wgAjaxExportList',
	'wgAuth',
	'wgAutoloadClasses',
	'wgAvailableRights',
	'wgCommandLineMode',
	'wgConf',
	'wgDBconnection', // Too old
	'wgDBmysql4', // Too old
	'wgEditEncoding', // Too old
	'wgExceptionHooks',
	'wgExtensionAliasesFiles',
	'wgExtensionCredits',
	'wgExtensionFunctions',
	'wgExtensionMessagesFiles',
	'wgFilterCallback',
	'wgHooks',
	'wgInputEncoding', // Too old
	'wgJobClasses',
	'wgLogActions',
	'wgLogActionsHandlers',
	'wgLogHeaders',
	'wgLogNames',
	'wgLogTypes',
	'wgOutputEncoding', // Too old
	'wgPagePropLinkInvalidations',
	'wgParserOutputHooks',
	'wgParserTestFiles',
	'wgSkinExtensionFunctions',
	'wgSpecialPageCacheUpdates',
	'wgSpecialPages',
	'wgStyleSheetPath',
	'wgStyleVersion',
	'wgTrivialMimeDetection',
	'wgUseMemCached', // Too old
	'wgVersion',
);

/**
 * Array of settings depending of the Core version
 */
$settingsVersion = array(
	'wgNewPasswordExpiry' => array( array( '1.15alpha', '>=' ) ),
	'wgMaxRedirects' => array( array( '1.15alpha', '>=' ) ),
	'wgInvalidRedirectTargets' => array( array( '1.15alpha', '>=' ) ),
	'wgNoFollowDomainExceptions' => array( array( '1.15alpha', '>=' ) ),
	'wgUseTwoButtonsSearchForm' => array( array( '1.15alpha', '>=' ) ),
	'wgAPIMaxResultSize' => array( array( '1.15alpha', '>=' ) ),
	'wgShowDebug' => array( array( '1.15alpha', '>=' ) ),
	'wgPreprocessorCacheThreshold' => array( array( '1.15alpha', '>=' ) ),
	'wgExportMaxLinkDepth' => array( array( '1.15alpha', '>=' ) ),
	'wgUseTagFilter' => array( array( '1.15alpha', '>=' ) ),
	'wgSummarySpamRegex' => array( array( '1.15alpha', '>=' ) ),
	'wgAPIMaxUncachedDiffs' => array( array( '1.15alpha', '>=' ) ),
	'wgTiffThumbnailType' => array( array( '1.15alpha', '>=' ) ),
	'wgExportFromNamespaces' => array( array( '1.15alpha', '>=' ) ),
);
