<?php
/**
 * PLEASE DO NOT EDIT THIS FILE MANUALLY!  IT IS GENERATED USING tiToMediaWiki.php TO CREATE
 * THESE $messages ARRAYS FROM Titanium strings.xml FILES.
 *
 * i18n messages for Wikia mobile app "Game Guides".
 *
 * If this file is changed (eg: by TranslateWiki.net), then please apply the changes using
 * mediaWikiToTi.php so that they get merged back correctly.
 */

$messages = array();

$messages['en'] = array(
	'activityindicator-message' => 'Loading...',
	
	//window-wikis.js
	'window-wikis-title' => 'Wikia Game Guides',
	'window-wikis-wikilist-search-hint' => 'Search our Top Games...',
	
	//window-category.js
	'window-category-load-batch' => 'More',
	
	//window-article.js
	'window-article-button-close' => 'Close',
	'window-article-button-back' => 'Back',
	'window-article-menu-search-label' => 'Search',
	'window-article-menu-dashboard-label' => 'Guide contents',
	'window-article-menu-cancel-label' => 'Cancel',
	
	//SearchView
	'searchview-no-results' => 'No results for "%s"',
	'searchview-button-back-list' => 'Back to list',
	'searchview-button-back-article' => 'Back to article',
	
	//SearchBar
	'searchbar-hint' => 'Search %s...',
	
	//update alert
	'alert-download-updated-wikis-message' => 'The list of available guides will be updated.',
	'alert-download-updated-wikis-button-ok' => 'Ok',
	
	//errors
	'error-update-required' => 'An update for this app is available and required.',
	'error-no-connection' => 'No internet connection available.\\nPlease try again.',
	'error-server' => 'Our servers responded with an error, sorry.\\nPlease try again.',
	'error-json-parse' => 'There was a problem with the data returned from our servers, sorry.\\nPlease try again.'
);

/** Message documentation (Message documentation)
 * @author Shirayuki
 */
$messages['qqq'] = array(
	'activityindicator-message' => '{{Identical|Loading}}',
	'window-category-load-batch' => '{{Identical|More}}',
	'window-article-button-close' => '{{Identical|Close}}',
	'window-article-menu-search-label' => '{{Identical|Search}}',
);

/** Arabic (العربية)
 * @author Mutarjem horr
 */
$messages['ar'] = array(
	'activityindicator-message' => 'جاري التحميل...',
	'window-wikis-title' => 'أدلة لعبة ويكيا',
	'window-wikis-wikilist-search-hint' => 'إبحث عن ألعابنا الأكثر نجاحاً...',
	'window-category-load-batch' => 'المزيد',
	'window-article-button-close' => 'أغلق',
	'window-article-button-back' => 'رجوع',
	'window-article-menu-search-label' => 'إبحث',
	'window-article-menu-dashboard-label' => 'محتويات الدليل',
	'window-article-menu-cancel-label' => 'ألغِ',
	'searchview-no-results' => 'لا يوجد نتائج لـ"%s"',
	'searchview-button-back-list' => 'الرجوع إلى القائمة',
	'searchview-button-back-article' => 'الرجوع إلى المقالة',
	'searchbar-hint' => 'البحث  %s ...',
	'alert-download-updated-wikis-message' => 'سيتم تحديث قائمة الأدلة المتوفرة.',
	'alert-download-updated-wikis-button-ok' => 'موافق',
	'error-update-required' => 'يوجد تحديث لهذا التطبيق و هو موجود و مطلوب.',
	'error-no-connection' => 'لا يوجد اتصال إنترنت متوفر.\\n الرجاء المحاولة مرة أخرى.',
	'error-server' => 'خدامنا ردّت بخطأ، عذرا.\\n الرجاء المحاولة مرة أخرى.',
	'error-json-parse' => 'كانت هناك مشكلة مع البيانات التي تم إرجاعها من خدامنا، عذرا.\\n الرجاء المحاولة مرة أخرى.',
);

/** Azerbaijani (azərbaycanca)
 * @author Cekli829
 */
$messages['az'] = array(
	'window-article-button-close' => 'Bağlı',
	'window-article-button-back' => 'Əvvəlki',
	'window-article-menu-search-label' => 'Axtar',
	'window-article-menu-cancel-label' => 'İmtina',
	'alert-download-updated-wikis-button-ok' => 'Ok',
);

/** Breton (brezhoneg)
 * @author Fohanno
 * @author Y-M D
 */
$messages['br'] = array(
	'activityindicator-message' => 'O kargañ...',
	'window-category-load-batch' => "Muioc'h",
	'window-article-button-close' => 'Serriñ',
	'window-article-button-back' => 'Distreiñ',
	'window-article-menu-search-label' => 'Klask',
	'window-article-menu-dashboard-label' => 'Danvez ar sturlevr',
	'window-article-menu-cancel-label' => 'Nullañ',
	'searchview-no-results' => 'N\'eus bet kavet disoc\'h ebet evit "%s"',
	'searchview-button-back-list' => "Distreiñ d'ar roll",
	'searchview-button-back-article' => "Distreiñ d'ar pennad",
	'searchbar-hint' => 'Klask %s...',
	'alert-download-updated-wikis-message' => 'Hizivaet e vo roll ar sturlevrioù dieub.',
	'alert-download-updated-wikis-button-ok' => 'Mat eo',
	'error-no-connection' => "Ne c'haller ket kevreañ ouzh internet.\\nEsaeit en-dro, mar plij.",
);

/** Catalan (català)
 * @author Roxas Nobody 15
 */
$messages['ca'] = array(
	'activityindicator-message' => "S'està carregant…",
	'window-wikis-title' => 'Wikia VideoJocs',
	'window-wikis-wikilist-search-hint' => 'Cerca el nostre Top  de Videojocs...',
	'window-category-load-batch' => 'Més',
	'window-article-button-close' => 'Tanca',
	'window-article-button-back' => 'Torna',
	'window-article-menu-search-label' => 'Cerca',
	'window-article-menu-dashboard-label' => 'Guia de Continguts',
	'window-article-menu-cancel-label' => 'Anul·la',
	'searchview-no-results' => 'No hi ha resultats per a " %s "',
	'searchview-button-back-list' => 'Tornar a la llista',
	'searchview-button-back-article' => "Tornar a l'article",
	'searchbar-hint' => 'Cercant...',
	'alert-download-updated-wikis-message' => "La llista de guies disponibles s'actualitzaràn.",
	'alert-download-updated-wikis-button-ok' => "D'acord",
	'error-update-required' => 'Una actualització per a aquest app està disponible i necessària.',
	'error-no-connection' => 'No hi ha connexió a internet disponible. torneu-\\nPlease.',
	'error-server' => 'Els nostres servidors va respondre amb un error, ho sento. torneu-\\nPlease.',
	'error-json-parse' => 'Hi havia un problema amb les dades que es retornen dels nostres servidors, ho sento. torneu-\\nPlease.',
);

/** Chechen (нохчийн)
 * @author Умар
 */
$messages['ce'] = array(
	'window-article-button-close' => 'ДӀачӀагӀа',
);

/** Czech (česky)
 * @author Chmee2
 * @author Reaperman
 */
$messages['cs'] = array(
	'activityindicator-message' => 'Nahrávám…',
	'window-wikis-title' => 'Wikia Herní návody',
	'window-wikis-wikilist-search-hint' => 'Vyhledat naše top hry...',
	'window-category-load-batch' => 'Více',
	'window-article-button-close' => 'Zavřít',
	'window-article-button-back' => 'Zpět',
	'window-article-menu-search-label' => 'Hledat',
	'window-article-menu-dashboard-label' => 'Obsah návodu',
	'window-article-menu-cancel-label' => 'Storno',
	'searchview-no-results' => 'Žádné výsledky pro „%s“',
	'searchview-button-back-list' => 'Zpět na seznam',
	'searchview-button-back-article' => 'Zpět na článek',
	'searchbar-hint' => 'Hledání  %s...',
	'alert-download-updated-wikis-message' => 'Seznam dostupných návodů bude aktualizován.',
	'alert-download-updated-wikis-button-ok' => 'OK',
	'error-update-required' => 'Aktualizace pro tuto aplikaci je dostupná a vyžadovaná.',
	'error-no-connection' => 'Připojení k Internetu není k dispozici. \\nProsím, opakujte akci.',
);

/** Welsh (Cymraeg)
 * @author Thefartydoctor
 */
$messages['cy'] = array(
	'window-category-load-batch' => 'Mwy',
	'alert-download-updated-wikis-button-ok' => 'Iawn',
);

/** German (Deutsch)
 * @author Inkowik
 * @author Kghbln
 * @author LWChris
 * @author Laximilian scoken
 * @author Tim Bartel
 * @author Welathêja
 */
$messages['de'] = array(
	'activityindicator-message' => 'Lade …',
	'window-wikis-title' => 'Wikia Game Guides',
	'window-wikis-wikilist-search-hint' => 'Suchen unsere beliebtesten Spiele...',
	'window-category-load-batch' => 'Mehr',
	'window-article-button-close' => 'Schließen',
	'window-article-button-back' => 'Zurück',
	'window-article-menu-search-label' => 'Suchen',
	'window-article-menu-dashboard-label' => 'Guide Inhalt',
	'window-article-menu-cancel-label' => 'Abbrechen',
	'searchview-no-results' => 'Keine Ergebnisse für %s',
	'searchview-button-back-list' => 'Zurück zur Liste',
	'searchview-button-back-article' => 'Zurück zum Artikel',
	'searchbar-hint' => 'Suche nach %s...',
	'alert-download-updated-wikis-message' => 'Die Liste der verfügbaren Guides muss aktualisiert werden.',
	'alert-download-updated-wikis-button-ok' => 'OK',
	'error-update-required' => 'Für diese App ist ein Update verfügbar und erforderlich.',
	'error-no-connection' => 'Keine Internet-Verbindung vorhanden.\\nBitte versuche es erneut.',
	'error-server' => 'Unsere Server haben einen Fehler gemeldet, sorry.\\nBitte versuche es erneut.',
	'error-json-parse' => 'Es gab ein Problem mit den Daten von unseren Servern, sorry.\\nBitte versuche es erneut.',
);

/** Zazaki (Zazaki)
 * @author Erdemaslancan
 */
$messages['diq'] = array(
	'activityindicator-message' => 'Bar beno...',
	'window-wikis-title' => 'Wikia Kay Şınasnayış',
	'window-category-load-batch' => 'Zewbi',
	'window-article-button-close' => 'Racnê',
	'window-article-button-back' => 'Peyser',
	'window-article-menu-search-label' => 'Cı geyre',
	'window-article-menu-dashboard-label' => 'Zerreki şınasnayş',
	'window-article-menu-cancel-label' => 'Bıterkne',
	'searchview-no-results' => 'Qandê "%s" neticey çıniyê',
	'searchview-button-back-list' => 'Peyser şo lista',
	'searchview-button-back-article' => 'Peyd şo wesiqa',
	'searchbar-hint' => 'Geyreno %s...',
	'alert-download-updated-wikis-button-ok' => 'Temam',
);

/** Spanish (español)
 * @author VegaDark
 */
$messages['es'] = array(
	'activityindicator-message' => 'Cargando...',
	'window-wikis-title' => 'Guías de Juego de Wikia',
	'window-wikis-wikilist-search-hint' => 'Buscar nuestros mejores juegos...',
	'window-category-load-batch' => 'Más',
	'window-article-button-close' => 'Cerrar',
	'window-article-button-back' => 'Atrás',
	'window-article-menu-search-label' => 'Buscar',
	'window-article-menu-dashboard-label' => 'Guía de contenidos',
	'window-article-menu-cancel-label' => 'Cancelar',
	'searchview-no-results' => 'No hay resultados para "%s"',
	'searchview-button-back-list' => 'Volver a la lista',
	'searchview-button-back-article' => 'Volver al artículo',
	'searchbar-hint' => 'Buscando %s...',
	'alert-download-updated-wikis-message' => 'La lista de las guías disponibles serán actualizadas.',
	'alert-download-updated-wikis-button-ok' => 'Ok',
	'error-update-required' => 'Hay una actualización necesaria disponible para esta aplicación.',
	'error-no-connection' => 'Conexión a Intenet no disponible.\\nInténtalo de nuevo.',
	'error-server' => 'Nuestros servidores respondieron con un error, lo sentimos.\\nInténtalo de nuevo.',
	'error-json-parse' => 'Hubo un problema con los datos devueltos desde nuestros servidores, lo sentimos.\\nInténtalo de nuevo.',
);

/** Finnish (suomi)
 * @author Centerlink
 * @author Nedergard
 */
$messages['fi'] = array(
	'activityindicator-message' => 'Ladataan...',
	'window-category-load-batch' => 'Lisää',
	'window-article-button-close' => 'Sulje',
	'window-article-button-back' => 'Takaisin',
	'window-article-menu-search-label' => 'Etsi',
	'window-article-menu-cancel-label' => 'Peruuta',
	'searchview-button-back-list' => 'Palaa luetteloon',
	'alert-download-updated-wikis-button-ok' => 'Ok',
);

/** Faroese (føroyskt)
 * @author EileenSanda
 */
$messages['fo'] = array(
	'window-wikis-title' => 'Wikia Spæl Vegleiðing',
	'window-wikis-wikilist-search-hint' => 'Leita eftir best umtóktu spølum...',
	'window-category-load-batch' => 'Meira',
	'window-article-button-close' => 'Lat aftur',
	'window-article-button-back' => 'Aftur',
	'window-article-menu-search-label' => 'Leita',
	'window-article-menu-dashboard-label' => 'Innihald av leiðbeining',
	'window-article-menu-cancel-label' => 'Ógildað',
	'searchview-no-results' => 'Ongi úrslit fyri "%s"',
	'searchview-button-back-list' => 'Aftur til lista',
	'searchview-button-back-article' => 'Aftur til grein',
	'searchbar-hint' => 'Leita %s...',
	'alert-download-updated-wikis-message' => 'Listin yvir tøkar vegleiðingar verður dagførdur.',
	'alert-download-updated-wikis-button-ok' => 'Í lagi',
	'error-update-required' => 'Ein dagføring fyri hesa appina er tøk og er eitt krav.',
	'error-no-connection' => 'Onki internet samband er at finna. \\n Vinarliga royn aftur.',
);

/** French (français)
 * @author Wyz
 */
$messages['fr'] = array(
	'activityindicator-message' => 'Chargement...',
	'window-wikis-title' => 'Wikia — Guides de jeu',
	'window-wikis-wikilist-search-hint' => 'Rechercher nos jeux préférés',
	'window-category-load-batch' => 'Plus',
	'window-article-button-close' => 'Fermer',
	'window-article-button-back' => 'Retour',
	'window-article-menu-search-label' => 'Rechercher',
	'window-article-menu-dashboard-label' => 'Contenu du guide',
	'window-article-menu-cancel-label' => 'Annuler',
	'searchview-no-results' => 'Aucun résultat pour « %s »',
	'searchview-button-back-list' => 'Retour à la liste',
	'searchview-button-back-article' => 'Retour à l’article',
	'searchbar-hint' => 'Recherche de « %s »...',
	'alert-download-updated-wikis-message' => 'La liste des guides disponibles va être mise à jour.',
	'alert-download-updated-wikis-button-ok' => 'Ok',
	'error-update-required' => 'Une mise à jour de l’application est disponible et nécessaire.',
	'error-no-connection' => 'Aucune connexion Internet disponible.\\nVeuillez réessayer.',
	'error-server' => 'Nos serveurs ont renvoyé une erreur, désolé.\\nVeuillez réessayer.',
	'error-json-parse' => 'Une erreur est survenue avec les données retournées par nos serveurs, désolé.\\nVeuillez réessayer.',
);

/** Galician (galego)
 * @author Toliño
 */
$messages['gl'] = array(
	'activityindicator-message' => 'Cargando...',
	'window-wikis-title' => 'Guías de xogos de Wikia',
	'window-wikis-wikilist-search-hint' => 'Procurar entre os nosos xogos preferidos...',
	'window-category-load-batch' => 'Máis',
	'window-article-button-close' => 'Pechar',
	'window-article-button-back' => 'Volver',
	'window-article-menu-search-label' => 'Procurar',
	'window-article-menu-dashboard-label' => 'Guía de contidos',
	'window-article-menu-cancel-label' => 'Cancelar',
	'searchview-no-results' => 'Non hai resultados para "%s"',
	'searchview-button-back-list' => 'Volver á lista',
	'searchview-button-back-article' => 'Volver ao artigo',
	'searchbar-hint' => 'Procurar %s...',
	'alert-download-updated-wikis-message' => 'A lista das guías dispoñibles será actualizada.',
	'alert-download-updated-wikis-button-ok' => 'Aceptar',
	'error-update-required' => 'Hai unha actualización necesaria e dispoñible para esta aplicación.',
	'error-no-connection' => 'Non hai dispoñible ningunha conexión á internet.\\nInténteo de novo.',
	'error-server' => 'Os nosos servidores devolveron un erro, sentímolo.\\nInténteo de novo.',
	'error-json-parse' => 'Houbo un problema cos datos obtidos dos nosos servidores, sentímolo.\\nInténteo de novo.',
);

/** Hungarian (magyar)
 * @author Dj
 */
$messages['hu'] = array(
	'activityindicator-message' => 'Betöltés…',
	'window-wikis-title' => 'Wikia játék útmutatók',
	'window-wikis-wikilist-search-hint' => 'Legismertebb játékok keresése...',
	'window-category-load-batch' => 'Több',
	'window-article-button-close' => 'Bezárás',
	'window-article-button-back' => 'Vissza',
	'window-article-menu-search-label' => 'Keresés',
	'window-article-menu-dashboard-label' => 'Az útmutató tartalma',
	'window-article-menu-cancel-label' => 'Mégse',
	'searchview-no-results' => 'Nem hozott eredményt a „%s” keresés',
	'searchview-button-back-list' => 'Vissza a listához',
	'searchview-button-back-article' => 'Vissza a cikkhez',
	'searchbar-hint' => 'Keresés  %s ...',
	'alert-download-updated-wikis-message' => 'A rendelkezésre álló útmutatók listája frissül.',
	'alert-download-updated-wikis-button-ok' => 'OK',
	'error-update-required' => 'Ehhez az alkalmazáshoz frissítés van, és szükséges is.',
	'error-no-connection' => 'Nincs internet kapcsolat.\\nPróbáld meg újra!',
	'error-server' => 'Elnézést, a szerverünk hibás választ adott.\\bPróbáld meg újra!',
	'error-json-parse' => 'Elnézést, gond volt a szerverünk által visszaküldött adattal.\\nPróbáld meg újra!',
);

/** Interlingua (interlingua)
 * @author McDutchie
 */
$messages['ia'] = array(
	'activityindicator-message' => 'Cargamento…',
	'window-wikis-title' => 'Wikia - Guidas de joco',
	'window-wikis-wikilist-search-hint' => 'Cercar nostre melior jocos...',
	'window-category-load-batch' => 'Plus',
	'window-article-button-close' => 'Clauder',
	'window-article-button-back' => 'Retornar',
	'window-article-menu-search-label' => 'Cercar',
	'window-article-menu-dashboard-label' => 'Contento del guida',
	'window-article-menu-cancel-label' => 'Cancellar',
	'searchview-no-results' => 'Nulle resultato pro "%s"',
	'searchview-button-back-list' => 'Retornar al lista',
	'searchview-button-back-article' => 'Retornar al articulo',
	'searchbar-hint' => 'Cercar %s…',
	'alert-download-updated-wikis-message' => 'Le lista del guidas disponibile essera actualisate.',
	'alert-download-updated-wikis-button-ok' => 'OK',
	'error-update-required' => 'Un actualisation de iste application es disponibile e necessari.',
	'error-no-connection' => 'Nulle connexion a internet disponibile.\\nPer favor reproba.',
	'error-server' => 'Nostre servitores respondeva con un error.\\nPer favor reproba.',
	'error-json-parse' => 'Un problema occurreva con le datos retornate ab nostre servitores.\\nPer favor reproba.',
);

/** Indonesian (Bahasa Indonesia)
 * @author C5st4wr6ch
 */
$messages['id'] = array(
	'window-wikis-wikilist-search-hint' => 'Cari Permainan Teratas kami',
	'searchview-no-results' => 'Tidak ada hasil untuk "%s"',
	'error-update-required' => 'Pembaruan untuk aplikasi ini telah tersedia dan diperlukan.',
	'error-json-parse' => 'Ada masalah dengan data yang dikembalikan dari server kami, maaf.\\nSilakan coba lagi.',
);

/** Italian (italiano)
 * @author Beta16
 * @author Federico "Lox" Lucignano <federico(at)wikia-inc.com>
 * @author Ximo17
 */
$messages['it'] = array(
	'activityindicator-message' => 'Caricamento...',
	'window-wikis-title' => 'Wikia Game Guides',
	'window-wikis-wikilist-search-hint' => 'Cerca i nostri giochi migliori...',
	'window-category-load-batch' => 'Altri',
	'window-article-button-close' => 'Chiudi',
	'window-article-button-back' => 'Indietro',
	'window-article-menu-search-label' => 'Cerca',
	'window-article-menu-dashboard-label' => 'Contenuti',
	'window-article-menu-cancel-label' => 'Annulla',
	'searchview-no-results' => 'Nessun risultato per "%s"',
	'searchview-button-back-list' => 'Torna alla lista',
	'searchview-button-back-article' => "Torna all'articolo",
	'searchbar-hint' => 'Cerca in %s...',
	'alert-download-updated-wikis-message' => 'La lista dei giochi disponibili verrá aggiornata.',
	'alert-download-updated-wikis-button-ok' => 'Ok',
	'error-update-required' => 'È disponibile un aggiornamento obbligatorio per questa applicazione.',
	'error-no-connection' => 'Nessuna connessione internet disponibile.\\nSi prega di riprovare.',
	'error-server' => 'Spiacenti, i nostri server hanno risposto con un errore.\\nSi prega di riprovare.',
	'error-json-parse' => 'Spiacenti, è stato riscontrato un problema con i dati inviati dai nostri server.\\nSi prega di riprovare.',
);

/** Khmer (ភាសាខ្មែរ)
 * @author គីមស៊្រុន
 */
$messages['km'] = array(
	'activityindicator-message' => 'កំពុងផ្ទុក​...',
);

/** Korean (한국어)
 * @author Infinity
 * @author 아라
 */
$messages['ko'] = array(
	'activityindicator-message' => '불러오는 중...',
	'window-wikis-title' => '위키아 게임 가이드',
	'window-wikis-wikilist-search-hint' => '상위 게임 찾기...',
	'window-category-load-batch' => '더 보기',
	'window-article-button-close' => '닫기',
	'window-article-button-back' => '뒤로',
	'window-article-menu-search-label' => '찾기',
	'window-article-menu-dashboard-label' => '도움말 목차',
	'window-article-menu-cancel-label' => '취소',
	'searchview-no-results' => '"%s"에 대한 결과가 없습니다',
	'searchview-button-back-list' => '목록으로 돌아가기',
	'searchview-button-back-article' => '문서로 돌아가기',
	'searchbar-hint' => '%s 찾기...',
	'alert-download-updated-wikis-message' => '사용 가능한 가이드 목록는 업데이트될 것입니다.',
	'alert-download-updated-wikis-button-ok' => '확인',
	'error-update-required' => '이 앱에 필요한 업데이트가 있습니다.',
	'error-no-connection' => '사용 가능한 인터넷 연결이 없습니다.\\n다시 시도하세요.',
	'error-server' => '저희 서버에 오류가 발생해서 죄송합니다.\\n다시 시도하세요.',
	'error-json-parse' => '저희 서버로 돌아온 자료에 문제가 있습니다.\\n다시 시도하세요.',
);

/** Kurdish (Latin script) (Kurdî (latînî)‎)
 * @author George Animal
 */
$messages['ku-latn'] = array(
	'window-article-button-close' => 'Bigre',
	'window-article-menu-cancel-label' => 'Betal bike',
);

/** Luxembourgish (Lëtzebuergesch)
 * @author Robby
 */
$messages['lb'] = array(
	'activityindicator-message' => 'Lueden...',
	'window-category-load-batch' => 'Méi',
	'window-article-button-close' => 'Zoumaachen',
	'window-article-button-back' => 'Zréck',
	'window-article-menu-search-label' => 'Sichen',
	'window-article-menu-cancel-label' => 'Ofbriechen',
	'searchview-button-back-article' => 'Zréck op den Artikel',
	'searchbar-hint' => 'No "%s" sichen',
	'alert-download-updated-wikis-button-ok' => 'OK',
);

/** Macedonian (македонски)
 * @author Bjankuloski06
 */
$messages['mk'] = array(
	'activityindicator-message' => 'Вчитувам...',
	'window-wikis-title' => 'Водичи за игри',
	'window-wikis-wikilist-search-hint' => 'Пребарајте ги нашите Водечки игри',
	'window-category-load-batch' => 'Повеќе',
	'window-article-button-close' => 'Затвори',
	'window-article-button-back' => 'Назад',
	'window-article-menu-search-label' => 'Пребарување',
	'window-article-menu-dashboard-label' => 'Содржина на водичот',
	'window-article-menu-cancel-label' => 'Откажи',
	'searchview-no-results' => 'Не пронајдов резулати за „%s“',
	'searchview-button-back-list' => 'Назад на списокот',
	'searchview-button-back-article' => 'Назад на статијата',
	'searchbar-hint' => 'Пребарај %s...',
	'alert-download-updated-wikis-message' => 'Списокот на водичи на располагање ќе биде дополнет.',
	'alert-download-updated-wikis-button-ok' => 'Ок',
	'error-update-required' => 'Овој приложен програм има поднова што мора да ја направите.',
	'error-no-connection' => 'Не сте поврзани со интернет.\\nОбидете се подоцна.',
	'error-server' => 'Нажалост, нашите опслужувачи одговорија со грешка.\\nОбидете се подоцна.',
	'error-json-parse' => 'Нажалост, се појави проблем со податоците што ги вратија нашите опслужувачи.\\nОбидете се подоцна.',
);

/** Malay (Bahasa Melayu)
 * @author Anakmalaysia
 */
$messages['ms'] = array(
	'activityindicator-message' => 'Memuatkan...',
	'window-wikis-title' => 'Panduan Permainan Wikia',
	'window-wikis-wikilist-search-hint' => 'Permainan Teratas Kami',
	'window-category-load-batch' => 'Lagi',
	'window-article-button-close' => 'Tutup',
	'window-article-button-back' => 'Kembali',
	'window-article-menu-search-label' => 'Cari',
	'window-article-menu-dashboard-label' => 'Kandungan panduan',
	'window-article-menu-cancel-label' => 'Batalkan',
	'searchview-no-results' => 'Tiada hasil untuk "%s"',
	'searchview-button-back-list' => 'Kembali ke senarai',
	'searchview-button-back-article' => 'Kembali ke rencana',
	'searchbar-hint' => 'Cari %s...',
	'alert-download-updated-wikis-message' => 'Senarai panduan yang ada akan dikemas kini.',
	'alert-download-updated-wikis-button-ok' => 'OK',
	'error-update-required' => 'Ada kemas kini yang diperlukan untuk aplikasi ini.',
	'error-no-connection' => 'Tiada sambungan internet.\\nSila cuba lagi.',
	'error-server' => 'Minta maaf, pelayan membalas dengan ralat.\\nSila cuba lagi.',
	'error-json-parse' => 'Maaf, ada masalah dengan data yang dipulangkan dari pelayan kami.\\nSila cuba lagi.',
);

/** Norwegian Bokmål (norsk bokmål)
 * @author Audun
 * @author Nghtwlkr
 */
$messages['nb'] = array(
	'activityindicator-message' => 'Laster inn...',
	'window-wikis-title' => 'Wikia spillguider',
	'window-wikis-wikilist-search-hint' => 'Våre toppspill',
	'window-category-load-batch' => 'Mer',
	'window-article-button-close' => 'Lukk',
	'window-article-button-back' => 'Tilbake',
	'window-article-menu-search-label' => 'Søk',
	'window-article-menu-dashboard-label' => 'Guideinnhold',
	'window-article-menu-cancel-label' => 'Avbryt',
	'searchview-no-results' => 'Ingen resultater for «%s»',
	'searchview-button-back-list' => 'Tilbake til listen',
	'searchview-button-back-article' => 'Tilbake til artikkel',
	'searchbar-hint' => 'Søk etter %s...',
	'alert-download-updated-wikis-message' => 'Listen over tilgjengelige guider vil bli oppdatert.',
	'alert-download-updated-wikis-button-ok' => 'Ok',
	'error-update-required' => 'En oppdatering for denne appen er tilgjengelig og påkrevd.',
	'error-no-connection' => 'Ingen internett-tilkobling tilgjengelig.\\nVennligst prøv igjen.',
	'error-server' => 'Serverne våre svarte med en feil, beklager.\\nVennligst prøv igjen.',
	'error-json-parse' => 'Det oppstod et problem med dataene returnert fra serverne våre, beklager.\\nVennligst prøv igjen.',
);

/** Dutch (Nederlands)
 * @author SPQRobin
 * @author Siebrand
 * @author Vicky Carlsson <vicky(at)wikia-inc.com>
 */
$messages['nl'] = array(
	'activityindicator-message' => 'Bezig met laden…',
	'window-wikis-title' => 'Wikia Game Guides',
	'window-wikis-wikilist-search-hint' => 'Bekijk onze topgames...',
	'window-category-load-batch' => 'Meer',
	'window-article-button-close' => 'Sluiten',
	'window-article-button-back' => 'Terug',
	'window-article-menu-search-label' => 'Zoeken',
	'window-article-menu-dashboard-label' => 'Inhoud Gids',
	'window-article-menu-cancel-label' => 'Annuleren',
	'searchview-no-results' => 'Geen resultaten voor "%s"',
	'searchview-button-back-list' => 'Terug naar lijst',
	'searchview-button-back-article' => 'Terug naar artikel',
	'searchbar-hint' => 'Zoek %s...',
	'alert-download-updated-wikis-message' => 'De lijst met beschikbare gidsen wordt bijgewerkt.',
	'alert-download-updated-wikis-button-ok' => 'Oké',
	'error-update-required' => 'Er is een nieuwere versie van deze toepassing beschikbaar die geïnstalleerd moet worden.',
	'error-no-connection' => 'Geen internetverbinding beschikbaar. \\nProbeer het opnieuw.',
	'error-server' => 'Sorry, onze servers reageerden met een foutmelding. \\nProbeer het opnieuw.',
	'error-json-parse' => 'Er was een probleem met de gegevens die door onze servers zijn verzonden.\\nProbeer het opnieuw.',
);

/** Pälzisch (Pälzisch)
 * @author Manuae
 */
$messages['pfl'] = array(
	'window-category-load-batch' => 'Waidari',
	'window-article-button-close' => 'Schließe',
	'window-article-button-back' => 'Zrigg',
	'window-article-menu-search-label' => 'Suche',
);

/** Polish (polski)
 * @author Jakub Olek <bukaj.kelo(at)gmail.com>
 * @author Sovq
 * @author Sp5uhe
 */
$messages['pl'] = array(
	'activityindicator-message' => 'Ładowanie...',
	'window-wikis-title' => 'Przewodniki Wikia Game Guides',
	'window-wikis-wikilist-search-hint' => 'Nasze Najlepsze Gry',
	'window-category-load-batch' => 'Więcej',
	'window-article-button-close' => 'Zamknij',
	'window-article-button-back' => 'Cofnij',
	'window-article-menu-search-label' => 'Szukaj',
	'window-article-menu-dashboard-label' => 'Zawartość przewodnika',
	'window-article-menu-cancel-label' => 'Anuluj',
	'searchview-no-results' => 'Brak wyników dla "%s"',
	'searchview-button-back-list' => 'Wróć do listy',
	'searchview-button-back-article' => 'Wróć do artykułu',
	'searchbar-hint' => 'Szukaj %s...',
	'alert-download-updated-wikis-message' => 'Lista dostępnych przewodników zostanie zaktualizowana.',
	'alert-download-updated-wikis-button-ok' => 'Ok',
	'error-update-required' => 'Dostępna i wymagana jest aktualizacja tej aplikacji.',
	'error-no-connection' => 'Brak połączenia z Internetem.\\nSpróbuj ponownie.',
	'error-server' => 'Serwer zwrócił błąd.\\nSpróbuj ponownie.',
	'error-json-parse' => 'Aplikacja otrzymała błędne dane z serwera.\\nSpróbuj ponownie.',
);

/** Piedmontese (Piemontèis)
 * @author Borichèt
 * @author Dragonòt
 */
$messages['pms'] = array(
	'activityindicator-message' => 'A caria ...',
	'window-wikis-title' => 'Guide dij Gieugh Wikia',
	'window-wikis-wikilist-search-hint' => 'Sërché nòstri Mej Gieugh...',
	'window-category-load-batch' => 'Pi',
	'window-article-button-close' => 'Sara',
	'window-article-button-back' => 'André',
	'window-article-menu-search-label' => 'Sërca',
	'window-article-menu-dashboard-label' => 'Contnù dla guida',
	'window-article-menu-cancel-label' => 'Scancela',
	'searchview-no-results' => 'Gnun arzultà për "%s"',
	'searchview-button-back-list' => 'André a la lista',
	'searchview-button-back-article' => 'André a la vos',
	'searchbar-hint' => 'Sërché %s...',
	'alert-download-updated-wikis-message' => 'La lista dle guide disponìbij a sarà agiornà.',
	'alert-download-updated-wikis-button-ok' => 'Va bin',
	'error-update-required' => "N'agiornament për costa aplicassion a l'é disponìbil e obligatòri.",
	'error-no-connection' => "Gnun-e conession sla Ragnà disponìbij.\\nPër piasì, ch'a preuva torna.",
	'error-server' => "Ij nòstri servent a l'han rëspondù con n'eror, an dëspias spiasent.\\nPër piasì, ch'a preuva torna.",
	'error-json-parse' => "A-i é staje un problema con ij dat artornà dai nòst servent, an dëspias.\\nPër piasì, ch'a preuva torna.",
);

/** Pashto (پښتو)
 * @author Ahmed-Najib-Biabani-Ibrahimkhel
 */
$messages['ps'] = array(
	'activityindicator-message' => 'برسېرېدنې کې دی...',
	'window-category-load-batch' => 'نور',
	'window-article-button-close' => 'تړل',
	'window-article-button-back' => 'پر شا',
	'window-article-menu-search-label' => 'پلټنه',
	'window-article-menu-cancel-label' => 'ناگارل',
	'alert-download-updated-wikis-button-ok' => 'ښه',
);

/** Portuguese (português)
 * @author Hamilton Abreu
 * @author Luckas
 */
$messages['pt'] = array(
	'activityindicator-message' => 'A carregar…',
	'window-wikis-title' => 'Guias de Jogos da Wikia',
	'window-wikis-wikilist-search-hint' => 'Os Melhores Jogos',
	'window-category-load-batch' => 'Mais',
	'window-article-button-close' => 'Fechar',
	'window-article-button-back' => 'Voltar',
	'window-article-menu-search-label' => 'Pesquisar',
	'window-article-menu-dashboard-label' => 'Índice do guia',
	'window-article-menu-cancel-label' => 'Cancelar',
	'searchview-no-results' => 'Não foram encontrados resultados para "%s"',
	'searchview-button-back-list' => 'Voltar à lista',
	'searchview-button-back-article' => 'Voltar ao artigo',
	'searchbar-hint' => 'Pesquisar %s...',
	'alert-download-updated-wikis-message' => 'A lista de guias disponíveis será atualizada.',
	'alert-download-updated-wikis-button-ok' => 'Ok',
	'error-update-required' => 'Está disponível uma atualização necessária para esta aplicação.',
	'error-no-connection' => 'Não está disponível nenhuma ligação à internet.\\nTente novamente, por favor.',
	'error-server' => 'Desculpe, os nossos servidores responderam com um erro.\\nTente novamente, por favor.',
	'error-json-parse' => 'Desculpe, houve um problema com os dados recebidos dos nossos servidores.\\nTente novamente, por favor.',
);

/** Brazilian Portuguese (português do Brasil)
 * @author Luckas
 * @author Luckas Blade
 */
$messages['pt-br'] = array(
	'activityindicator-message' => 'Carregando...',
	'window-category-load-batch' => 'Mais',
	'window-article-button-close' => 'Fechar',
	'window-article-button-back' => 'Voltar',
	'window-article-menu-search-label' => 'Pesquisar',
	'window-article-menu-cancel-label' => 'Cancelar',
	'searchbar-hint' => 'Pesquisar %s...',
	'alert-download-updated-wikis-button-ok' => 'Ok',
);

/** tarandíne (tarandíne)
 * @author Joetaras
 */
$messages['roa-tara'] = array(
	'activityindicator-message' => 'Stoche a scareche…',
	'window-wikis-title' => 'Guide le le Sciueche de Uicchia',
	'window-wikis-wikilist-search-hint' => 'Cirche le Sciuche Megghie megghie...',
	'window-category-load-batch' => 'De cchiù',
	'window-article-button-close' => 'Achiude',
	'window-article-button-back' => 'Rrete',
	'window-article-menu-search-label' => 'Cirche',
	'window-article-menu-dashboard-label' => "Condenute d'a guide",
	'window-article-menu-cancel-label' => 'Annulle',
	'searchview-no-results' => 'Nisciune resultate pe "%s"',
	'searchview-button-back-list' => "Tuèrne a l'elenghe",
	'searchview-button-back-article' => "Tuèrne a 'a vôsce",
	'searchbar-hint' => 'Cirche %s...',
	'alert-download-updated-wikis-message' => "L'elenghe de le guide disponibbile adda essere aggiornate.",
	'alert-download-updated-wikis-button-ok' => 'Ok',
	'error-update-required' => "'N'aggiornamende pe sta applicazione jè disponibbile e richieste.",
	'error-no-connection' => 'Nisciuna connessione a indernette disponibbile.\\nPe piacere pruève arrete.',
	'error-server' => "Le nostre server stonne a respondene cu 'n'errore.\\nPe piacere pruève arrete.",
	'error-json-parse' => "Stè 'nu probbleme cu 'u date ca ha turnate da le server nuèstre.\\nPe piacere pruève arrete.",
);

/** Russian (русский)
 * @author Byulent
 * @author Kuzura
 */
$messages['ru'] = array(
	'activityindicator-message' => 'Загрузка...',
	'window-wikis-title' => 'Wikia Game Guides',
	'window-wikis-wikilist-search-hint' => 'Поиск в Top Games...',
	'window-category-load-batch' => 'Более',
	'window-article-button-close' => 'Закрыть',
	'window-article-button-back' => 'Назад',
	'window-article-menu-search-label' => 'Поиск',
	'window-article-menu-dashboard-label' => 'Содержание руководства',
	'window-article-menu-cancel-label' => 'Отмена',
	'searchview-no-results' => 'Нет результатов для "%s"',
	'searchview-button-back-list' => 'Назад к списку',
	'searchview-button-back-article' => 'Вернуться к статье',
	'searchbar-hint' => 'Поиск  %s...',
	'alert-download-updated-wikis-message' => 'Список доступных руководств будет обновлен.',
	'alert-download-updated-wikis-button-ok' => 'OK',
	'error-update-required' => 'Доступно и требуется обновление для этого приложения.',
	'error-no-connection' => 'Нет подключения к Интернету. \\nПовторите попытку.',
	'error-server' => 'Сервер отвечает ошибкой. \\nПовторите попытку.',
	'error-json-parse' => 'Существует проблема с отправкой данных на наши сервера, извините. \\nПожалуйста, попытайтесь снова.',
);

/** Swedish (svenska)
 * @author Vicky Carlsson <vicky(at)wikia-inc.com>
 * @author WikiPhoenix
 */
$messages['sv'] = array(
	'activityindicator-message' => 'Läser in...',
	'window-wikis-title' => 'Wikia Game Guides',
	'window-wikis-wikilist-search-hint' => 'Våra Topp-spel',
	'window-category-load-batch' => 'Mer',
	'window-article-button-close' => 'Stäng',
	'window-article-button-back' => 'Tillbaka',
	'window-article-menu-search-label' => 'Sök',
	'window-article-menu-dashboard-label' => 'Guidens innehåll',
	'window-article-menu-cancel-label' => 'Avbryt',
	'searchview-no-results' => 'Inga resultat for "%s"',
	'searchview-button-back-list' => 'Tillbaka till listan',
	'searchview-button-back-article' => 'Tillbaka till artikeln',
	'searchbar-hint' => 'Sök %s...',
	'alert-download-updated-wikis-message' => 'Listan med tillgängliga guider kommer att uppdateras.',
	'alert-download-updated-wikis-button-ok' => 'OK',
	'error-update-required' => 'En uppdatering för denna app är tillgänglig och nödvändig.',
	'error-no-connection' => 'Ingen internetanslutning är tillgänglig.\\nVar god försök igen.',
	'error-server' => 'Våra servrar svarade tyvärr med ett fel.\\nVar god försök igen.',
	'error-json-parse' => 'Det uppstod tyvärr ett problem med datan som returneras från våra servrar.\\nVar god försök igen.',
);

/** Telugu (తెలుగు)
 * @author Veeven
 */
$messages['te'] = array(
	'window-article-menu-search-label' => 'వెతుకు',
	'window-article-menu-cancel-label' => 'రద్దుచేయి',
	'searchview-no-results' => '"%s"కి ఫలితాలేమీ లేవు',
	'alert-download-updated-wikis-button-ok' => 'సరే',
);

/** Tagalog (Tagalog)
 * @author AnakngAraw
 */
$messages['tl'] = array(
	'activityindicator-message' => 'Ikinakarga...',
	'window-wikis-title' => 'Mga Gabay sa Palaro ng Wikia',
	'window-wikis-wikilist-search-hint' => 'Hanapin ang aming Pangunahing mga Laro...',
	'window-category-load-batch' => 'Marami pa',
	'window-article-button-close' => 'Isara',
	'window-article-button-back' => 'Bumalik',
	'window-article-menu-search-label' => 'Maghanap',
	'window-article-menu-dashboard-label' => 'Mga nilalaman ng patnubay',
	'window-article-menu-cancel-label' => 'Huwag ituloy',
	'searchview-no-results' => 'Walang mga resulta para sa "%s"',
	'searchview-button-back-list' => 'Bumalik sa listahan',
	'searchview-button-back-article' => 'Bumalik sa artikulo',
	'searchbar-hint' => 'Hanapin ang %s...',
	'alert-download-updated-wikis-message' => 'Isasapanahon ang listahan ng makukuhang mga gabay.',
	'alert-download-updated-wikis-button-ok' => 'Sige',
	'error-update-required' => 'Makukuha at kailangan ang isang pagsasapanahon para sa aplikasyong ito.',
	'error-no-connection' => 'Walang makuhang pagkakakabit sa internet.\\nPaki subukan ulit.',
	'error-server' => 'Tumugon ang aming mga tagapaghain na may kamalian, paumanhin.\\nPaki subukan ulit.',
	'error-json-parse' => 'Mayroong isang suliranin sa datong ibinalik magmula sa aming mga tagapaghain, paumanhin.\\nPaki subukan ulit.',
);

/** толышә зывон (толышә зывон)
 * @author Гусейн
 */
$messages['tly'] = array(
	'activityindicator-message' => 'Бо кардә...',
	'window-article-menu-search-label' => 'Нәве',
	'window-article-menu-cancel-label' => 'Ләғв кардеј',
	'alert-download-updated-wikis-button-ok' => 'OK',
);

/** Ukrainian (українська)
 * @author Andriykopanytsia
 * @author Base
 * @author Steve.rusyn
 * @author SteveR
 */
$messages['uk'] = array(
	'activityindicator-message' => 'Завантаження…',
	'window-wikis-title' => 'Посібники ігор Вікія',
	'window-wikis-wikilist-search-hint' => 'Пошук найпопулярніших ігор…',
	'window-category-load-batch' => 'Більше',
	'window-article-button-close' => 'Закрити',
	'window-article-button-back' => 'Назад',
	'window-article-menu-search-label' => 'Пошук',
	'window-article-menu-dashboard-label' => 'Вміст посібника',
	'window-article-menu-cancel-label' => 'Скасувати',
	'searchview-no-results' => 'Нічого не знайдено для "%s"',
	'searchview-button-back-list' => 'Назад до списку',
	'searchview-button-back-article' => 'Назад до статті',
	'searchbar-hint' => 'Пошук  %s ...',
	'alert-download-updated-wikis-message' => 'Перелік доступних посібників буде оновлено.',
	'alert-download-updated-wikis-button-ok' => 'Гаразд',
	'error-update-required' => 'Оновлення для цієї програми доступне і необхідне.',
	'error-no-connection' => 'Немає підключення до Інтернету.\\пбудь ласка спробуйте ще раз.',
	'error-server' => 'Наші сервери відповіли: помилка, вибачте. \\nСпробуйте ще раз.',
	'error-json-parse' => 'Виникла проблема з даними, які повертаються з наших серверів, вибачте. \\nБудь ласка, спробуйте ще раз.',
);

/** Simplified Chinese (中文（简体）‎)
 * @author Dimension
 * @author Hydra
 * @author Reasno
 * @author Sam Wang
 */
$messages['zh-hans'] = array(
	'activityindicator-message' => '载入中……',
	'window-wikis-title' => 'Wikia 游戏指南',
	'window-wikis-wikilist-search-hint' => '搜索我们的顶部游戏⋯',
	'window-category-load-batch' => '更多',
	'window-article-button-close' => '关闭',
	'window-article-button-back' => '返回',
	'window-article-menu-search-label' => '查找',
	'window-article-menu-dashboard-label' => '指南内容',
	'window-article-menu-cancel-label' => '取消',
	'searchview-no-results' => '"%s"没有结果',
	'searchview-button-back-list' => '返回到列表',
	'searchview-button-back-article' => '返回条目',
	'searchbar-hint' => '搜索 %s ⋯',
	'alert-download-updated-wikis-button-ok' => '确认',
);

/** Traditional Chinese (中文（繁體）‎)
 * @author Ffaarr
 */
$messages['zh-hant'] = array(
	'window-article-button-close' => '關閉',
);
