ALTER TABLE page MODIFY COLUMN page_restrictions TINYBLOB DEFAULT NULL;
ALTER TABLE page MODIFY COLUMN page_random DOUBLE UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE page MODIFY COLUMN page_latest INT(8) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE page MODIFY COLUMN page_len INT(8) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE revision MODIFY COLUMN rev_text_id INT(8) UNSIGNED NOT NULL DEFAULT 0;