mysql %1 --user=%2 --password=%3 < "1 - Remove old versioning columns.sql"
mysql %1 --user=%2 --password=%3 < "2 - Create new versioning.sql"
mysql %1 --user=%2 --password=%3 < "3 - Create new versioning.sql"
mysql %1 --user=%2 --password=%3 < "4 - Add source id column.sql"
mysql %1 --user=%2 --password=%3 < "5 - Create new versioning.sql"
mysql %1 --user=%2 --password=%3 < "6 - Remove set_id from uw_alt_meaningtexts.sql"
mysql %1 --user=%2 --password=%3 < "7 - Objects.sql"
mysql %1 --user=%2 --password=%3 < "8 - Move class membership to separate table.sql"
mysql %1 --user=%2 --password=%3 < "9 - Add UUIDs to objects.sql"
mysql %1 --user=%2 --password=%3 < "10 - Add database script log.sql"
mysql %1 --user=%2 --password=%3 < "11 - Add DefinedMeaning namespace.sql"
mysql %1 --user=%2 --password=%3 < "12 - Add defined meaning pages.sql"
mysql %1 --user=%2 --password=%3 < "13 - Add Object IDs to relations.sql"
mysql %1 --user=%2 --password=%3 < "14 - Add Object IDs to class membership.sql"
mysql %1 --user=%2 --password=%3 < "15 - Add Object IDs to syntrans.sql"
mysql %1 --user=%2 --password=%3 < "16 - Update source_id column in uw_alt_meaningtexts.sql"
mysql %1 --user=%2 --password=%3 < "17 - Remove unused tables and columns.sql"
mysql %1 --user=%2 --password=%3 < "18 - Database changes to use text attributes on objects.sql"
mysql %1 --user=%2 --password=%3 < "19 - Different types of attributes on objects.sql"
mysql %1 --user=%2 --password=%3 < "20 - Add Object IDs to translated content attribute values.sql"
mysql %1 --user=%2 --password=%3 < "21 - Add class attributes.sql"
mysql %1 --user=%2 --password=%3 < "22 - Add level to class attributes.sql"
mysql %1 --user=%2 --password=%3 < "24 - Add language ID indices.sql"
mysql %1 --user=%2 --password=%3 < "25 - Add attribute typing.sql"
mysql %1 --user=%2 --password=%3 < "27 - Create Wikidata Sets.sql"
mysql %1 --user=%2 --password=%3 < "28 - Table reorg.sql"
mysql %1 --user=%2 --password=%3 < "30 - Change table engine.sql"
mysql %1 --user=%2 --password=%3 < "31 - rename fallback column.sql"
mysql %1 --user=%2 --password=%3 < "32 - rename user group.sql"
mysql %1 --user=%2 --password=%3 < "33 - default values.sql"
