<?php

class SpecialPortabilityDashboardController extends WikiaSpecialPageController {
	const SPECIAL_INSIGHTS_PATH = '/wiki/Special:Insights/';
	const SPECIAL_INSIGHTS_TYPELESS_TEMPLATE_PAGE = 'templateswithouttype';
	const SPECIAL_CUSTOM_INFOBOXES_PAGE = 'nonportableinfoboxes';


	public function __construct() {
		parent::__construct( 'PortabilityDashboard', 'pidash', true );
	}

	public function index() {
		$model = new PortabilityDashboardModel();

		Wikia::addAssetsToOutput( 'special_portability_dashboard_scss' );

		// template model 
		$this->response->setVal( 'list', $model->getList() );

		// template helpers
		$this->response->setVal(
			'typelessTemplatesInsightsPath', self::SPECIAL_INSIGHTS_PATH . self::SPECIAL_INSIGHTS_TYPELESS_TEMPLATE_PAGE
		);
		$this->response->setVal(
			'customInfoboxesInsightsPath', self::SPECIAL_INSIGHTS_PATH . self::SPECIAL_CUSTOM_INFOBOXES_PAGE
		);

		// i18n template strings
		$this->response->setVal( 'dashboardLegend', 'Hover over table column headers to get more context.' );
		$this->response->setVal( 'dashboardLabels', [
			[
				'name' => 'Community',
				'description' => 'Link to Community main page.'
			],
			[
				'name' => 'Language',
				'description' => 'This Community language.'
			],
			[
				'name' => 'Portability',
				'description' => 'Absolute portability in %.'
			],
			[
				'name' => 'Infobox Portability',
				'description' => '% of portable infoboxes.'
			],
			[
				'name' => 'Traffic',
				'description' => '% of overall Wikia traffic generated by this Community.'
			],
			[
				'name' => 'Unorganized Templates',
				'description' => 'Number of unorganized templates on this Community.'
			],
			[
				'name' => 'Non-portable Infoboxes',
				'description' => 'number of non-portable infoboxes on this Community'
			],
			[
				'name' => 'Migration Impact',
				'description' => 'Migration Impact'
			],
		]);

		$this->response->setTemplateEngine( WikiaResponse::TEMPLATE_ENGINE_MUSTACHE );
	}
}
