FROM artifactory.wikia-inc.com/sus/php-wikia-base:8a16e38

ENV WIKIA_DATACENTER="sjc"
ENV WIKIA_ENVIRONMENT="sandbox"
ENV HOSTNAME_OVERRIDE="sandbox-sus2"

ADD app /usr/wikia/slot1/current/src
ADD config /usr/wikia/slot1/current/config

RUN mkdir -p /usr/wikia/slot1/current/cache/messages && \
    chmod 777 /usr/wikia/slot1/current/cache/messages && \
    SERVER_ID=177 php maintenance/rebuildLocalisationCache.php --threads=4

USER nobody
