FROM artifactory.wikia-inc.com/sus/php-wikia-base:372bb48

ENV WIKIA_DATACENTER="${SANDBOX_DATACENTER}"
ENV WIKIA_ENVIRONMENT="${SANDBOX_ENVIRONMENT}"
ENV HOSTNAME_OVERRIDE="${SANDBOX_NAME}"

ADD app /usr/wikia/slot1/current/src
ADD config /usr/wikia/slot1/current/config

RUN mkdir -p /usr/wikia/slot1/current/cache/messages && \
    chmod 777 /usr/wikia/slot1/current/cache/messages && \
    SERVER_ID=177 php maintenance/rebuildLocalisationCache.php --threads=32

USER nobody
