FROM artifactory.wikia-inc.com/sus/php-wikia-base:latest

ENV WIKIA_DATACENTER="sjc"
ENV WIKIA_ENVIRONMENT="sandbox"
ENV HOSTNAME_OVERRIDE="sandbox-sus2"

ADD app /usr/wikia/slot1/current/src
ADD config /usr/wikia/slot1/current/config
ADD cache /usr/wikia/slot1/current/cache/messages

RUN SERVER_ID=177 php /usr/wikia/slot1/current/src/maintenance/rebuildLocalisationCache.php --primary

USER nobody