<?php

/**
 * Class MimeMagicCached
 *
 * A replacement for MimeMagic's mMediaTypes array.  Constructing a new MimeMagic instance
 * is heavy, requiring a few files to be read in, cleaned up and parsed.  This class
 * initializes the media types in PHP which is much faster to read in.
 *
 * This class should not extend MimeMagic until the __construct method is overridden.  Without
 * doing this the speed benefit of modules using this module to get MediaTypes would be nullified
 *
 * @author Garth Webb <garth@wikia-inc.com>
 */
class MimeMagicLite {

	var $mMediaTypes = [
			'AUDIO' => [
				"audio/midi",
				"audio/x-aiff",
				"audio/x-wav",
				"audio/mp3",
				"audio/mpeg",
				"audio/mpeg",
				"audio/mp3",
				"audio/mpeg3",
				"audio/wav",
				"audio/x-wav",
				"audio/wave",
				"audio/midi",
				"audio/mid",
				"audio/basic",
				"audio/ogg",
				"audio/x-aiff",
				"audio/x-pn-realaudio",
				"audio/x-realaudio",
				"audio/webm",
				"audio/x-matroska",
			],

			'VIDEO' => [
				"video/ogg",
				"video/mpeg",
				"video/mpeg",
				"application/mpeg",
				"video/ogg",
				"video/x-sgi-video",
				"video/x-flv",
				"video/webm",
				"video/x-matroska",
			],

			'OFFICE' => [
				'application/pdf','application/vnd.oasis.opendocument.chart',
				'application/vnd.oasis.opendocument.chart-template',
				'application/vnd.oasis.opendocument.database',
				'application/vnd.oasis.opendocument.formula',
				'application/vnd.oasis.opendocument.formula-template',
				'application/vnd.oasis.opendocument.graphics',
				'application/vnd.oasis.opendocument.graphics-template',
				'application/vnd.oasis.opendocument.image',
				'application/vnd.oasis.opendocument.image-template',
				'application/vnd.oasis.opendocument.presentation',
				'application/vnd.oasis.opendocument.presentation-template',
				'application/vnd.oasis.opendocument.spreadsheet',
				'application/vnd.oasis.opendocument.spreadsheet-template',
				'application/vnd.oasis.opendocument.text',
				'application/vnd.oasis.opendocument.text-template',
				'application/vnd.oasis.opendocument.text-master',
				'application/vnd.oasis.opendocument.text-web',
				'application/pdf',
				'application/acrobat',
				'application/msword',
				'application/vnd.ms-excel',
				'application/vnd.ms-powerpoint',
				'application/x-director',
				'text/rtf',
				'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
				'application/vnd.openxmlformats-officedocument.wordprocessingml.template',
				'application/vnd.ms-word.document.macroenabled.12',
				'application/vnd.ms-word.template.macroenabled.12',
				'application/vnd.openxmlformats-officedocument.presentationml.template',
				'application/vnd.openxmlformats-officedocument.presentationml.slideshow',
				'application/vnd.openxmlformats-officedocument.presentationml.presentation',
				'application/vnd.ms-powerpoint.addin.macroenabled.12',
				'application/vnd.ms-powerpoint.presentation.macroenabled.12',
				'application/vnd.ms-powerpoint.presentation.macroenabled.12',
				'application/vnd.ms-powerpoint.slideshow.macroenabled.12',
				'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
				'application/vnd.openxmlformats-officedocument.spreadsheetml.template',
				'application/vnd.ms-excel.sheet.macroenabled.12',
				'application/vnd.ms-excel.template.macroenabled.12',
				'application/vnd.ms-excel.addin.macroenabled.12',
				'application/vnd.ms-excel.sheet.binary.macroenabled.12',
			],

			'EXECUTABLE' => [
				'text/javascript',
				'application/x-javascript',
				'text/javascript',
				'application/x-javascript',
				'application/x-ecmascript',
				'text/ecmascript',
				'application/x-bash',
				'application/x-sh',
				'application/x-csh',
				'application/x-tcsh',
				'application/x-tcl',
				'application/x-perl',
				'application/x-python',
			],

			'MULTIMEDIA' => [
				'application/x-shockwave-flash',
				'application/ogg',
				'audio/ogg',
				'video/ogg',
				'application/ogg',
				'application/x-ogg',
				'audio/ogg',
				'audio/x-ogg',
				'video/ogg',
				'video/x-ogg',
				'application/x-shockwave-flash',
				'audio/x-pn-realaudio-plugin',
				'model/iges',
				'model/mesh',
				'model/vrml',
				'video/quicktime',
				'video/x-msvideo',
			],

			'BITMAP' => [
				'image/x-bmp',
				'image/x-ms-bmp',
				'image/bmp',
				'image/gif',
				'image/jpeg',
				'image/png',
				'image/tiff',
				'image/vnd.djvu',
				'image/x-xcf',
				'image/x-portable-pixmap',
				'image/gif',
				'image/png',
				'image/x-png',
				'image/ief',
				'image/jpeg',
				'image/jp2',
				'image/xbm',
				'image/tiff',
				'image/x-icon',
				'image/x-ico',
				'image/x-rgb',
				'image/x-portable-pixmap',
				'image/x-portable-graymap',
				'image/x-portable-greymap',
				'image/x-bmp',
				'image/x-ms-bmp',
				'image/bmp',
				'application/x-bmp',
				'application/bmp',
				'image/x-photoshop',
				'image/psd',
				'image/x-psd',
				'image/photoshop',
				'image/vnd.adobe.photoshop',
				'image/vnd.djvu',
				'image/x.djvu',
				'image/x-djvu',
				'image/webp',
				],

			'DRAWING' => [
				'image/svg+xml',
				'image/svg+xml',
				'application/svg+xml',
				'application/svg',
				'image/svg',
				'application/postscript',
				'application/x-latex',
				'application/x-tex',
				'application/x-dia-diagram',
				'application/acad',
				'application/x-acad',
				'application/autocad_dwg',
				'image/x-dwg',
				'application/dwg',
				'application/x-dwg',
				'application/x-autocad',
				'image/vnd.dwg',
				'drawing/dwg',
			],

			'TEXT' => [
				'text/plain',
				'text/html',
				'text/plain',
				'text/html',
				'application/xhtml+xml',
				'application/xml',
				'text/xml',
				'text',
			],

			'ARCHIVE' => [
				'application/zip',
				'application/x-zip',
				'application/x-gzip',
				'application/x-bzip',
				'application/x-tar',
				'application/x-stuffit',
				'application/x-opc+zip',
			],
			'UNKNOWN' => [
				'unknown/unknown',
				'application/octet-stream',
				'application/x-empty',
			],
	];
}
