document.write("<script type=\"text\/javascript\"><!--");
document.write("google_ad_client = \"ca-pub-7983542246824243\";");
document.write("\/* Passback Xaxis *\/");
document.write("google_ad_slot = \"5385082904\";");
document.write("google_ad_width = 728;");
document.write("google_ad_height = 90;");
document.write("\/\/-->");
document.write("<\/script>");
document.write("<script type=\"text\/javascript\"");
document.write("src=\"\/\/pagead2.googlesyndication.com\/pagead\/show_ads.js\">");
document.write("<\/script>");
