#!/usr/bin/perl

my $wikia_lib;
BEGIN {
	$wikia_lib = "/home/moli/wikia/wikia-utils/lib/"; 
	$YML = "/home/moli/wikia/wikia-conf/DB.localhost.yml";
	if (! -e $wikia_lib) {
		$wikia_lib = "/home/wikicities/conf/mediawiki/wikia-utils/lib" ;
		$YML = undef;
	}
}

=needed modules
=cut
use DBI;
use Cwd;
use Getopt::Long;
use Data::Dumper;

use Date::Manip;
use Switch;
use Spreadsheet::WriteExcel::Big;

use lib $wikia_lib;
use Wikia::Config;
use Wikia::Utils;
use Wikia::DB;
use Wikia::LB;

=default values
=cut
my $email_title = "Top editors";
my $DEF_LIMIT = 1000;
my $DEF_MONTHS = 12;
my $XLS_FILE = "/home/reports/top_editors/top_editors_" . substr (&ParseDate("today"), 0, 8) . ".xls";

=list of namespaces 
=cut
use constant NS_BLOG_ARTICLE => "500";
use constant NS_BLOG_ARTICLE_TALK => "501";
use constant NS_BLOG_LISTING => "502";
use constant NS_BLOG_LISTING_TALK => "503";
use constant NS_VIDEO => "400";
use constant NS_VIDEO_TALK => "401";
use constant NS_MAIN => "0";
use constant NS_IMAGE => "6";

=help function
=cut
sub usage() {
    print <<EOF
video_blog_usage [--help] [--usedb=s] 
	help - print this text
	months - number of month to check (default 1 (last month))
	limit - limit of users
	TASKID - identifier of job
EOF
;	
}

=info
========================================
Main program 
========================================
=cut

=read script args 
=cut
my ($help, $months, $limit, $TASKID) = @_;
GetOptions('help' => \$help, 'months=s' => \$months, 'limit=s' => \$limit, 'TASKID=s' => \$TASKID);

my @ltime = localtime;

=checking args
=cut
if ($help) {
	&usage();
	exit;
} elsif (!$TASKID) {
	print STDERR "Use option --help to know how to use script \n";
	exit;
}

=config -> set logfile 
=cut
my $lb = Wikia::LB->new( {yml => $YML } );

=config -> set logfile 
=cut
my $oConf = new Wikia::Config( {logfile => "/tmp/top_editors.log"} );

=db archive connection
=cut
my $db_ext = new Wikia::DB( {"dbh" => $lb->getConnection( Wikia::LB::DB_SLAVE, undef, Wikia::LB::DATAWARESHARED )} );

=wikia utils 
=cut
my $oUtils = new Wikia::Utils();

=db slave connection
=cut
my $db = new Wikia::DB( {"dbh" => $lb->getConnection( Wikia::LB::DB_SLAVE, 'stats', Wikia::LB::EXTERNALSHARED )} );

$limit = $DEF_LIMIT unless $limit;
$months = $DEF_MONTHS unless $months;

=get task info
=cut
$oConf->log("\n\nTask ID: $TASKID started");

=get task info
=cut
$oConf->log("Processing: get task information");
my $task = $db_ext->get_daemon_task($TASKID);
my ($DATA, $DATAALL, $DATAMOST) = ();
=foreach wiki generate data 
=cut
my %nspaceNames = (
	NS_BLOG_ARTICLE() => "User_blog",
	NS_BLOG_ARTICLE_TALK() => "User_blog_comment",
	NS_BLOG_LISTING() => "Blog",
	NS_BLOG_LISTING_TALK() => "Blog_talk",
	NS_VIDEO() => "Video",
	NS_VIDEO_TALK() => "Video_talk",
	NS_MAIN() => "Main",
	NS_IMAGE() => "Image",
);

=build dates structure 
=cut
my $dates = $oUtils->get_dates($months, "month", "now", "$months months ago");
my @dates = ();
if (scalar @$dates) {		
	@dates = map { substr ($_, 0, 6) } @$dates;
}
my $other_wikis = "5, 11, 425, 520, 2719, 5409";

$oConf->log("Processing: select users from local users table");

=old query
my $select = "lu_user_id as user_id, ue_edit_count as cnt";
my $from = "`dataware`.`city_local_users`, dbstats.city_user_edits";
my @where = ( 
	"lu_singlegroup != 'bot'",
	"lu_allgroups not like '%bot%'",
	"lu_wikia_id not in (".$other_wikis.")", 
	"ue_user_id = lu_user_id",
	"ue_edit_namespace = 0",
	"lu_user_name != 'CreateWiki script'",
	"lu_user_name not like '%Bot%'"
);
my @options = (
	"group by 1",
	"ORDER BY cnt desc",
	"LIMIT ". $limit
); 
=cut

=old query again
my $select = "ue_user_id as user_id, ue_edit_count - (select if(isnull(sum(lu_rev_cnt)),0,sum(lu_rev_cnt)) as cnt from `dataware`.`city_local_users` where lu_user_id = ue_user_id and ((lu_singlegroup = 'bot') or (lu_allgroups like '%bot%') or (lu_user_name like '%Bot%') ) ) as cnt";
my $from = "dbstats.city_user_edits, `dataware`.`city_local_users`";
my @where = ( 
	"lu_singlegroup != 'bot'",
	"lu_allgroups not like '%bot%'",
	"lu_wikia_id not in (".$other_wikis.")", 
	"ue_user_id = lu_user_id",
	"ue_edit_namespace = 0",
	"lu_user_name != 'CreateWiki script'",
	"lu_user_name not like '%Bot%'"
);
my @options = (
	"group by 1",
	"ORDER BY cnt desc",
	"LIMIT ". $limit
); 
=cut

my $select = "user_id, sum(edit_count) - (select if(isnull(sum(lu_rev_cnt)),0,sum(lu_rev_cnt)) as cnt from `dataware`.`city_local_users` where lu_user_id = user_id and ( (lu_singlegroup = 'bot') or (lu_allgroups like '%bot%') or (lu_user_name like '%Bot%') or (lu_user_name = 'CreateWiki script') or (lu_user_name like '%Bot%') ) ) as cnt";
my $from = "dataware.user_edits_summary";
my @where = (
	"city_id not in (".$other_wikis.")",
	"edit_ns = 0",
	"user_id > 0"
);
my @options = (
	"group by 1",
	"ORDER BY cnt desc",
	"LIMIT ". $limit
); 

my %USERS = ();
my %TOP_EDITORS = ();
$sth = $db_ext->select_many($select, $from, \@where, \@options);
if ($sth) {
	while(my $values = $sth->fetchrow_hashref()) {
		my $user_name = $db->get_user_by_id($values->{user_id});
		%{$USERS{$values->{user_id}}} = ('all' => $values->{cnt}, 'ns_main' => 0, 'name' => $user_name);
		$TOP_EDITORS{$values->{user_id}} = $values->{cnt};
	}
	$sth->finish();
}

my %USERS_WIKIS = ();
foreach my $user_id (sort keys %USERS) {
	$select = "lu_wikia_id as city_id, count(*) as cnt";
	$from = "`dataware`.`city_local_users`";
	@where = ( "lu_user_id = " . $db_ext->handler->quote($user_id) , "lu_wikia_id not in (".$other_wikis.")" );
	@options = ( "GROUP BY lu_wikia_id", "ORDER BY cnt desc, lu_wikia_id" );
	$sth = $db_ext->select_many($select, $from, \@where, \@options);
	if ($sth) {
		while(my $values = $sth->fetchrow_hashref()) {
			$USERS_WIKIS{$user_id} = () unless $USERS_WIKIS{$user_id};
			push @{$USERS_WIKIS{$user_id}}, $values->{city_id};
		}
		$sth->finish();
	}
}

=get all Wikis
=cut
my @where_db = ("city_public = 1");
my $databases = $db->get_wikis(\@where_db);
my $hubs = $db->getWikiCats();

my %databaseNames = ();
foreach my $city_id (keys %$databases) {
	$databaseNames{$databases->{$city_id}} = $city_id;
}

my $loop = 0;
foreach my $user_id (sort keys %USERS) {
	#--- set start time
	my $start_sec = time();
	$loop++;
	$oConf->log($USERS{$user_id}{name} . " (".$user_id.") processed (".$loop.")");
	
=get home Wiki for user
=cut
	$select = "lu_wikia_id, max(lu_rev_cnt)"; 
	$from = "`dataware`.`city_local_users`";
	@where = ("lu_user_id = ". $db_ext->handler->quote($user_id) );	
	@options = ("group by 1", "order by 2 desc", "limit 1");
	my ($oRow) = $db_ext->select($select, $from, \@where, \@options);
	my $homeCity = $oRow->{lu_wikia_id};

=get number of edits in main namespace
	$select = "sum(ue_edit_count) as cnt";
	$from = "`dbstats`.`city_user_edits`";
	@where = ("ue_edit_namespace = 0", "ue_user_id = ".$user_id);	
	@options = ();
	($oRow) = $db_ext->select($select, $from, \@where, \@options);
	$USERS{$user_id}{ns_main} = $oRow->{cnt};
=cut
	$USERS{$user_id}{ns_main} = 0 unless ($USERS{$user_id}{ns_main});
	
=get list of wikis, where user edited something
=cut
	my @wikis = @{$USERS_WIKIS{$user_id}};

=processing for every Wiki
=cut
	$oConf->log("Selected list of Wikis for selected users (" .scalar(@wikis). ")");
	foreach (@wikis) {
		my $city_id = $_;
		my $dbname = $databases->{$city_id};
		
		next unless $dbname;
		
		$db_ext->ping();
		$homeCity = $city_id unless ($homeCity);

		$db_ext->handler->ping();
		$oConf->log("processing Wiki: ".$dbname);

		my $contentNS = $db->getContentNS($city_id);
		$contentNS = 0 unless $contentNS;

		#
		# count all in content namespace
		my $db_local = new Wikia::DB( {"dbh" => $lb->getConnection( Wikia::LB::DB_SLAVE, 'stats', $databases->{$city_id} )} );
		$db_local->check_lag();
		$select = "count(*) as cnt";
		$from = "revision";
		@where = (
			"rev_user = '".$user_id."'",
			"rev_page in (select page_id from page where page_is_redirect = 0 and page_namespace in (".$contentNS."))"
		);
		@options = ();
		my ($oRowCnt) = $db_local->select($select, $from, \@where, \@options);
		$USERS{$user_id}{ns_main} += $oRowCnt->{cnt};
		
		foreach (@dates) {
			my $date = $_;
			#$oConf->log("Get revision for date " . $date);
			$USERS{$user_id}{$date} = 0 unless $USERS{$user_id}{$date};

			$db->handler->ping();
			#
			# count all in content namespace and for date
			$select = "count(*) as cnt";
			$from = "revision";
			@where = (
				"rev_user = '".$user_id."'",
				"rev_page in (select page_id from page where page_is_redirect = 0 and page_namespace in (".$contentNS."))",
				"date_format(rev_timestamp, '%Y%m') = '".$date."'"
			);
			@options = ();
			$cnt = 0;
			($oRowCnt) = $db_local->select($select, $from, \@where, \@options);
			$cnt = $oRowCnt->{cnt};
			$cnt = 0 unless $cnt;
			$USERS{$user_id}{$date} = $USERS{$user_id}{$date} + $cnt;
		}
		
		$db_local->disconnect() if ($db_local);
		undef $db_local ;
	}
=end of main loop
=cut
	$USERS{$user_id}{home} = $databases->{$homeCity};
	$USERS{$user_id}{hub} = $hubs->{$homeCity};

	my $end_sec = time();
	my @ts = gmtime($end_sec - $start_sec);

	$oConf->log($user_id . " processed ".sprintf ("%d hours %d minutes %d seconds",@ts[2,1,0]) . "\n\n");
}

=checking results
=cut
$oConf->log("checking results and build XLS file");
my $res = ();

if (! scalar keys %USERS) {
	$oConf->log("No data found for parameters");
	exit;
}

=XLS - default settings ========================
=init XLS spreadsheet
=cut
my $dir = "/home/reports/top_editors/";
mkdir($dir) if (!(-e $dir)) ;
unlink ($XLS_FILE);


my $workbook = Spreadsheet::WriteExcel::Big->new($XLS_FILE);
my @cols = (A..Z, AA..AZ);
my $formatHdr = $workbook->add_format( bold => 1, color => 'black', align => 'center');
my $formatBody = $workbook->add_format( bold => 0, color => 'black', valign => 'vcenter', align => 'right');

=create XLS sheet with data
=cut
my $sheet = $workbook->add_worksheet('Top editors');
$sheet->activate();
my ($col, $row) = (0, 2); 
$sheet->write($row, $col, "Editor", $formatHdr); 
$sheet->write($row, $col+1, "Editor ID", $formatHdr); 
$sheet->write($row, $col+2, "Total edits (content NS)", $formatHdr); 
$sheet->write($row, $col+3, "Home wiki", $formatHdr); 
$sheet->write($row, $col+4, "Hub", $formatHdr); 
my $i = 5;
foreach (@dates) {
	$sheet->write($row, $col+$i, $_, $formatHdr); 
	$i++;
}

foreach my $user_id (sort { $TOP_EDITORS{$b} <=> $TOP_EDITORS{$a} } keys %TOP_EDITORS) {
	$i = 0; $row++;
	$sheet->write($row, $col+$i, $USERS{$user_id}{name}, $formatBody); $i++;
	$sheet->write($row, $col+$i, $user_id, $formatBody); $i++;
	$sheet->write($row, $col+$i, $USERS{$user_id}{ns_main}, $formatBody); $i++;
	$sheet->write($row, $col+$i, $USERS{$user_id}{home}, $formatBody); $i++;
	$sheet->write($row, $col+$i, $USERS{$user_id}{hub}, $formatBody); $i++;
	foreach (@dates) {
		$sheet->write($row, $col+$i, $USERS{$user_id}{$_}, $formatBody);$i++;
	}
}
=close XLS file
=cut
$workbook->close();
$db_ext->disconnect() if ($db_ext);
=finish
=cut
system("gzip -c $XLS_FILE > $XLS_FILE.gz") if ( -e $XLS_FILE );
%update = ("-dj_result_file" => "concat_ws(',', dj_result_file, '".$XLS_FILE.".gz')");
$oConf->log("update task info in database (subdomains)");
$db_ext = new Wikia::DB( {"dbh" => $lb->getConnection( Wikia::LB::DB_MASTER, undef, Wikia::LB::DATAWARESHARED )} );
$q_up = $db_ext->update_daemon_task( \%update, $TASKID );
if ( $q_up ) {
	$oConf->log("send emails with report");
	$oUtils->send_file( $email_title, $task->{dj_result_emails}, $XLS_FILE . ".gz" );
}
$oConf->log("process done");
$db_ext->disconnect() if ($db_ext);

1;
