FROM nginx:1.15.6-alpine

RUN chown -R nginx:nginx /etc/nginx && \
    chown nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /var/log/nginx && \
    mkdir /var/run/nginx && \
    chown nginx:nginx /var/run/nginx

ADD docker/base/base.inc /etc/nginx/conf.d/base.inc
ADD docker/base/nginx.conf /etc/nginx/nginx.conf
ADD docker/prod/site.conf.template /etc/nginx/conf.d/site.conf.template

# static mediawiki files
ADD apple-touch-icon.png /usr/wikia/slot1/current/src/apple-touch-icon.png

ADD skins /usr/wikia/slot1/current/src/skins
ADD resources /usr/wikia/slot1/current/src/resources
ADD extensions /usr/wikia/slot1/current/src/extensions


ADD ./nginx_wrapper.sh /nginx_wrapper.sh
RUN chown -R nginx:nginx /nginx_wrapper.sh

USER nginx

# default read timeout, will be different for tasks
ENV FASTCGI_READ_TIMEOUT 180s


CMD /nginx_wrapper.sh