FROM artifactory.wikia-inc.com/sus/php-wikia-base:e65afb8d20b625dd17e27a672560cfe80

ENV WIKIA_DATACENTER="sjc"
ENV WIKIA_ENVIRONMENT="prod"

ADD app /usr/wikia/slot1/current/src
ADD config /usr/wikia/slot1/current/config

RUN mkdir -p /usr/wikia/slot1/current/cache/messages && \
    chmod 777 /usr/wikia/slot1/current/cache/messages && \
    SERVER_ID=177 php maintenance/rebuildLocalisationCache.php --threads=4

USER nobody
