# This is a base nginx image with Wikia's directory structure
FROM nginx:1.15.6-alpine
RUN chown -R nginx:nginx /etc/nginx && \
    chown nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /var/log/nginx && \
    mkdir /var/run/nginx && \
    chown nginx:nginx /var/run/nginx
COPY ./nginx_wrapper.sh /nginx_wrapper.sh
RUN chown -R nginx:nginx /nginx_wrapper.sh

CMD /nginx_wrapper.sh
USER nginx
