#!/bin/bash

if [ "X$3" == "X" ];then
	echo "Usage: finish <lang> <edition> <checkpoint>"
	exit
fi

. `dirname $0`/config.sh

bindir=$base/scripts
lang=$1
edition=$2
checkpoint=$3
site=wikipedia
langdir=$base/new/$site/$lang

if [ -e $langdir/compressed ]; then
	echo "Already compressed $lang"
	echo "everything=done" > $checkpoint
	exit
fi
if [ ! -e $langdir/index.html ]; then
	echo "$lang directory is broken, missing index.html, skipping."
	exit
fi

date > $langdir/compressed

echo "$lang: Compressing HTML..."
$bindir/compress-html $lang $edition "$checkpoint"
#echo "$lang: Making image tarball..."
#ssh albert tar -C /mnt/static -cf /a/upload_snapshot/$edition/downloads/wikipedia-$lang-images.tar -h $lang/upload
#ln -sf /mnt/upload_snapshot/$edition/downloads/wikipedia-$lang-images.tar /mnt/static/downloads/$edition/$lang/wikipedia-$lang-images.tar
echo "$lang: Done."
