#!/bin/bash

if [ -z $1 ];then
	echo "Usage: start-lang <lang>"
	exit 1
fi

lang=$1
shift
dest=/mnt/static/wikipedia/$lang-new

if [ ! -d $dest ];then
	mkdir -p $dest
	#rm -rf /mnt/upload3/wikipedia/$lang/shared
	ln -s /home/wikipedia/htdocs/wikipedia.org/images $dest/images
	
	# Upload snapshot disabled, not enough space
	#[ -d /mnt/upload_snapshot/new/$lang ] || mkdir -p /mnt/upload_snapshot/new/$lang
	#ln -s /mnt/upload_snapshot/new/$lang $dest/upload
	
	mkdir $dest/upload
	ln -s /mnt/upload3/wikipedia/$lang/* $dest/upload/
	rm -f $dest/upload/shared
	mkdir $dest/upload/shared
	ln -s /home/wikipedia/common/php-1.5/skins $dest/skins
	cp /mnt/static/COPYING.html $dest/COPYING.html
fi
