#!/bin/bash

. `dirname $0`/config.sh

if [ -z $base ]; then 
	echo "No base directory"
	exit; 
fi

rm -rf $base/var/checkpoints
mkdir $base/var/checkpoints
rm -rf $base/var/jobs
mkdir $base/var/jobs
rm -rf $base/var/logs
mkdir $base/var/logs

