 CREATE TABLE /*$wgDBprefix*/city_list (
  `city_id` int(9) NOT NULL auto_increment,
  `city_path` varchar(255) NOT NULL default '/dev/null',
  `city_dbname` varchar(64) NOT NULL default 'notreal',
  `city_sitename` varchar(255) NOT NULL default 'wikicities',
  `city_url` varchar(255) NOT NULL default 'http://notreal.wikicities.com/',
  `city_created` datetime default NULL,
  `city_founding_user` int(5) default NULL,
  `city_adult` tinyint(1) default '0',
  `city_public` int(1) NOT NULL default '1',
  `city_additional` text,
  `city_description` text,
  `city_title` varchar(255) default NULL,
  `city_founding_email` varchar(255) default NULL,
  `city_lang` varchar(8) NOT NULL default 'en',
  `city_special_config` text,
  `city_umbrella` varchar(255) default NULL,
  `city_ip` varchar(256) NOT NULL default '/usr/wikia/source/wiki',
  `city_google_analytics` varchar(100) default '',
  `city_google_search` varchar(100) default '',
  `city_google_maps` varchar(100) default '',
  `city_indexed_rev` int(8) unsigned NOT NULL default '1',
  `city_lastdump_timestamp` varchar(14) default '19700101000000',
  `city_factory_timestamp` varchar(14) default '19700101000000',
  `city_useshared` tinyint(1) default '1',
  `ad_cat` char(4) NOT NULL default '',
  `city_flags` int(10) unsigned NOT NULL default '0',
  `city_cluster` varchar(255) default NULL,
  `city_last_timestamp` timestamp NOT NULL default CURRENT_TIMESTAMP,
  PRIMARY KEY  (`city_id`),
  KEY `city_dbname_idx` (`city_dbname`),
  KEY `titleidx` (`city_title`),
  KEY `urlidx` (`city_url`),
  KEY `city_flags` (`city_flags`)
) ENGINE=InnoDB;
