# This is a base Docker image used in prod/sandbox/preview Jenkinsfile
FROM artifactory.wikia-inc.com/sus/php-wikia-base:225a68a

# disable the opcache
RUN sed -i 's/zend_extension=/;zend_extension=/g' /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini

RUN apt update && apt install -q -y vim procps less git openssl make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl
ENV LANG="C.UTF-8" \
    LC_ALL="C.UTF-8" \
    PATH="/opt/pyenv/shims:/opt/pyenv/bin:$PATH" \
    PYENV_ROOT="/opt/pyenv" \
    PYENV_SHELL="bash"
RUN git clone --single-branch --depth 1 git://github.com/yyuu/pyenv.git $PYENV_ROOT

# Install needed version, skip if already exists
RUN pyenv install 3.6.4 -s
RUN echo 'eval "$( pyenv init -)"\n' >> ~/.pyenv_profile
RUN dash ~/.pyenv_profile
RUN pyenv local 3.6.4
RUN pip install --upgrade pip

ADD app /usr/wikia/slot1/current/src/app
ADD config /usr/wikia/slot1/current/src/config
ADD rebuild /usr/wikia/slot1/current/src/rebuild

RUN pip install pytest
RUN pip install -r rebuild/requirements.txt

ARG VAULT_TOKEN
RUN echo "cd rebuild &&\n dash ~/.pyenv_profile &&\n   pyenv local 3.6.4  &&\n  export PYTHONWARNINGS="ignore:Unverified HTTPS request" &&\n pytest .    &&\n export WIKIA_ENVIRONMENT=sandbox &&\n SERVER_ID=177 php ../app/maintenance/rebuildLocalisationCache.php --threads=16 --primary   &&\n python ./bin/recreate_wiki.py --env=sjc  --debug --vault-address=https://active.vault.service.sjc.consul:8200 --vault-token=$VAULT_TOKEN --city-dbname=szlmercurycc --app-base-path='../app'   &&\n python bin/clear_fastly_cache.py --env=sjc --vault-address=https://active.vault.service.sjc.consul:8200 --vault-token=$VAULT_TOKEN --app-base-path='../app'" >> run_script
