# This is a base Docker image used in prod/sandbox/preview Jenkinsfile
FROM artifactory.wikia-inc.com/sus/php-wikia-base:225a68a

# disable the opcache
RUN sed -i 's/zend_extension=/;zend_extension=/g' /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini

RUN apt update && apt install -q -y vim procps less git openssl make build-essential libssl-dev zlib1g-dev libbz2-dev libreadline-dev libsqlite3-dev wget curl llvm libncurses5-dev libncursesw5-dev xz-utils tk-dev libffi-dev liblzma-dev python-openssl
RUN curl -L https://raw.githubusercontent.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash
# Set and source vars and init
RUN export PATH="$PYENV_ROOT/bin:$PATH"
RUN echo 'if command -v ~/.pyenv/bin/pyenv 1>/dev/null 2>&1; then\n  eval "$(~/.pyenv/bin/pyenv init -)"\nfi' >> ~/.pyenv_profile
RUN dash ~/.pyenv_profile
# Install needed version, skip if already exists
RUN ~/.pyenv/bin/pyenv install 3.6.4 -s

ADD app /usr/wikia/slot1/current/src/app
ADD config /usr/wikia/slot1/current/src/config
ADD rebuild /usr/wikia/slot1/current/src/rebuild

ARG VAULT_TOKEN
RUN cd rebuild
RUN echo "dash ~/.pyenv_profile \n pyenv local 3.6.4 \n pip install -r requirements.txt \n pytest .  \n export WIKIA_ENVIRONMENT=sandbox \n SERVER_ID=177 php ../app/maintenance/rebuildLocalisationCache.php --threads=16 --primary \n python bin/recreate_wiki.py --env=sjc  --debug --vault-address=https://active.vault.service.sjc.consul:8200 --vault-token=$VAULT_TOKEN --city-dbname=szlmercurycc --app-base-path='../app' \n python bin/clear_fastly_cache.py --env=sjc --vault-address=https://active.vault.service.sjc.consul:8200 --vault-token=$VAULT_TOKEN --app-base-path='../app'" >> run_script
