<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));

return array(
    'd1715cacc3c23b16a030645514266a76' => $vendorDir . '/data-values/interfaces/Interfaces.php',
    '7cb394c3af2b1ae832979b0368e0da62' => $vendorDir . '/data-values/data-values/DataValues.php',
    '90559502573a0d473dc66fde5c0ff7e2' => $vendorDir . '/data-values/common/Common.php',
    '0dd9431cbbfa9ed9cb9d565d7129dbaf' => $vendorDir . '/data-values/validators/Validators.php',
    'af3cc937b8a54e5b4209c82d6cfe8889' => $vendorDir . '/param-processor/param-processor/DefaultConfig.php',
    'ad155f8f1cf0d418fe49e248db8c661b' => $vendorDir . '/react/promise/src/functions_include.php',
    '5a494680c593293bd6035e42e2a6825c' => $vendorDir . '/data-values/geo/Geo.php',
    'c3ae67574219cc56cab6c30ef8877b85' => $baseDir . '/extensions/Validator/Validator.php',
    'f4c767faab43077fd89ff7cf99ffb4b8' => $vendorDir . '/serialization/serialization/Serialization.php',
    '94e265ce14c952a920a4ea5f7e8e9baa' => $vendorDir . '/mediawiki/parser-hooks/ParserHooks.php',
    'bbf73f3db644d3dced353b837903e74c' => $vendorDir . '/php-di/php-di/src/DI/functions.php',
    '9ebf2cbcc0b7687b276c44d77096b002' => $baseDir . '/extensions/Maps/Maps.php',
    '69e0397dea3bf8934eed002abf6b38ef' => $baseDir . '/extensions/SemanticMediaWiki/src/Aliases.php',
    '1e1cb42dd2499e18ea5eab984a9f5c8b' => $baseDir . '/extensions/SemanticMediaWiki/src/Defines.php',
    '81831d7e713e54a40378b62fec6629d5' => $baseDir . '/extensions/SemanticMediaWiki/src/GlobalFunctions.php',
    '0e960e930c32120da8e2ee126b82c67b' => $baseDir . '/extensions/SemanticMediaWiki/DefaultSettings.php',
    'cd9b6b6b76aed1304a64986142337d3a' => $baseDir . '/extensions/SemanticMediaWiki/SemanticMediaWiki.php',
);
