#!/bin/bash
#
# This script is meant to be ran from the directory where you want to 
# install the wiki, for example in /var/www/. You will most likely have
# to run the scirpt with administrator privileges as it requires, among
# other things, writing to system files and restarting apache. It will:
# 	1) wget the MediaWiki source
#	2) extract the source to the provided directory
#	3) check out the UNIWIKI extensions to the extensions directory
#	   of the MediaWiki installation
#	4) patch the installer script to add the default UNIWIKI settings
#	   to the LocalSettings.php file upon installation
#	5) add a virtual host entry to the sites-available and sites-enabled
#          directories (Debian) or httpd.conf file
#	6) reload the apache webserver
# NOTE: This script assumes that you already have the DNS entry set up
#       for the wiki you are installing. Also, it assumes that you have
#       Subversion client installed and in your path. Place this script 
#       somewhere like /usr/local/bin to easily create uniwikis!

# print usage message if not called with correct args
if [ $# -eq 0 ]; then
	echo "Usage: $0 <wiki-name>"
	exit
fi

# info for this installation
INSTALL_DIRNAME=$1
INSTALL_PATH=`pwd`

# mediawiki settingsi
MEDIAWIKI_SRC_URL="http://download.wikimedia.org/mediawiki/1.13/mediawiki-1.13.2.tar.gz"
MEDIAWIKI_TARGZ="mediawiki-1.13.2.tar.gz"
MEDIAWIKI_DIRNAME="mediawiki-1.13.2"
MEDIAWIKI_LINENUM=1741

# uniwiki settings
UNIWIKI_SRC_URL="http://svn.wikimedia.org/svnroot/mediawiki/trunk/extensions/uniwiki"
UNIWIKI_DIRNAME="uniwiki"
UNIWIKI_SETTINGS_FILE="$INSTALL_PATH/$INSTALL_DIRNAME/extensions/$UNIWIKI_DIRNAME/.make-uniwiki-settings"

# apache settings
VHOST_ENTRY="\n\n
# This virtual host entry was automagically added\n
# by $USER using the 'make-uniwiki' script.\n
<VirtualHost *:80>\n
        \tServerName $INSTALL_DIRNAME\n
        \tDocumentRoot $INSTALL_PATH/$INSTALL_DIRNAME\n
	\tOptions FollowSymLinks MultiViews\n
        \t<Directory $INSTALL_PATH/$INSTALL_DIRNAME>\n
                \t\tOptions FollowSymLinks Indexes\n
                \t\tAllowOverride all\n
                \t\tOrder allow,deny\n
                \t\tallow from all\n
        \t</Directory>\n
</VirtualHost>\n
"

# get the MediaWiki src, extract it, and name it accordingly
wget $MEDIAWIKI_SRC_URL
tar -xzf $MEDIAWIKI_TARGZ
rm $MEDIAWIKI_TARGZ
mv $MEDIAWIKI_DIRNAME $INSTALL_DIRNAME

# move to the extensions directory and get the UNIWIKI extensions
cd "$INSTALL_PATH/$INSTALL_DIRNAME/extensions"
svn co $UNIWIKI_SRC_URL $UNIWIKI_DIRNAME

# patch the MediaWiki install script to add the UNIWIKI default settings
cd "$INSTALL_PATH/$INSTALL_DIRNAME/config"
split -l $MEDIAWIKI_LINENUM -a 1 index.php temp
cat tempa $UNIWIKI_SETTINGS_FILE tempb > index.php
rm tempa tempb

# add the virtual host entry and reload the server
if [[ -d /etc/apache2/sites-available ]]; then
        APACHE_CONF_FILE="/etc/apache2/sites-available/$INSTALL_DIRNAME"
	echo -e $VHOST_ENTRY > "/etc/apache2/sites-available/$INSTALL_DIRNAME"
	a2ensite $INSTALL_DIRNAME
	/etc/init.d/apache2 reload
elif [[ -f /etc/httpd/conf/httpd.conf ]]; then
	echo -e $VHOST_ENTRY >> /etc/httpd/conf/httpd.conf
	/etc/rc.d/httpd reload
else
	exit
fi

# set the permissions to www-data
# (and group write, so devs can edit it)
chown -R www-data:www-data "$INSTALL_PATH/$INSTALL_DIRNAME"
chmod -R g+w "$INSTALL_PATH/$INSTALL_DIRNAME"

exit
