/* 
 * 
 * @preserve Copyright(c) 2010-2011 Digital Fulrcum, LLC 
 * (http://digital-fulcrum.com). All rights reserved.
 * License: See license.txt or http://digital-fulcrum.com/ghostwriter-license/ 
 * GhostWriter: http://digital-fulcrum.com/ghostwriter-complete-control
 * Release: 12.4.4 
 */
this["ghostwriter"]=this["ghostwriter"]||function(){var W=this,D=W.document,$Head=D.head||D.getElementsByTagName("HEAD")[0],$ToString="toString",$NativeToString="nativeToString",$Parser,$Dombuilder,$Domelement,$Capabilities,$Queue=[],$Initialized=false,$Running=false,$Debug=W.location.hash.toLowerCase().indexOf("gwrdebug")>=0?true:false,$Noop=new Function,getInserter,$UA=function(ua){var $={ie:false,ie6:false,fx:false};$.ie=/msie/i.test(ua);$.ie6=$.ie&&/msie 6/i.test(ua);$.fx=!$.ie&&/firefox/i.test(ua);
$.opera=!!W.opera;return $}(navigator.userAgent),$Messages=function($){for(var m in $)$[m]=["ghostwriter.js  >> ",$[m],""].join("");return $}({enqueue:"ENQUEUE script",dequeue:"DEQUEUE script",start:"BEGIN ghostload",done:"FINISHED ghostload",attach:"\tattach/execute script",finish:"\tloaded/finished script",handlerError:" !!! ERROR !!!!  Error executing handler ",removed:"Root element no longer in document, will skip pending scripts",demolish:"demolish() called, removing script "});ghostwriter["queue"]=
$Queue;ghostwriter["handlers"]={};ghostwriter["debug"]=debug;ghostwriter["currload"]=$Noop;ghostwriter["getscriptidentifier"]=getscriptidentifier;getInserter=function($){return function(topNode,type){var fn=type in $?$[type]:$.append,failback=topNode.parentNode;return function(childNode){fn(topNode,childNode,failback)}}}({append:function(tgt,el){tgt.appendChild(el)},before:function(tgt,el,p){var p=tgt.parentNode||p;if(!p)return;else if(p!=tgt.parentNode||$UA.ie6&&tgt.nodeType==3&&el.tagName.toLowerCase()==
"script")p.appendChild(el);else p.insertBefore(el,tgt)},after:function(tgt,el){var p=tgt.parentNode,sib=tgt.nextSibling;p.insertBefore(el,sib)}});return ghostwriter;function ghostwriter(element,options){options=options||{};if(!$Initialized)Initialize();if($Running)return Enqueue(element,options);$Running=true;element=getElement(element);var a=[element,options];a["demolish"]=ghostload(element,options);return a}function Initialize(){$Initialized=true;$Parser=ghostwriter["htmlstreamparser"];$Dombuilder=
ghostwriter["domtree"];$Domelement=ghostwriter["domelement"];$Capabilities=ghostwriter["capabilities"];ghostwriter["fh"]["set"]()}function Enqueue(element,options){if($Debug)logScriptActivity($Messages.enqueue,options["script"]);var handle=Array.prototype.slice.call(arguments);$Queue[$Queue.length]=handle;handle["demolish"]=demolish;return handle}function Dequeue(){$Running=false;if($Queue.length<1)return;var args=$Queue.shift();if($Debug)logScriptActivity($Messages.dequeue,args[1]["script"]);ghostwriter.apply(ghostwriter,
args);return $Queue.length}function getElement(element){if(typeof element=="string")element=D.getElementById(element);if(!element)throw new Error("Unable to find element "+element+"\nUsage: ghostwriter(element|elementid, options)");return element}function logScriptActivity(message,script){var id=getscriptidentifier(script);flog([message,id,""].join(' "'))}function debug(y){return y==null?$Debug:$Debug=y}function ghostload(element,options){var insertfn=getInserter(element,options["insertType"]),parser=
new $Parser({chars:parserCharHandler,start:parserTagStartHandler,end:parserTagEndHandler}),oldwrite=D.write,oldwriteln=D.writeln,e=null,curr=makescript(options["script"]),onDone=typeof options["done"]=="function"?options["done"]:$Noop,callHook=createHookCallback(ghostwriter["handlers"]||{},options["handlers"]||{}),tree=new $Dombuilder(insertfn,function(){var args=Array.prototype.slice.call(arguments);args.unshift("onelement");callHook.apply(W,args)}),outstanding=0,loadqueue=[],inserted=false,localAsyncTrigger=
null,demolished=false;if($Debug)logScriptActivity($Messages.start,options["script"]);D.write=write;write[$ToString]=ghostwriter[$NativeToString]("write");D.writeln=writeln;writeln[$ToString]=ghostwriter[$NativeToString]("writeln");callHook("begin",options["script"]);if("tagName"in curr)initializeDomTree(tree,curr);if(inDocument(element))addscript(curr);else if($Debug)flog([$Messages.removed,element,""].join(" '"));inserted=true;if(outstanding<1)finish();return demolish;function writeln(text){parser.parse(text+
"\n")}function write(text){parser.parse(text)}function onload(complete){var synchronous=$Capabilities["synchronous"];outstanding--;if($Debug&&!complete)logScriptActivity($Messages.finish,this);if(!synchronous)removeAsyncTrigger();if(!complete)callHook("finishscript",this);if(demolished)return;else if(loadqueue.length>0)loadNext();else if(!(synchronous||complete))setTrigger();else if(outstanding<1&&inserted)finish();return true}function parserTagEndHandler(tn){if(tn.toLowerCase()=="script")addscript(tree.current.element);
else tree.close(tn)}function parserCharHandler(text){tree.addText(text)}function parserTagStartHandler(tn,alist,unary){tn=tn.toLowerCase();var attrs=attrsToObject(alist);if(!callHook("check",tn,attrs))return false;tree.add(tn,attrs);if(unary)tree.close(tn)}function loadNext(){if(outstanding)return;var nextScript=curr=loadqueue.shift();AddLoadHandler(nextScript,onload);if(!inDocument(element)){if($Debug)flog([$Messages.removed,element,""].join(" '"));return onload.call(nextScript)}callHook("startscript",
nextScript);outstanding++;tree.reset();if($Debug)logScriptActivity($Messages.attach,nextScript);callHook("onelement",nextScript);if(tree.current&&tree.current.element!=nextScript)tree.current.appendChild(nextScript);else insertfn(nextScript)}function setTrigger(){ghostwriter["currload"]=onload;localAsyncTrigger=D.createElement("SCRIPT");localAsyncTrigger.text="ghostwriter.currload(true)";localAsyncTrigger.type="text/javascript";flog("setting local trigger");outstanding++;$Head.appendChild(localAsyncTrigger)}
function removeAsyncTrigger(){localAsyncTrigger&&localAsyncTrigger.parentNode&&localAsyncTrigger.parentNode===$Head&&$Head.removeChild(localAsyncTrigger)}function addscript(s){if(!s)return;else if(s.defer){tree.close();return s}if(outstanding&&s.src){loadqueue[loadqueue.length]=s;tree.close("script",false);return s}else if(typeof s=="function"){s();if($Debug)flog([$Messages.attach,s+"",""].join(" '"));onload.call(s,true);return s}outstanding++;D.write=write;D.writeln=writeln;return runScript(s)}function runScript(scriptElement){var mustEval=
false;if(!inDocument(element)){if($Debug)flog([$Messages.removed,element,""].join(" '"));return onload.call(scriptElement)}if($Debug)logScriptActivity($Messages.attach,scriptElement);callHook("startscript",scriptElement);if(isEmptyScript(scriptElement)){tree.close();outstanding--;return scriptElement}if(!scriptElement.src)mustEval=mutateLocalScript(scriptElement);mustEval||AddLoadHandler(scriptElement,onload);tree.close();mustEval&&evalScript(scriptElement.text,scriptElement.language)&&onload.call(scriptElement);
return scriptElement}function mutateLocalScript(scriptElement){var C=$Capabilities,mustEval=!(C["synchronous"]&&C["localonload"]);if(mustEval){scriptElement.setAttribute("type","text/any");scriptElement.removeAttribute("language")}else if(C["usedatauri"]){scriptElement.setAttribute("src","data:text/javascript,"+encodeURIComponent(scriptElement.text));scriptElement.async=true}return mustEval}function evalScript(scriptCode,type){var geval=W.execScript||eval;try{if(W.execScript&&type)geval(scriptCode,
type);else geval(scriptCode)}finally{return true}}function finish(){D.write=oldwrite;D.writeln=oldwriteln;if($Debug)logScriptActivity($Messages.done,options["script"]);callHook("end",options["script"]);demolished||setTimeout(onDone,0);demolished=true;Dequeue();return true}function demolish(){if($Debug)logScriptActivity($Messages.demolish,curr);curr&&onload.call(curr,true);if(curr.parentNode)curr.parentNode.removeChild(curr)}}function demolish(){for(var i=0,l=$Queue.length;i<l;i++)if($Queue[i]===this){$Queue.splice(i,
1);break}}function isEmptyScript(scriptElement){return!(scriptElement.src||scriptElement.text||scriptElement.textContent)}function initializeDomTree(domTree,scriptElement){var e=new $Domelement("script",{});e.isready=false;e.element=scriptElement;e.parentNode=domTree.current;domTree.current=e}function createHookCallback(global,local){var hooks={begin:[],end:[],onelement:[],check:[],startscript:[],finishscript:[]};Iterator(hooks,function(key,value){typeof global[key]=="function"&&value.push(global[key]);
typeof local[key]=="function"&&value.push(local[key])});return function(type){var handledBy=hooks[type],args=Array.prototype.slice.call(arguments);args.shift();for(var i=0,l=handledBy.length,hookReturn;i<l;i++){try{hookReturn=handledBy[i].apply(W,args)}catch(e){flog([$Messages.handlererror,'handler type: "'+type+"'",'callback funtion: "'+handledBy[i]+'"','exception: "'+e+'"'].join("\n"))}if(hookReturn!=null&&!hookReturn)return hookReturn}return true}}function inDocument(target){while(target){if(target===
D)return true;target=target.parentNode}return false}function Iterator(collection,callback){for(var key in collection)if(collection.hasOwnProperty(key))callback.call(collection,key,collection[key]);return collection}function tweakurl(url){if(url.indexOf("file:")===0)return url.replace("file","http");else if(url.indexOf("//")===0)return"http:"+url;return url}function makescript(sa){if(typeof sa=="function"||typeof sa=="object"&&"nodeType"in sa&&"tagName"in sa&&sa.tagName=="SCRIPT")return sa;var s=D.createElement("SCRIPT");
if(typeof sa=="string")sa={src:sa};for(var a in sa){if(a=="text"||a=="innerText")s.text=sa[a];if(typeof sa[a]!="object")s[a]=sa[a]}return s}function AddLoadHandler(script,cb){if(script.attachEvent){script.attachEvent("onreadystatechange",loadhandler);script.attachEvent("onerror",loadhandler)}else if(script.addEventListener){script.addEventListener("load",loadhandler,false);script.addEventListener("error",loadhandler,false)}else{script.onload=loadhandler;script.onerror=loadhandler}function loadhandler(e){if(e.type==
"error")flog("uh oh ... script "+script.src+" finished shamefully");if(e.type=="readystatechange"&&script.readyState&&script.readyState!="complete"&&script.readyState!="loaded")return;if(script.detachEvent){script.detachEvent("onreadystatechange",arguments.callee);script.detachEvent("onerror",arguments.callee)}else if(script.removeEventListener){script.removeEventListener("load",arguments.callee,false);script.removeEventListener("error",arguments.callee,false)}else script.onload=script.onerror=null;
cb.call(script)}}function getscriptidentifier(script){var scriptText=typeof script=="function"?script+"":script.src?script.src:script.text,scriptId=script.id||"",charCount=40,scriptTextLength=scriptText.length,separator="{...}";scriptId=scriptId?"(#"+scriptId+") ":"";scriptText=scriptText.replace(/\n/g," ");if(scriptTextLength<=charCount+separator.length)return scriptText;return[scriptId,scriptText.substr(0,charCount),separator,scriptText.substr(scriptTextLength-charCount,scriptTextLength-1)].join("")}
function attrsToObject(a_l){var _={};for(var i=0,l=a_l.length,a=a_l[i];i<l;a=a_l[++i]){var n=a.name,v=a.value;_[n]=v}return _}}();window["flog"]=function(){var startTime=new Date;return flog;function flog(msg){var diff=((new Date-startTime)/100).toFixed(1);msg=["#gwr[+",diff,"] ",msg].join("");if(typeof Y=="object"&&typeof Y.log=="function")Y.log(msg);if(typeof console=="object"&&"log"in console)console.log(msg)}}();
ghostwriter["nativeToString"]=function(){var $="function 00() {\n    [native code]\n}".split(0),slice="slice";return function stringMaker(methodName){var _=$[slice]();_[1]=methodName;return function(){return _.join("")}}}();
window["ghostwriter"]["flushloadhandlers"]=window["ghostwriter"]["fh"]=function($W){var Debug=$W["ghostwriter"]["debug"],$D=document,$Split="split",$OverridableElementList=[$W,$D],$EventList,$DispatchEventPrefix="gwrsim",$GlobalOnload=$W.onload,$HaveFlushed=false,$Overridden=false,$resetDoScrollOverride=new Function,$Messages=function($){for(var m in $)$[m]=["loadhandlers.js >> ",$[m],""].join("");return $}({domeventreceived:"Received DOM load event of type ",registerdomevent:"Registering for event of type ",
addedlistener:"Adding new event listener ",callbackerror:"!!ERROR!! Exception thrown running callback function "});$EventList=registerOnloadListeners("DOMContentLoaded0load0readystatechange".split(0),$OverridableElementList);simulateOnload["set"]=setOverrides;simulateOnload["eventlist"]=$EventList;$W.onload=null;return simulateOnload;function simulateOnload(){$resetDoScrollOverride();fireOverrideEvents();$HaveFlushed=true}function setOverrides(){$resetDoScrollOverride=setDoScrollOverride();setDocumentOverrides();
installEventHandlerProxies($EventList);setGlobalOnload();if($Overridden)return false;else{$Overridden=true;return $Overridden}}function setGlobalOnload(){var globalLoad=$W.onload||$GlobalOnload,loadEvent=$D.addEventListener?"load":"onload";$W.onload=$GlobalOnload=null;if(!globalLoad)return;if($W.addEventListener)$W.addEventListener(loadEvent,globalLoad,false);else if($W.attachEvent)$W.attachEvent(loadEvent,globalLoad)}function setDoScrollOverride(){if($Overridden)return $resetDoScrollOverride;var overrideObject,
nativeDoScroll,docElement=$D.documentElement;if(typeof Element=="object"&&typeof Element.prototype=="object"&&Element.prototype.doScroll)overrideObject=Element.prototype;else if(docElement&&docElement.doScroll)overrideObject=$D.documentElement;if(!overrideObject)return new Function("return new Function()");nativeDoScroll=overrideObject.doScroll;overrideObject.doScroll=new Function("throw new Error;");return resetDoScroll;function resetDoScroll(){if(overrideObject==$D.documentElement)$D.documentElement.doScroll=
nativeDoScroll;else overrideObject.doScroll=function(){nativeDoScroll.call(this)}}}function setDocumentOverrides(){var fnList="write0writeln0close0open"[$Split](0),body="flog('Illegal call to document.00(): \"'+ a + '\"')"[$Split](0),toStringMaker=$W["ghostwriter"]["nativeToString"],toString="toString",i=0,name;while(name=fnList[i++]){body[1]=name;fn=new Function("a",body.join(""));$D[name]=fn;fn[toString]=toStringMaker(name)}}function registerOnloadListeners(eventNameList,domObjectList){var $={};
Each(eventNameList,function(eventName){Each(domObjectList,function(domObject){addListener(eventName,domObject)})});return $;function addListener(eventName,domObject){if(Debug())logActivity($Messages.registerdomevent,eventName,domObject);if(domObject.addEventListener){$[eventName]=$[eventName]||{};$[eventName][domObject]={event:null,target:domObject};domObject.addEventListener(eventName,handleReady,false)}if(domObject.attachEvent){eventName="on"+eventName;$[eventName]=$[eventName]||{};$[eventName][domObject]=
{event:null,target:domObject};domObject.attachEvent(eventName,handleReady)}}function handleReady(event){var domObject=event.currentTarget||this,msEvent=!event.target,eventName=msEvent?"on"+event.type:event.type,eventCache=$[eventName][domObject];if(!eventCache)return;if(Debug())logActivity($Messages.domeventreceived,eventName,domObject);eventCache.event=msEvent?copyEventObject(event):event;if(domObject.removeEventListener)domObject.removeEventListener(eventName,handleReady,false);if(domObject.detachEvent&&
!eventName.indexOf("on")==0)domObject.detachEvent(eventName,handleReady);if($HaveFlushed)dispatchEventCache(eventCache,eventName)}function copyEventObject(event){if(document.createEventObject)return document.createEventObject(event);var $={};for(var key in event)$[key]=event[key];return $}}function fireOverrideEvents(){var eventList=$EventList;Iterator(eventList,function(eventType){var domObjectEventList=eventList[eventType];Iterator(domObjectEventList,function(domObject){var eventCache=domObjectEventList[domObject];
if(eventCache.event)dispatchEventCache(eventCache,eventType)})})}function dispatchEventCache(eventCache,actualType){var quirky=actualType.indexOf("on")==0,domTarget=eventCache.target;if(domTarget.dispatchEvent&&!quirky)standardDispatcher.apply(this,arguments);else msiequirkDispatcher.apply(this,arguments)}function standardDispatcher(eventCache){var originalEvent=eventCache.event,domTarget=eventCache.target,customOnloadEvent=$D.createEvent("UIEvents"),fakeEvent=$DispatchEventPrefix+originalEvent.type;
customOnloadEvent.originalEvent=originalEvent;customOnloadEvent.initEvent(fakeEvent,false,false);domTarget.dispatchEvent(customOnloadEvent)}function msiequirkDispatcher(eventCache){var originalEvent=eventCache.event,domTarget=eventCache.target,listeners=eventCache.listeners;if(!listeners)return;while(listener=listeners.shift())try{listener.call(domTarget,originalEvent)}catch(e){logActivity($Messages.callbackerror,listener+"",e.message)}}function installEventHandlerProxies(overrideEventList){if($Overridden)return false;
Each($OverridableElementList,function(domObject){if(domObject.addEventListener)domObject.addEventListener=eventListenerProxyFactory.call(domObject,domObject.addEventListener);if(domObject.attachEvent)domObject.attachEvent=attachEventProxyFactory.call(domObject,domObject.attachEvent)});function eventListenerProxyFactory(method){var eventList=$EventList;return function eventListenerProxy(eventType){var args;if(eventType in eventList){args=[$DispatchEventPrefix+eventType,createEventListener(arguments[1],
eventType),false];if(Debug())logActivity($Messages.addedlistener,eventType,this)}else args=Array.prototype.slice.call(arguments);return Function.prototype.apply.call(method,this,args)}}function attachEventProxyFactory(method){var eventList=$EventList;return function attachEvent(eventType,callback){if(!(eventType in eventList))return Function.prototype.apply.call(method,this,Array.prototype.slice.call(arguments));var eventCache=eventList[eventType][this],listeners=eventCache.listeners=eventCache.listeners||
[];listeners[listeners.length]=callback;return true}}function createEventListener(callback){return function eventListener(event){var dom=event.target,originalEvent=event.originalEvent;if(dom.removeEventListener)dom.removeEventListener(event.type,arguments.callee,false);callback.call(dom,originalEvent)}}}function Each(array,callback){for(var i=0,l=array.length;i<l;i++)callback.call(array,array[i]);return array}function Iterator(collection,callback){for(var key in collection)if(collection.hasOwnProperty(key))callback.call(collection,
key,collection[key]);return collection}function logActivity(message,type,target){flog([message,' "',type,'" / "',target.toString(),'"'].join(""))}}(this);
window["ghostwriter"]["domtree"]=function(){var IGNORE={html:false,head:false,body:false,noscript:true,noembed:true,title:true,meta:true},ghostwriter=window["ghostwriter"],ELEMENT;function appendToBody(element){document.body.appendChild(element)}function domtree(insertFn,onadd){ELEMENT=ELEMENT||ghostwriter["domelement"];var _self=this;this.inserter=typeof insertFn=="function"?insertFn:appendToBody;this.addhandler=onadd||new Function;this.current={tagName:null,appendChild:function(element){_self.inserter(element);
return this},close:function(){return this},parentNode:null,ready:function(){return true}};this.current.parentNode=this.current;this.previous=null;this.ignoring=0}domtree.prototype={addText:function(text){var tag=ELEMENT("",text);if(!this.ignoring&&text!=="\n"&&text!=="\r\n")this.current.appendChild(tag.element);return this},add:function(tagName,attributes){attributes=typeof attributes=="undefined"?{}:attributes;if(tagName in IGNORE){if(IGNORE[tagName])this.ignoring++;return this}else if(this.ignoring)return this;
var p=this.current,tag=this.current=ELEMENT(tagName,attributes);tag.parentNode=p;if(tag["ready"]()){try{this.addhandler(tag.element)}catch(e){flog("ERROR executing element add handler: "+e.message)}p.appendChild(tag.element)}return this},reset:function(){this.ignoring=0;return this},close:function(tn,attach){tn=tn||"";tn=tn.toLowerCase();if(attach==null)attach=true;if(tn&&tn in IGNORE&&IGNORE[tn]&&this.ignoring){this.ignoring--;return this}else if(tn&&tn in IGNORE)return this;else if(this.ignoring)return this;
var wasready=this.current["ready"](),el=wasready||this.current.close()&&this.current["ready"]();this.current=this.current.parentNode;if(!el)throw new Error("attempting to close tag that is not ready");if(attach&&!wasready){try{this.addhandler(el)}catch(e){flog("ERROR executing element add handler: "+e.message)}if(this.current)this.current.appendChild(el);else this.inserter(el)}return this}};domtree.prototype["addText"]=domtree.prototype.addText;domtree.prototype["add"]=domtree.prototype.add;domtree.prototype["close"]=
domtree.prototype.close;return domtree}();
window["ghostwriter"]["domelement"]=function(){var D=document,W=window,UA=navigator.userAgent,IE=UA.indexOf("MSIE")>-1?true:false,WK=UA.indexOf("WebKit")>-1?true:false,READYONOPEN={style:false,script:false},ELQUIRKS={};domelement.prototype={setAttribute:function(name,value){return this.element.setAttribute(name,value)},appendChild:function(e){var el=this.element;if(el.tagName.toLowerCase()=="script"&&el.src)return;if("canHaveChildren"in el&&!el.canHaveChildren){var t="data"in e?e.data:e.textContent;
if(!t)return false;el.text+=t}else el.appendChild(e);return this},ready:function(){if(this.isready)return this.element;else return false},close:function(){this.isready=true;return this.element},create:function(){var get=IE&&(!D.documentMode||D.documentMode<9)?msieMaker:domMaker,encoder=null;return function(a,b){a=a.toLowerCase();b=typeof b=="object"?b:{};return get.call(this,a,b)};function msieMaker(a,b){var c,d=["<"+a];$Iterator(b,function(key,value){if(key.toLowerCase().indexOf("on")==0)value=value.replace(/\"/g,
"&quot;");d[d.length]=key+'="'+value+'"'});d[d.length]=">";var f=D.createElement(d.join(" "));return f}function domMaker(a,b){encoder=encoder||window["ghostwriter"]["htmlstreamparser"]["Encoder"];var c=D.createElement(a);$Iterator(b,function(key,value){value=typeof value=="string"?encoder["htmlDecode"](value):value;c.setAttribute(key,value)});return c}function $Iterator(object,fn){for(var key in object)if(object.hasOwnProperty(key))fn.call(object,key,object[key]);return object}}()};domelement.prototype["setAttribute"]=
domelement.prototype.setAttribute;domelement.prototype["appendChild"]=domelement.prototype.appendChild;domelement.prototype["ready"]=domelement.prototype.ready;domelement.prototype["close"]=domelement.prototype.close;domelement.prototype["create"]=domelement.prototype.create;ELQUIRKS["link"]=function(){function domlink(tn,a){if(a.href&&a.href in C)return new domtext("","");C[a.href]=true;return new domelement(tn,a)}var C={};return domlink}();domtext.prototype=new domelement;ELQUIRKS[""]=domtext;if(IE)(function(){domobject_ie.prototype=
new domelement;domstyle_ie.prototype=new domelement;function domtable_ie(){domelement.apply(this,arguments);return this}domtable_ie.prototype=new domelement;domtable_ie.prototype.appendChild=function(e){if(e.tagName=="TBODY"){this.tbody=e;this.element.appendChild(e);return this}else if(!this.tbody){this.tbody=document.createElement("TBODY");this.element.appendChild(this.tbody)}this.tbody.appendChild(e);return this};function domstyle_ie(tn,a){this._text="";this._a=a;this.isready=false;return this}
domstyle_ie.prototype["create"]=function(tn,attrs){return attrs};domstyle_ie.prototype["appendChild"]=function(el){var t="data"in el?el.data:el.text;if(!t)return;this._text+=t};domstyle_ie.prototype["close"]=function(){var _A="STYLE",_B=new RegExp("(?:^url\\([\"']?|[\"']?\\)$)","gi"),_C="text/css",_D=["<span>&nbsp;</span><"+_A],_E=D.getElementsByTagName("HEAD")[0];return function(){var a=this._a,b="",c=_D.slice(),d=D.createElement("DIV"),e;for(var f in a)c[c.length]=[f,'"'+a[f]+'"'].join("=");c[c.length]=
[">",this._text,"</",_A,">"].join("");d.innerHTML=c.join(" ");e=this.element=d.lastChild;e=e.styleSheet.imports;for(var i=0,l=e.length;i<l;i++){var p=e[i],r=p.href,k=(new domelement("LINK",{href:r.replace(_D,""),type:"text/css",rel:"stylesheet"})).close();_E.appendChild(k)}a=b=c=d=e=p=k=null;this.isready=true;return this.element}}();function domobject_ie(tn,a){domelement.apply(this,arguments);this.isready=false;return this}var _p={setAttribute:function(name,value){this.element.a[name]=value},appendChild:function(e){if(!e.tagName)return null;
if(e.tagName.toUpperCase()==="PARAM"){var n=e.getAttribute("name"),p=this.element.p;if(n)p[n]=e.getAttribute("value")}return this},close:function(){var c=this.element,a=c.a,b="PARAM",d=D.createElement("DIV"),e="object",h=["<"+e],p=c.p;for(var an in a)h[h.length]=[an,'="',a[an],'"'].join("");h[h.length]=">";for(var pn in p)h[h.length]=["<",b,' name="',pn,'" value="',p[pn],'"></',b,">"].join("");h[h.length]="</"+e+">";d.innerHTML=h.join(" ");this.isready=true;this.element=d.firstChild;a=c=d=h=p=null;
return this.element},create:function(t,a){a.type="application/x-shockwave-flash";return{a:a,p:{}}}};for(var p in _p)domobject_ie.prototype[p]=_p[p];ELQUIRKS["object"]=domobject_ie;ELQUIRKS["table"]=domtable_ie;ELQUIRKS["style"]=domstyle_ie})();if(WK)ELQUIRKS.noembed=function(){_.prototype=new domelement;_.prototype["create"]=function(){return D.createElement("noscript")};function _(){return domelement.apply(this,arguments)}return _}();function domtext(empty,textcontent){this.element=D.createTextNode(textcontent);
this.isready=true;return this}function domelement(tn,attrs){if(W==this)return new domelement(tn,attrs);if(!tn)return this;this.tagName=tn.toUpperCase();this.element=this.create(tn,attrs);this.isready=tn in READYONOPEN?READYONOPEN[tn]:true;return this}return function(tn,attributes){tn=tn.toLowerCase();if(tn in ELQUIRKS)return new ELQUIRKS[tn](tn,attributes);else return new domelement(tn,attributes)}}();
window["ghostwriter"]["htmlstreamparser"]=function(){var startTag=/^<(\w+)((?:\s+[\w\-:]+(?:\s*=\s*(?:(?:"[^"]*")|(?:'[^']*')|[^>\s]+))?)*)\s*(\/?)>/,endTag=/^<\/(\w+) *[>\n]/,comments={startre:/^\s*(?:<!--).*/,startix:"<!--",endre:/--[^>]*>/,endix:"--\>"},cdataregex=/<!\[CDATA\[(.*?)]]\>/g,attr=/([\w:-]+)(?:\s*=\s*(?:(?:"((?:\\.|[^"])*)")|(?:'((?:\\.|[^'])*)')|([^>\s]+)))?/g,empty=makeMap("xml,area,base,basefont,br,col,frame,hr,img,input,isindex,link,meta,param,embed"),block=makeMap("address,applet,blockquote,button,center,dd,del,dir,div,dl,dt,fieldset,form,frameset,hr,iframe,ins,isindex,li,map,menu,noframes,noscript,object,ol,p,pre,script,table,tbody,td,tfoot,th,thead,tr,ul"),
inline=makeMap("abbr,acronym,applet,b,basefont,bdo,big,br,button,cite,code,del,dfn,em,font,i,iframe,img,input,kbd,label,map,q,s,samp,script,select,small,strike,strong,sub,sup,textarea,tt,u,var"),closeSelf=makeMap("colgroup,dd,dt,li,options,p,td,tfoot,th,thead,tr"),fillAttrs=makeMap("checked,compact,declare,defer,disabled,ismap,multiple,nohref,noresize,noshade,nowrap,readonly,selected"),special=makeMap("script,style,iframe"),handlerList="chars,comment,start,end".split(","),tagRegexMap={};HTMLParser.prototype=
{parse:parse,flush:flush};function HTMLParser(handlers){handlers=handlers||{};this.stack=[];this.remainder="";this.handlers=handlers||{};this.parsecalls=0;this.lastendtagindex=-1;for(var i=0,l=handlerList.length,o=handlerList[i];i<l;o=handlerList[++i])if(!(o in this.handlers))handlers[o]=new Function;this["get"]=function(){return""}}function parse(html){html=this.remainder+html;var index,chars,match,stack=this.stack,last=html,handler=this.handlers,lastTag="",iterations=0;this.remainder="";this["get"]=
this["html"]=getHtml;this.parsecalls++;stack.last=function(){return this[this.length-1]};while(html){lastTag=this.stack[this.stack.length-1];chars=true;iterations++;if(!lastTag||!special[lastTag]){if(html.indexOf(comments.startix)===0){if(index=comments.endre.exec(html.substr(comments.startix.length))){html=html.substr(comments.startix.length);if(index[0].length>3)index=index.index+index[0].length-3;else index=index.index;handler["comment"](html.substr(index));html=html.substring(index+3);chars=false}}else if(html.indexOf("</")===
0){match=html.match(endTag);if(match){html=html.substring(match[0].length);match[0].replace(endTag,parseEndTag);chars=false}}else if(html.indexOf("<")===0){match=html.match(startTag);if(match){html=html.substring(match[0].length);match[0].replace(startTag,parseStartTag);chars=false}else html=html.replace(/^<[^>]*>/,"")}if(chars){index=html.indexOf("<");var text=index<0?html:html.substring(0,index),c=lastTag;html=index<0?"":html.substring(index);if(!(c in special))text=Encoder["htmlDecode"](text);
if(text.length>0)handler["chars"](text)}}else if(html.indexOf("</")>-1&&html.match(new RegExp("</"+lastTag+" *[>\n]","i"))){var len=html.length,re=tagRegexMap[lastTag]=tagRegexMap[lastTag]||new RegExp("((?:.|\n|\r)*?)</"+lastTag+" *[>\n]","i");html=html.replace(re,findTagBody);if(len>html.length)parseEndTag("",lastTag)}if(html==last){this.remainder=html;return this}last=html}parseEndTag();function findTagBody(all,text){text=text.replace(comments.startre,"").replace(cdataregex,"$1");if(text.length>
0)handler["chars"](text);return""}function parseStartTag(tag,tagName,rest,unary){tagName=tagName.toLowerCase();if(block[tagName])while(stack.last()&&inline[stack.last()])parseEndTag("",stack.last());if(closeSelf[tagName]&&stack.last()==tagName)parseEndTag("",tagName);unary=empty[tagName]||!!unary;if(!unary)stack.push(tagName.toLowerCase());var attrs=[];rest.replace(attr,function(match,name){var value=arguments[2]?arguments[2]:arguments[3]?arguments[3]:arguments[4]?arguments[4]:fillAttrs[name]?name:
"";attrs.push({name:name,value:value})});handler["start"](tagName,attrs,unary)}function parseEndTag(tag,tagName){if(!tagName)return;var found=false,tstack=stack.slice();tagName=tagName.toLowerCase();for(var pos=stack.length-1;pos>=0;pos--)if(stack[pos]==tagName){found=true;break}if(found){stack.length=pos;for(var i=tstack.length-1;i>=pos;i--)handler["end"](tstack[i])}}function getHtml(){return html}return false}function flush(){var h=this.handlers,t="";if(this.remainder.length>0)h.chars(this.remainder);
while(t=this.stack.shift())h.end(t);this.remainder=""}function makeMap(str){var obj={},items=str.split(",");for(var i=0;i<items.length;i++)obj[items[i]]=true;return obj}var Encoder=HTMLParser["Encoder"]=function(){var entityToCode={apos:39,quot:34,amp:38,lt:60,gt:62,nbsp:160,iexcl:161,cent:162,pound:163,curren:164,yen:165,brvbar:166,sect:167,uml:168,copy:169,ordf:170,laquo:171,not:172,shy:173,reg:174,macr:175,deg:176,plusmn:177,sup2:178,sup3:179,acute:180,micro:181,para:182,middot:183,cedil:184,sup1:185,
ordm:186,raquo:187,frac14:188,frac12:189,frac34:190,iquest:191,Agrave:192,Aacute:193,Acirc:194,Atilde:195,Auml:196,Aring:197,AElig:198,Ccedil:199,Egrave:200,Eacute:201,Ecirc:202,Euml:203,Igrave:204,Iacute:205,Icirc:206,Iuml:207,ETH:208,Ntilde:209,Ograve:210,Oacute:211,Ocirc:212,Otilde:213,Ouml:214,times:215,Oslash:216,Ugrave:217,Uacute:218,Ucirc:219,Uuml:220,Yacute:221,THORN:222,szlig:223,agrave:224,aacute:225,acirc:226,atilde:227,auml:228,aring:229,aelig:230,ccedil:231,egrave:232,eacute:233,ecirc:234,
euml:235,igrave:236,iacute:237,icirc:238,iuml:239,eth:240,ntilde:241,ograve:242,oacute:243,ocirc:244,otilde:245,ouml:246,divide:247,oslash:248,ugrave:249,uacute:250,ucirc:251,uuml:252,yacute:253,thorn:254,yuml:255,OElig:338,oelig:339,Scaron:352,scaron:353,Yuml:376,fnof:402,circ:710,tilde:732,Alpha:913,Beta:914,Gamma:915,Delta:916,Epsilon:917,Zeta:918,Eta:919,Theta:920,Iota:921,Kappa:922,Lambda:923,Mu:924,Nu:925,Xi:926,Omicron:927,Pi:928,Rho:929,Sigma:931,Tau:932,Upsilon:933,Phi:934,Chi:935,Psi:936,
Omega:937,alpha:945,beta:946,gamma:947,delta:948,epsilon:949,zeta:950,eta:951,theta:952,iota:953,kappa:954,lambda:955,mu:956,nu:957,xi:958,omicron:959,pi:960,rho:961,sigmaf:962,sigma:963,tau:964,upsilon:965,phi:966,chi:967,psi:968,omega:969,thetasym:977,upsih:978,piv:982,ensp:8194,emsp:8195,thinsp:8201,zwnj:8204,zwj:8205,lrm:8206,rlm:8207,ndash:8211,mdash:8212,lsquo:8216,rsquo:8217,sbquo:8218,ldquo:8220,rdquo:8221,bdquo:8222,dagger:8224,Dagger:8225,bull:8226,hellip:8230,permil:8240,prime:8242,Prime:8243,
lsaquo:8249,rsaquo:8250,oline:8254,frasl:8260,euro:8364,image:8465,weierp:8472,real:8476,trade:8482,alefsym:8501,larr:8592,uarr:8593,rarr:8594,darr:8595,harr:8596,crarr:8629,lArr:8656,uArr:8657,rArr:8658,dArr:8659,hArr:8660,forall:8704,part:8706,exist:8707,empty:8709,nabla:8711,isin:8712,notin:8713,ni:8715,prod:8719,sum:8721,minus:8722,lowast:8727,radic:8730,prop:8733,infin:8734,ang:8736,and:8743,or:8744,cap:8745,cup:8746,"int":8747,there4:8756,sim:8764,cong:8773,asymp:8776,ne:8800,equiv:8801,le:8804,
ge:8805,sub:8834,sup:8835,nsub:8836,sube:8838,supe:8839,oplus:8853,otimes:8855,perp:8869,sdot:8901,lceil:8968,rceil:8969,lfloor:8970,rfloor:8971,lang:9001,rang:9002,loz:9674,spades:9824,clubs:9827,hearts:9829,diams:9830},charToEntity=function(e2c){var $={};for(var entityName in e2c)$[String.fromCharCode(e2c[entityName])]=entityName;return $}(entityToCode),entityRegex=/&(.+?);/g;return{htmlDecode:decodeEntities};function decodeEntities(str){return str.replace(entityRegex,entityReplace)}function entityReplace(str,
ent){var code="";if(ent[0]=="#")if(ent[1]=="x")code=parseInt(ent.substr(2),16);else code=parseInt(ent.substr(1));else if(ent in entityToCode)code=entityToCode[ent];return code?String.fromCharCode(code):str}}();return HTMLParser}();
window["ghostwriter"]["loadscripts"]=function(){var D=document,H=D.getElementsByTagName("HEAD")[0],G=window["ghostwriter"],DEBUG=G["debug"],GETID=G["getscriptidentifier"],DV=D.defaultView,IE=navigator.userAgent.indexOf("MSIE")>=0,X=DV&&DV.getComputedStyle?"background-position":"backgroundPositionX",Y="type",T="text/html",J="text/javascript",JS="javascript",L="language",C="script",F="defer",DEFER=F,S="src",DS=F+S,DC=F+C,FL=[],RE=new RegExp("(?:^url\\([\"']?|[\"']?\\)$)","gi"),SCRIPTCHARCOUNT=20,_CURR=
null,MAP=function(a){var _=[];for(var b=0,c=a.length;b<c;b++)_[_.length]=a[b][2];return _}(find().sort(sorter)),MESSAGES=function($){for(var m in $)$[m]=["scriptloader.js >> ",$[m]," text/deferscript "].join("");return $}({start:"Starting ",end:"Complete",begin:"BEGIN loading",finish:"LOADED all"});if(DEBUG())flog(MESSAGES.begin);if(IE)addtoken();load();function load(){if(!MAP.length){if(DEBUG())flog(MESSAGES.finish);return simload()}var a=MAP.shift()||[],scripttoload=a[0],marker=a[1],isghost=a[2],
gwoptions;if(!isghost){marker.parentNode.replaceChild(scripttoload,marker);return load()}if(scripttoload[DEFER]){FL[FL.length]=[b,c];_CURR=null;return load()}gwoptions={insertType:"before",script:scripttoload,done:load};if(marker.parentNode===H){gwoptions["insertType"]="append";marker=H}_CURR=scripttoload;if(DEBUG())(function(scriptId){flog([MESSAGES.start,"'",scriptId,"'"].join(""));gwoptions.done=function(){flog(MESSAGES.end);load()}})(GETID(scripttoload));G(marker,gwoptions);return false}function addtoken(){var script=
D.createElement(C),head=H;script.text="void null";H.insertBefore(script,H.firstChild)}function copyscript(model){model.className="";var e=IE?model.cloneNode(false):D.createElement(C),a=model.attributes,t="";if("cssText"in e.style)e.style.cssText="";if(!IE)for(var i=0,l=a.length;i<l;i++){t=a[i];e.setAttribute(t.name,t.value)}e.setAttribute(Y,J);e.removeAttribute(L);e.removeAttribute(DS);if(model.text)e.text=model.text;return e}function getsource(s){return s.getAttribute(DS)||s.getAttribute(S)}function sorter(c,
d){var a=c[0],b=d[0];if(a==b){a=c[1];b=d[1];return a<b?-1:1}else return a>b?-1:1}function getstyle(a,b){var c;if(DV&&DV.getComputedStyle)c=DV.getComputedStyle(a,"").getPropertyValue(b);else if(a.currentStyle)c=a.currentStyle[b];return c||""}function simload(){var a,b,c=D.getElementsByTagName(C)[0];for(var i=0,l=FL.length;i<l;i++){a=copyscript(FL[i][0]);a.removeAttribute(F);b=FL[i][1];if(b.parentNode)b.parentNode.replaceChild(a,b);else c.parentNode.insertBefore(a,c)}setTimeout(G["flushloadhandlers"],
0);return}function find(){var a=toArray(D.getElementsByTagName(C)),c=[],index=0,type="",foundFirst=false;for(var i=0,l=a.length;i<l;i++){var e="",deferscript=a[i],type=(deferscript.getAttribute(Y)||"").toLowerCase(),lang=(deferscript.getAttribute(L)||"").toLowerCase(),marker=D.createTextNode(""),isdefer=type.indexOf(DEFER)>=0,isjs=type.indexOf(JS)>0||!type,src=getsource(deferscript),priority=isdefer?parseInt(getstyle(deferscript,X).split(" "),10)||0:0,newscript=isdefer?copyscript(deferscript):deferscript,
inhead=deferscript.parentNode==H;if(src&&!newscript.src){newscript.removeAttribute(DS);newscript.src=src}if(!isjs)c[c.length]=[priority,index,[newscript,marker,isdefer]];if(isdefer||foundFirst||!isjs)deferscript.parentNode.replaceChild(marker,deferscript);if(!foundFirst&&!inhead&&isdefer)foundFirst=isdefer;index++}return c}function toArray(a){var b=[];for(var i=0,l=a.length;i<l;i++)b[i]=a[i];return b}};
this["ghostwriter"]["capabilities"]=function(document){var $return={synchronous:false,localonload:false,usedatauri:false,complete:false},$script="script",$dataUri="data:text/javascript,void 0",$anchor=document.head||document.getElementsByTagName("head")[0];testSynchronousExec();testLocalOnload();return $return;function testSynchronousExec(){var asyncBlocker=document.createElement($script),synchronous=document.createElement($script),scriptText="$gwsynctest= true";asyncBlocker.async=synchronous.async=
false;asyncBlocker.src=$dataUri;synchronous.text=scriptText;$anchor.appendChild(asyncBlocker,$anchor);$anchor.appendChild(synchronous,$anchor);$return["synchronous"]=typeof this["$gwsynctest"]=="boolean"}function testLocalOnload(){var s=document.createElement($script),timer;s.onload=s.onreadystatechange=function(){loadHandler.apply(this,arguments);$return["localonload"]=true;$return["usedatauri"]=false;$return["complete"]=true;clearTimeout(timer)};timer=setTimeout(function(){var s=document.createElement($script);
s.src="data:text/javascript,void 0";s.onload=s.onreadystatechange=function(){if(loadHandler.apply(this,arguments))$return["localonload"]=$return["complete"]=$return["usedatauri"]=true};$anchor.appendChild(s)},1);$anchor.appendChild(s);return false}function loadHandler(){if(this.readyState&&this.readyState!="complete"&&this.readyState!="loaded")return false;this.onload=this.onreadystatechange=null;return true}}(document);