<?php
class ExactTarget_AccountTypeEnum {
	const None='None';
	const EXACTTARGET='EXACTTARGET';
	const PRO_CONNECT='PRO_CONNECT';
	const CHANNEL_CONNECT='CHANNEL_CONNECT';
	const CONNECT='CONNECT';
	const PRO_CONNECT_CLIENT='PRO_CONNECT_CLIENT';
	const LP_MEMBER='LP_MEMBER';
	const DOTO_MEMBER='DOTO_MEMBER';
	const ENTERPRISE_2='ENTERPRISE_2';
	const BUSINESS_UNIT='BUSINESS_UNIT';
}
