<?php
/**
 * Internationalisation file for GamingCalendar extension.
 */

$messages = array();

/**
 * English
 */
$messages['en'] = array(
    'gamingcalendar-heading' => 'Game Calendar',
);

/** TEST MESSAGES ONLY **/
$messages['en']['gamingcalendar-20110621'] = "* Batman|Arkham City\n** SYSTEMS: PS3\n** DESCRIPTION: The Dark Knight returns to Gotham in the follow-up to the award-winning Arkham Asylum in Batman: Arkham City. Explore this all-new world that spans five times larger than the Asylum using a variety of new and enhanced gameplay features.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2173/2173056.jpg|52px\n** MOREINFO: http://batman.wikia.com/wiki/Batman:_Arkham_City\n** PREORDER: http://www.bestbuy.com/site/Batman%3A+Arkham+City+-+PlayStation+3/2173056.p?id=1218312456491&skuId=2173056";
$messages['en']['gamingcalendar-20110624'] = "* Batman|Arkham City\n** SYSTEMS: PS3\n** DESCRIPTION: The Dark Knight returns to Gotham in the follow-up to the award-winning Arkham Asylum in Batman: Arkham City. Explore this all-new world that spans five times larger than the Asylum using a variety of new and enhanced gameplay features.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2173/2173056.jpg|52px\n** MOREINFO: http://batman.wikia.com/wiki/Batman:_Arkham_City\n** PREORDER: http://www.bestbuy.com/site/Batman%3A+Arkham+City+-+PlayStation+3/2173056.p?id=1218312456491&skuId=2173056";
$messages['en']['gamingcalendar-20110627'] = "* Call of Duty|Modern Warfare 3\n** SYSTEMS: X360, PS3, PC\n** DESCRIPTION: Featuring the brutality and intensity that have become cornerstones of this engaging series, Call of Duty: Modern Warfare 3 has you locking and loading for epic battles in which you lay waste to your enemies in devastating hails of gunfire. Prepare yourself for the adrenaline-pumping, heart-pounding action as you answer the Call of Duty.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2670/2670133.jpg|45px\n** MOREINFO: http://callofduty.wikia.com/wiki/Call_of_Duty:_Modern_Warfare_3\n** PREORDER: http://www.bestbuy.com/site/Call+of+Duty%3A+Modern+Warfare+3+-+Xbox+360/2670133.p?id=1218343210400&skuId=2670133";
$messages['en']['gamingcalendar-20110701'] = "* The Legend of Zelda|Skyward Sword\n** SYSTEMS: Wii\n** DESCRIPTION: Embark on Link's greatest adventure yet with The Legend of Zelda: Skyward Sword. Full motion control is supported by the Wii MotionPlus accessory and allows Link's actions to mirror your movements on-screen. Draw a bow and fire it, toss bombs at enemies and use your whip to solve puzzles with clear accuracy.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/1015/1015054.jpg|45px\n** MOREINFO: http://zelda.wikia.com/wiki/The_Legend_of_Zelda:_Skyward_Sword\n** PREORDER: http://www.bestbuy.com/site/The+Legend+of+Zelda%3A+Skyward+Sword+-+Nintendo+Wii/1015054.p?id=1218208999561&skuId=1015054";
$messages['en']['gamingcalendar-20110706'] = "* Uncharted 3|Drake's Deception\n** SYSTEMS: PS3\n** DESCRIPTION: Uncharted 3: Drake's Deception is the upcoming sequel and third installment in the Uncharted series.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/1708/1708812.jpg|48px\n** MOREINFO: http://uncharted.wikia.com/wiki/Category:Uncharted_3\n** PREORDER: http://www.bestbuy.com/site/Uncharted+3%3A+Drake's+Deception+-+PlayStation+3/1708812.p?id=1218286786572&skuId=1708812&st=uncharted%203&lp=1&cp=1\n* Red Faction|Armageddon\n** SYSTEMS: X360,PS3,PC\n** DESCRIPTION: blah blah blah blah\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/1067/1067948.jpg|45px\n** MOREINFO:http://redfaction.wikia.com/wiki/Red_Faction:Armageddon\n** PREORDER: http://www.bestbuy.com/site/Red+Faction%3A+Armageddon+-+Xbox+360/1067948.p?id=1218216965748&skuId=1067948&st=red%20faction%20armageddon&lp=1&cp=1";
$messages['en']['gamingcalendar-20110709'] = "* Gears of War 3\n** SYSTEMS: X360\n** DESCRIPTION: Gears of War 3 is the thrilling finale to the saga that has captivated millions. Experience the heart-pounding action exclusively on Xbox 360 and enjoy improved and explosive cooperative and competitive multiplayer action with Xbox LIVE.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/9854/9854804.jpg|45px\n** MOREINFO: http://gearsofwar.wikia.com/wiki/Gears_of_War_3\n** PREORDER: http://www.bestbuy.com/site/Gears+of+War+3+-+Xbox+360/9854804.p?id=1218185322509&skuId=9854804";
$messages['en']['gamingcalendar-20110713'] = "* Madden NFL 12\n** SYSTEMS: PS3\n** DESCRIPTION: Get ready to immerse yourself in the exciting NFL action when you step under center in Madden NFL 12, and experience the grit and immediacy that you've come to expect from this revolutionary series. Now, lace up for a new season and prove that your team can rise to gridiron glory in Madden NFL 12.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2375/2375201.jpg|52px\n** MOREINFO: http://random-ness.wikia.com/wiki/Madden_NFL_12\n** PREORDER: http://www.bestbuy.com/site/Madden+NFL+12+-+PlayStation+3/2375201.p?id=1218323422757&skuId=2375201";
$messages['en']['gamingcalendar-20110714'] = "* The Elder Scrolls V|Skyrim\n** SYSTEMS: X360\n** DESCRIPTION: The long-awaited and much-anticipated next installment of the award-winning The Elder Scrolls franchise is here. Now, the expansive, open world that forever revolutionized the face of the fantasy epic leads you deeper into the combat, the magic and the myth than you've ever been before.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2095/2095189.jpg|45px\n** MOREINFO: http://elderscrolls.wikia.com/wiki/The_Elder_Scrolls_V:_Skyrim\n** PREORDER: http://www.bestbuy.com/site/The+Elder+Scrolls+V%3A+Skyrim+-+Xbox+360/2095189.p?id=1218309065976&skuId=2095189";
$messages['en']['gamingcalendar-20110720'] = "* Madden NFL 12\n** SYSTEMS: PS3\n** DESCRIPTION: Get ready to immerse yourself in the exciting NFL action when you step under center in Madden NFL 12, and experience the grit and immediacy that you've come to expect from this revolutionary series. Now, lace up for a new season and prove that your team can rise to gridiron glory in Madden NFL 12.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2375/2375201.jpg|52px\n** MOREINFO: http://random-ness.wikia.com/wiki/Madden_NFL_12\n** PREORDER: http://www.bestbuy.com/site/Madden+NFL+12+-+PlayStation+3/2375201.p?id=1218323422757&skuId=2375201";
$messages['en']['gamingcalendar-20110721'] = "* The Elder Scrolls V|Skyrim\n** SYSTEMS: X360\n** DESCRIPTION: The long-awaited and much-anticipated next installment of the award-winning The Elder Scrolls franchise is here. Now, the expansive, open world that forever revolutionized the face of the fantasy epic leads you deeper into the combat, the magic and the myth than you've ever been before.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2095/2095189.jpg|45px\n** MOREINFO: http://elderscrolls.wikia.com/wiki/The_Elder_Scrolls_V:_Skyrim\n** PREORDER: http://www.bestbuy.com/site/The+Elder+Scrolls+V%3A+Skyrim+-+Xbox+360/2095189.p?id=1218309065976&skuId=2095189";
$messages['en']['gamingcalendar-20110722'] = "* Uncharted 3|Drake's Deception\n** SYSTEMS: PS3\n** DESCRIPTION: Uncharted 3: Drake's Deception is the upcoming sequel and third installment in the Uncharted series.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/1708/1708812.jpg|48px\n** MOREINFO: http://uncharted.wikia.com/wiki/Category:Uncharted_3\n** PREORDER: http://www.bestbuy.com/site/Uncharted+3%3A+Drake's+Deception+-+PlayStation+3/1708812.p?id=1218286786572&skuId=1708812&st=uncharted%203&lp=1&cp=1\n* Red Faction|Armageddon\n** SYSTEMS: X360,PS3,PC\n** DESCRIPTION: blah blah blah blah\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/1067/1067948.jpg|45px\n** MOREINFO:http://redfaction.wikia.com/wiki/Red_Faction:Armageddon\n** PREORDER: http://www.bestbuy.com/site/Red+Faction%3A+Armageddon+-+Xbox+360/1067948.p?id=1218216965748&skuId=1067948&st=red%20faction%20armageddon&lp=1&cp=1";
$messages['en']['gamingcalendar-20110723'] = "* Gears of War 3\n** SYSTEMS: X360\n** DESCRIPTION: Gears of War 3 is the thrilling finale to the saga that has captivated millions. Experience the heart-pounding action exclusively on Xbox 360 and enjoy improved and explosive cooperative and competitive multiplayer action with Xbox LIVE.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/9854/9854804.jpg|45px\n** MOREINFO: http://gearsofwar.wikia.com/wiki/Gears_of_War_3\n** PREORDER: http://www.bestbuy.com/site/Gears+of+War+3+-+Xbox+360/9854804.p?id=1218185322509&skuId=9854804";
$messages['en']['gamingcalendar-20110724'] = "* Batman|Arkham City\n** SYSTEMS: PS3\n** DESCRIPTION: The Dark Knight returns to Gotham in the follow-up to the award-winning Arkham Asylum in Batman: Arkham City. Explore this all-new world that spans five times larger than the Asylum using a variety of new and enhanced gameplay features.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2173/2173056.jpg|52px\n** MOREINFO: http://batman.wikia.com/wiki/Batman:_Arkham_City\n** PREORDER: http://www.bestbuy.com/site/Batman%3A+Arkham+City+-+PlayStation+3/2173056.p?id=1218312456491&skuId=2173056";
$messages['en']['gamingcalendar-20110726'] = "* Call of Duty|Modern Warfare 3\n** SYSTEMS: X360, PS3, PC\n** DESCRIPTION: Featuring the brutality and intensity that have become cornerstones of this engaging series, Call of Duty: Modern Warfare 3 has you locking and loading for epic battles in which you lay waste to your enemies in devastating hails of gunfire. Prepare yourself for the adrenaline-pumping, heart-pounding action as you answer the Call of Duty.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2670/2670133.jpg|45px\n** MOREINFO: http://callofduty.wikia.com/wiki/Call_of_Duty:_Modern_Warfare_3\n** PREORDER: http://www.bestbuy.com/site/Call+of+Duty%3A+Modern+Warfare+3+-+Xbox+360/2670133.p?id=1218343210400&skuId=2670133";
$messages['en']['gamingcalendar-20110727'] = "* The Legend of Zelda|Skyward Sword\n** SYSTEMS: Wii\n** DESCRIPTION: Embark on Link's greatest adventure yet with The Legend of Zelda: Skyward Sword. Full motion control is supported by the Wii MotionPlus accessory and allows Link's actions to mirror your movements on-screen. Draw a bow and fire it, toss bombs at enemies and use your whip to solve puzzles with clear accuracy.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/1015/1015054.jpg|45px\n** MOREINFO: http://zelda.wikia.com/wiki/The_Legend_of_Zelda:_Skyward_Sword\n** PREORDER: http://www.bestbuy.com/site/The+Legend+of+Zelda%3A+Skyward+Sword+-+Nintendo+Wii/1015054.p?id=1218208999561&skuId=1015054";
$messages['en']['gamingcalendar-20110728'] = "* Forza Motorsport 4|Limited Collector's Edition\n** SYSTEMS: X360\n** DESCRIPTION: Rev your engine and prepare for a racing experience like never before when controller-based racing meets the freedom and interactive power of the Kinect. Get into gear with Forza Motorsport 4, the newest game to the Forza Motorsport franchise, and enhance your racing experience with this Limited Collector's Edition.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2953/2953607.jpg|45px\n** MOREINFO: http://gaming.wikia.com/wiki/Forza_Motorsport_4\n** PREORDER: http://www.bestbuy.com/site/Forza+Motorsport+4%3A+Limited+Collector's+Edition+-+Xbox+360/2953607.p?id=1218367094869&skuId=2953607";
$messages['en']['gamingcalendar-20110801'] = "* Twisted Metal\n** SYSTEMS: PS3\n** DESCRIPTION: The classic, devilishly demented shooter action of Twisted Metal is back exclusively for PlayStation 3, delivering clearer detail and madder action than ever before. An elite fleet of more than a dozen new and familiar fear-inducing vehicles and a huge selection of deadly weapons are at your disposal, letting you choose your favorite methods of devastation.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/1072/1072255.jpg|52px\n** MOREINFO: http://twistedmetal.wikia.com/wiki/Twisted_Metal_Wiki\n** PREORDER: http://www.bestbuy.com/site/Twisted+Metal+-+PlayStation+3/1072255.p?id=1218217269251&skuId=1072255";
$messages['en']['gamingcalendar-20110802'] = "* Saints Row|The Third\n** SYSTEMS: X360\n** DESCRIPTION: In Saints Row: The Third, fame and fortune come at a bittersweet price for the kings of Stilwater. Faced with serious demands from the legendary criminal fraternity, the Syndicate, the Saints must hit the streets of Steelport to trample their new rivals — and defend their status. Get ready for intense action, grueling gang violence and outlandish situations to spare as you take on a decaying city of sin in an all-new battle with the Saints.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2330/2330703.jpg|45px\n** MOREINFO: http://saintsrow.wikia.com/wiki/Saints_Row:_The_Third\n** PREORDER: http://www.bestbuy.com/site/Saints+Row%3A+The+Third+-+Xbox+360/2330703.p?id=1218321173353&skuId=2330703\n* FIFA Soccer\n** SYSTEMS: X360\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2704/2704058.jpg|45px\n** DESCRIPTION: Step onto the pitch in FIFA Soccer 12 as the top sports game on the planet continues to redefine the genre with innovations inspired by real-world soccer. Powered by the all-new Player Impact Engine, FIFA Soccer 12 delivers authentic player interactions on the pitch from recovering quickly after a light brush to pushing and pulling during a fight for possession.\n** MOREINFO: http://fifa12.wikia.com/wiki/Fifa_12\n** PREORDER: http://www.bestbuy.com/site/FIFA+Soccer+12+-+Xbox+360/2704058.p?id=1218351305382&skuId=2704058";
$messages['en']['gamingcalendar-20110805'] = "* Deus Ex|Human Revolution Augmented Edition\n** SYSTEMS: PC\n** DESCRIPTION: The Deus Ex: Human Revolution Augmented Edition transports you to the turning point of the human venture in more ways than one, pairing the gaming experience of the future with a gripping motion graphic novel, 40-page art book, behind-the-scenes DVD and more. Enter a world where science, technology and humanity intersect, and seize the power to decide the outcome of the human race as you become Adam Jensen.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2203/2203179.jpg|45px\n** MOREINFO: http://deusex.wikia.com/wiki/Deus_Ex:_Human_Revolution_Preorder_Packs#Augmented_Edition\n** PREORDER: http://www.bestbuy.com/site/Deus+Ex%3A+Human+Revolution+Augmented+Edition+-+Windows/2203179.p?id=1218313908383&skuId=2203179";

$messages['en']['gamingcalendar-20110809'] = "* Madden NFL 12\n** SYSTEMS: PS3\n** DESCRIPTION: Get ready to immerse yourself in the exciting NFL action when you step under center in Madden NFL 12, and experience the grit and immediacy that you've come to expect from this revolutionary series. Now, lace up for a new season and prove that your team can rise to gridiron glory in Madden NFL 12.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2375/2375201.jpg|52px\n** MOREINFO: http://random-ness.wikia.com/wiki/Madden_NFL_12\n** PREORDER: http://www.bestbuy.com/site/Madden+NFL+12+-+PlayStation+3/2375201.p?id=1218323422757&skuId=2375201";
$messages['en']['gamingcalendar-20110811'] = "* The Elder Scrolls V|Skyrim\n** SYSTEMS: X360\n** DESCRIPTION: The long-awaited and much-anticipated next installment of the award-winning The Elder Scrolls franchise is here. Now, the expansive, open world that forever revolutionized the face of the fantasy epic leads you deeper into the combat, the magic and the myth than you've ever been before.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2095/2095189.jpg|45px\n** MOREINFO: http://elderscrolls.wikia.com/wiki/The_Elder_Scrolls_V:_Skyrim\n** PREORDER: http://www.bestbuy.com/site/The+Elder+Scrolls+V%3A+Skyrim+-+Xbox+360/2095189.p?id=1218309065976&skuId=2095189";
$messages['en']['gamingcalendar-20110817'] = "* Uncharted 3|Drake's Deception\n** SYSTEMS: PS3\n** DESCRIPTION: Uncharted 3: Drake's Deception is the upcoming sequel and third installment in the Uncharted series.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/1708/1708812.jpg|48px\n** MOREINFO: http://uncharted.wikia.com/wiki/Category:Uncharted_3\n** PREORDER: http://www.bestbuy.com/site/Uncharted+3%3A+Drake's+Deception+-+PlayStation+3/1708812.p?id=1218286786572&skuId=1708812&st=uncharted%203&lp=1&cp=1\n* Red Faction|Armageddon\n** SYSTEMS: X360,PS3,PC\n** DESCRIPTION: blah blah blah blah\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/1067/1067948.jpg|45px\n** MOREINFO:http://redfaction.wikia.com/wiki/Red_Faction:Armageddon\n** PREORDER: http://www.bestbuy.com/site/Red+Faction%3A+Armageddon+-+Xbox+360/1067948.p?id=1218216965748&skuId=1067948&st=red%20faction%20armageddon&lp=1&cp=1";
$messages['en']['gamingcalendar-20110818'] = "* Gears of War 3\n** SYSTEMS: X360\n** DESCRIPTION: Gears of War 3 is the thrilling finale to the saga that has captivated millions. Experience the heart-pounding action exclusively on Xbox 360 and enjoy improved and explosive cooperative and competitive multiplayer action with Xbox LIVE.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/9854/9854804.jpg|45px\n** MOREINFO: http://gearsofwar.wikia.com/wiki/Gears_of_War_3\n** PREORDER: http://www.bestbuy.com/site/Gears+of+War+3+-+Xbox+360/9854804.p?id=1218185322509&skuId=9854804";
$messages['en']['gamingcalendar-20110823'] = "* Batman|Arkham City\n** SYSTEMS: PS3\n** DESCRIPTION: The Dark Knight returns to Gotham in the follow-up to the award-winning Arkham Asylum in Batman: Arkham City. Explore this all-new world that spans five times larger than the Asylum using a variety of new and enhanced gameplay features.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2173/2173056.jpg|52px\n** MOREINFO: http://batman.wikia.com/wiki/Batman:_Arkham_City\n** PREORDER: http://www.bestbuy.com/site/Batman%3A+Arkham+City+-+PlayStation+3/2173056.p?id=1218312456491&skuId=2173056";
$messages['en']['gamingcalendar-20110826'] = "* Call of Duty|Modern Warfare 3\n** SYSTEMS: X360, PS3, PC\n** DESCRIPTION: Featuring the brutality and intensity that have become cornerstones of this engaging series, Call of Duty: Modern Warfare 3 has you locking and loading for epic battles in which you lay waste to your enemies in devastating hails of gunfire. Prepare yourself for the adrenaline-pumping, heart-pounding action as you answer the Call of Duty.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2670/2670133.jpg|45px\n** MOREINFO: http://callofduty.wikia.com/wiki/Call_of_Duty:_Modern_Warfare_3\n** PREORDER: http://www.bestbuy.com/site/Call+of+Duty%3A+Modern+Warfare+3+-+Xbox+360/2670133.p?id=1218343210400&skuId=2670133";
$messages['en']['gamingcalendar-20110830'] = "* The Legend of Zelda|Skyward Sword\n** SYSTEMS: Wii\n** DESCRIPTION: Embark on Link's greatest adventure yet with The Legend of Zelda: Skyward Sword. Full motion control is supported by the Wii MotionPlus accessory and allows Link's actions to mirror your movements on-screen. Draw a bow and fire it, toss bombs at enemies and use your whip to solve puzzles with clear accuracy.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/1015/1015054.jpg|45px\n** MOREINFO: http://zelda.wikia.com/wiki/The_Legend_of_Zelda:_Skyward_Sword\n** PREORDER: http://www.bestbuy.com/site/The+Legend+of+Zelda%3A+Skyward+Sword+-+Nintendo+Wii/1015054.p?id=1218208999561&skuId=1015054";
$messages['en']['gamingcalendar-20110902'] = "* Forza Motorsport 4|Limited Collector's Edition\n** SYSTEMS: X360\n** DESCRIPTION: Rev your engine and prepare for a racing experience like never before when controller-based racing meets the freedom and interactive power of the Kinect. Get into gear with Forza Motorsport 4, the newest game to the Forza Motorsport franchise, and enhance your racing experience with this Limited Collector's Edition.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2953/2953607.jpg|45px\n** MOREINFO: http://gaming.wikia.com/wiki/Forza_Motorsport_4\n** PREORDER: http://www.bestbuy.com/site/Forza+Motorsport+4%3A+Limited+Collector's+Edition+-+Xbox+360/2953607.p?id=1218367094869&skuId=2953607";
$messages['en']['gamingcalendar-20110906'] = "* Twisted Metal\n** SYSTEMS: PS3\n** DESCRIPTION: The classic, devilishly demented shooter action of Twisted Metal is back exclusively for PlayStation 3, delivering clearer detail and madder action than ever before. An elite fleet of more than a dozen new and familiar fear-inducing vehicles and a huge selection of deadly weapons are at your disposal, letting you choose your favorite methods of devastation.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/1072/1072255.jpg|52px\n** MOREINFO: http://twistedmetal.wikia.com/wiki/Twisted_Metal_Wiki\n** PREORDER: http://www.bestbuy.com/site/Twisted+Metal+-+PlayStation+3/1072255.p?id=1218217269251&skuId=1072255";
$messages['en']['gamingcalendar-20110907'] = "* Saints Row|The Third\n** SYSTEMS: X360\n** DESCRIPTION: In Saints Row: The Third, fame and fortune come at a bittersweet price for the kings of Stilwater. Faced with serious demands from the legendary criminal fraternity, the Syndicate, the Saints must hit the streets of Steelport to trample their new rivals — and defend their status. Get ready for intense action, grueling gang violence and outlandish situations to spare as you take on a decaying city of sin in an all-new battle with the Saints.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2330/2330703.jpg|45px\n** MOREINFO: http://saintsrow.wikia.com/wiki/Saints_Row:_The_Third\n** PREORDER: http://www.bestbuy.com/site/Saints+Row%3A+The+Third+-+Xbox+360/2330703.p?id=1218321173353&skuId=2330703\n* FIFA Soccer\n** SYSTEMS: X360\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2704/2704058.jpg|45px\n** DESCRIPTION: Step onto the pitch in FIFA Soccer 12 as the top sports game on the planet continues to redefine the genre with innovations inspired by real-world soccer. Powered by the all-new Player Impact Engine, FIFA Soccer 12 delivers authentic player interactions on the pitch from recovering quickly after a light brush to pushing and pulling during a fight for possession.\n** MOREINFO: http://fifa12.wikia.com/wiki/Fifa_12\n** PREORDER: http://www.bestbuy.com/site/FIFA+Soccer+12+-+Xbox+360/2704058.p?id=1218351305382&skuId=2704058";
$messages['en']['gamingcalendar-20110909'] = "* Deus Ex|Human Revolution Augmented Edition\n** SYSTEMS: PC\n** DESCRIPTION: The Deus Ex: Human Revolution Augmented Edition transports you to the turning point of the human venture in more ways than one, pairing the gaming experience of the future with a gripping motion graphic novel, 40-page art book, behind-the-scenes DVD and more. Enter a world where science, technology and humanity intersect, and seize the power to decide the outcome of the human race as you become Adam Jensen.\n** IMAGE: http://images.bestbuy.com/BestBuy_US/images/products/2203/2203179.jpg|45px\n** MOREINFO: http://deusex.wikia.com/wiki/Deus_Ex:_Human_Revolution_Preorder_Packs#Augmented_Edition\n** PREORDER: http://www.bestbuy.com/site/Deus+Ex%3A+Human+Revolution+Augmented+Edition+-+Windows/2203179.p?id=1218313908383&skuId=2203179";
