#!/usr/bin/php
<?php
/**
 * MwRdf.php -- RDF framework for MediaWiki
 * Copyright 2005,2006 Evan Prodromou <evan@wikitravel.org>
 * Copyright 2007 Mark Jaroski
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or
 *  (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA *
 * @author Evan Prodromou <evan@wikitravel.org>
 * @author Mark Jaroski <mark@geekhive.net>
 * @package MediaWiki
 * @subpackage Extensions
 */

if (!defined('PHPUnit_MAIN_METHOD')) {
	define('PHPUnit_MAIN_METHOD', 'MwRdf_AllTests::main');
}

define( 'MEDIAWIKI', true );

set_include_path( "test" . PATH_SEPARATOR . get_include_path() );

require_once( 'PHPUnit/Framework.php' );
require_once( 'PHPUnit/TextUI/TestRunner.php' );
require_once( 'PHPUnit/Extensions/OutputTestCase.php' );

require_once( 'SetupRdf.php' );

require_once( 'MwRdfTest.php' );
require_once( 'MwRdfTest_Framework.php' );
require_once( 'MwRdfTest_Models.php' );
require_once( 'MwRdfTest_Storage.php' );
require_once( 'MwRdfTest_Vocabulary.php' );
require_once( 'MwRdfTest_Load.php' );
require_once( 'MwRdfTest_Form.php' );
require_once( 'MwRdfTest_Pages.php' );

$wgSitename = "Test wiki";
$wgContLanguageCode = "en";

class MwRdf_AllTests {
	public static function main( $suite ) {
		if ( ! $suite )
			$suite = 'all';

		switch ( $suite ) {
			case 'all' :
				PHPUnit_TextUI_TestRunner::run(self::suite());
				break;
			case 'framework' :
				PHPUnit_TextUI_TestRunner::run(self::frameworkSuite());
				break;
			case 'test' :
				PHPUnit_TextUI_TestRunner::run(self::testTestSuite());
				break;
			case 'page' :
				PHPUnit_TextUI_TestRunner::run(self::pageSuite());
				break;
			case 'vocab' :
				PHPUnit_TextUI_TestRunner::run(self::vocabSuite());
				break;
			case 'models' :
				PHPUnit_TextUI_TestRunner::run(self::modelFactorySuite());
				break;
			case 'function' :
				PHPUnit_TextUI_TestRunner::run(self::functionSuite());
				break;
			case 'storage' :
				PHPUnit_TextUI_TestRunner::run(self::storageSuite());
				break;
			case 'load' :
				PHPUnit_TextUI_TestRunner::run(self::loadSuite());
				break;
			case 'query' :
				PHPUnit_TextUI_TestRunner::run(self::querySuite());
				break;
		}
	}

	public static function suite() {
		$suite = new PHPUnit_Framework_TestSuite('Mediawiki RDF Extension');
		$suite->addTestSuite('MwRdfTest_Framework');
		$suite->addTestSuite('MwRdf_Vocabulary_Test');
		$suite->addTestSuite('MwRdf_ModelingAgent_Test');
		$suite->addTestSuite('MwRdfTest_Storage');
		$suite->addTestSuite('MwRdf_Form_Test');
		$suite->addTestSuite('MwRdf_SpecialPageFunction_Test');
		return $suite;
	}

	public static function testTestSuite() {
		$suite = new PHPUnit_Framework_TestSuite('Mediawiki RDF Extension');
		$suite->addTestSuite('MwRdfTestTest');
		return $suite;
	}

	public static function frameworkSuite() {
		$suite = new PHPUnit_Framework_TestSuite('Mediawiki RDF Extension');
		$suite->addTestSuite('MwRdfTest_Framework');
		return $suite;
	}

	public static function modelFactorySuite() {
		$suite = new PHPUnit_Framework_TestSuite('Mediawiki RDF Extension');
		$suite->addTestSuite('MwRdf_ModelingAgent_Test');
		return $suite;
	}

	public static function storageSuite() {
		$suite = new PHPUnit_Framework_TestSuite('Mediawiki RDF Extension');
		$suite->addTestSuite('MwRdfTest_Storage');
		return $suite;
	}

	public static function loadSuite() {
		$suite = new PHPUnit_Framework_TestSuite('Mediawiki RDF Extension');
		$suite->addTestSuite('MwRdf_Load_Test');
		return $suite;
	}

	public static function functionSuite() {
		$suite = new PHPUnit_Framework_TestSuite('Mediawiki RDF Extension');
		$suite->addTestSuite('MwRdf_SpecialPageFunction_Test');
		return $suite;
	}

	public static function vocabSuite() {
		$suite = new PHPUnit_Framework_TestSuite('Mediawiki RDF Extension');
		$suite->addTestSuite('MwRdf_Vocabulary_Test');
		return $suite;
	}

	public static function querySuite() {
		$suite = new PHPUnit_Framework_TestSuite('Mediawiki RDF Extension');
		$suite->addTestSuite('MwRdf_QueryPage_Test');
		$suite->addTestSuite('MwRdf_LinksInQuery_Test');
		return $suite;
	}

	public static function pageSuite() {
		$suite = new PHPUnit_Framework_TestSuite('Mediawiki RDF Extension');
		$suite->addTestSuite( 'MwRdf_SpecialPage_Test' );
		$suite->addTestSuite( 'MwRdf_Form_Test' );
		return $suite;
	}

}

if (PHPUnit_MAIN_METHOD == 'MwRdf_AllTests::main') {
	MwRdfTest::$Runtime = time();
	$suite = null;
	if ( isset( $argv[1] ) ) $suite = $argv[1];
	MwRdf_AllTests::main( $suite );
}
