FROM nginx:1.13

RUN chown -R nginx:nginx /etc/nginx && \
    chown nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /var/log/nginx && \
    mkdir /var/run/nginx && \
    chown nginx:nginx /var/run/nginx

ADD docker/dev/k8s/nginx.conf /etc/nginx/nginx.conf
ADD docker/dev/k8s/site.conf /etc/nginx/conf.d/default.conf

# static mediawiki files
ADD skins /usr/wikia/slot1/current/src/skins
ADD resources /usr/wikia/slot1/current/src/resources
ADD extensions /usr/wikia/slot1/current/src/extensions

USER nginx