FROM artifactory.wikia-inc.com/sus/php-wikia-base:47aabb7

ADD app /usr/wikia/slot1/current/src
ADD config /usr/wikia/slot1/current/config
ADD cache /usr/wikia/slot1/current/cache/messages

USER nobody
