<?php
/**
 * TemplateClassificationData
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */
/**
 *  Copyright 2015 SmartBear Software
 *
 *  Licensed under the Apache License, Version 2.0 (the "License");
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License.
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\TemplateClassification\Storage\Models;

use \ArrayAccess;
/**
 * TemplateClassificationData Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TemplateClassificationData implements ArrayAccess
{
    /**
      * Array of property to type mappings. Used for (de)serialization 
      * @var string[]
      */
    static $swaggerTypes = array(
        'wiki_id' => 'int',
        'page_id' => 'int',
        'providers' => '\Swagger\Client\TemplateClassification\Storage\Models\TemplateTypeProvider[]'
    );
  
    /** 
      * Array of attributes where the key is the local name, and the value is the original name
      * @var string[] 
      */
    static $attributeMap = array(
        'wiki_id' => 'wikiId',
        'page_id' => 'pageId',
        'providers' => 'providers'
    );
  
    /**
      * Array of attributes to setter functions (for deserialization of responses)
      * @var string[]
      */
    static $setters = array(
        'wiki_id' => 'setWikiId',
        'page_id' => 'setPageId',
        'providers' => 'setProviders'
    );
  
    /**
      * Array of attributes to getter functions (for serialization of requests)
      * @var string[]
      */
    static $getters = array(
        'wiki_id' => 'getWikiId',
        'page_id' => 'getPageId',
        'providers' => 'getProviders'
    );
  
    
    /**
      * $wiki_id 
      * @var int
      */
    protected $wiki_id;
    
    /**
      * $page_id 
      * @var int
      */
    protected $page_id;
    
    /**
      * $providers 
      * @var \Swagger\Client\TemplateClassification\Storage\Models\TemplateTypeProvider[]
      */
    protected $providers;
    

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        if ($data != null) {
            $this->wiki_id = $data["wiki_id"];
            $this->page_id = $data["page_id"];
            $this->providers = $data["providers"];
        }
    }
    
    /**
     * Gets wiki_id
     * @return int
     */
    public function getWikiId()
    {
        return $this->wiki_id;
    }
  
    /**
     * Sets wiki_id
     * @param int $wiki_id 
     * @return $this
     */
    public function setWikiId($wiki_id)
    {
        
        $this->wiki_id = $wiki_id;
        return $this;
    }
    
    /**
     * Gets page_id
     * @return int
     */
    public function getPageId()
    {
        return $this->page_id;
    }
  
    /**
     * Sets page_id
     * @param int $page_id 
     * @return $this
     */
    public function setPageId($page_id)
    {
        
        $this->page_id = $page_id;
        return $this;
    }
    
    /**
     * Gets providers
     * @return \Swagger\Client\TemplateClassification\Storage\Models\TemplateTypeProvider[]
     */
    public function getProviders()
    {
        return $this->providers;
    }
  
    /**
     * Sets providers
     * @param \Swagger\Client\TemplateClassification\Storage\Models\TemplateTypeProvider[] $providers 
     * @return $this
     */
    public function setProviders($providers)
    {
        
        $this->providers = $providers;
        return $this;
    }
    
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset 
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->$offset);
    }
  
    /**
     * Gets offset.
     * @param  integer $offset Offset 
     * @return mixed 
     */
    public function offsetGet($offset)
    {
        return $this->$offset;
    }
  
    /**
     * Sets value based on offset.
     * @param  integer $offset Offset 
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        $this->$offset = $value;
    }
  
    /**
     * Unsets offset.
     * @param  integer $offset Offset 
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->$offset);
    }
  
    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) {
            return json_encode(get_object_vars($this), JSON_PRETTY_PRINT);
        } else {
            return json_encode(get_object_vars($this));
        }
    }
}
