#!/bin/bash
#
# This script is used for generating merged dictionaries for given language.
#
# $Id$
if [ -z "$1" ]
then
	echo "Usage: ./merge [lang code]"
	exit
fi

LANG=$1

echo "Merging $LANG dictionaries";

# get list of dictionaries for given dictionary
FILES=`ls $LANG_*.dic`

# prepare words storage
WORDS_FILE="words_$LANG"
rm words_*

# process each file
for f in $FILES
do
	PREFIX=`echo $f | cut -d '.' -f1`
	echo "  Processing $PREFIX..."

	unmunch $PREFIX.dic $PREFIX.aff >> $WORDS_FILE 2> /dev/null
done

# sort the words and remove duplicates
sort $WORDS_FILE | uniq  > $WORDS_FILE.tmp
mv $WORDS_FILE.tmp $WORDS_FILE

# print out some statistics
COUNT=`cat $WORDS_FILE | wc -l`
echo "$COUNT words found"
echo

# generate merged dictionary
echo "Generating dictionary and affix files..."
affixcompress $WORDS_FILE >& /dev/null

# cleanup
rm $WORDS_FILE word word2 *.tmp
echo "Done"