<?php

$wgExtensionCredits['other'][] = array(
	'name' => 'Rich Text Editor (Wysiwyg)',
	'description' => 'CKeditor integration for MediaWiki',
	'descriptionmsg' => 'rte-desc',
	'url' => 'http://www.wikia.com/wiki/c:help:Help:Editing',
	'author' => array('Inez Korczyński', 'Maciej Brencz')
);

// autoloaded classes
$wgAutoloadClasses['RTE'] = __DIR__ . '/RTE.class.php';
$wgAutoloadClasses['RTEAjax'] = __DIR__ . '/RTEAjax.class.php';
$wgAutoloadClasses['RTEData'] = __DIR__ . '/RTEData.class.php';
$wgAutoloadClasses['RTELang'] = __DIR__ . '/RTELang.class.php';
$wgAutoloadClasses['RTELinkerHooks'] = __DIR__ . '/RTELinkerHooks.class.php';
$wgAutoloadClasses['RTEMagicWord'] = __DIR__ . '/RTEMagicWord.class.php';
$wgAutoloadClasses['RTEMarker'] = __DIR__ . '/RTEMarker.class.php';
$wgAutoloadClasses['RTEParser'] = __DIR__ . '/RTEParser.class.php';
$wgAutoloadClasses['RTEReverseParser'] = __DIR__ . '/RTEReverseParser.class.php';
$wgAutoloadClasses['RTEController'] = __DIR__ . '/RTEController.class.php';

// hooks
$wgHooks['EditPage::showEditForm:initial'][] = 'RTE::init';
$wgHooks['ParserMakeImageParams'][] = 'RTEParser::makeImageParams';
$wgHooks['AlternateEdit'][] = 'RTE::reverse';
$wgHooks['EditPageBeforeConflictDiff'][] = 'RTE::reverse';

// hooks for user preferences handling
$wgHooks['EditingPreferencesBefore'][] = 'RTE::onEditingPreferencesBefore';
$wgHooks['UserGetOption'][] = 'RTE::userGetOption';
$wgHooks['UserGetPreference'][] = 'RTE::userGetOption';

// __NOWYSIWYG__ magic words handling
$wgHooks['MagicWordwgVariableIDs'][] = 'RTEMagicWord::register';
$wgHooks['LanguageGetMagic'][] = 'RTEMagicWord::get';
$wgHooks['InternalParseBeforeLinks'][] = 'RTEMagicWord::remove';
$wgHooks['ParserBeforeStrip'][] = 'RTEMagicWord::checkParserBeforeStrip';
$wgHooks['EditPage::getContent::end'][] = 'RTEMagicWord::checkEditPageContent';

// hooks for modifying MW Linker behavior
$wgHooks['MakeHeadline'][] = 'RTELinkerHooks::onMakeHeadline';
$wgHooks['LinkEnd'][] = 'RTELinkerHooks::onLinkEnd';
$wgHooks['LinkerMakeExternalLink'][] = 'RTELinkerHooks::onLinkerMakeExternalLink';

// i18n
$wgExtensionMessagesFiles['RTE'] = __DIR__ . '/i18n/RTE.i18n.php';

// Ajax dispatcher
$wgAjaxExportList[] = 'RTEAjax';
function RTEAjax() {
	wfProfileIn(__METHOD__);
	global $wgRequest;

	$ret = false;

	$method = $wgRequest->getVal( 'method', false );

	if ($method && method_exists( 'RTEAjax', $method )) {

		$data = RTEAjax::$method();

		if (is_array( $data )) {
			$json = json_encode( $data );

			$response = new AjaxResponse( $json );
			$response->setContentType( 'application/json; charset=utf-8' );
			$ret = $response;
		}
		else {
			$ret = $data;
		}
	}

	wfProfileOut(__METHOD__);
	return $ret;
}
/*
$wgResourceModules['ext.wikia.RTE2'] = array(
	'messages' => array(
		'rte-ck-bucket-textAppearance',
		'rte-ck-bucket-insert',
		'rte-ck-bucket-controls',
		'rte-ck-commentEditor-title',
		'rte-ck-errorPopupTitle',
		'rte-ck-hoverPreview-codedElement-intro',
		'rte-ck-hoverPreview-codedElement-title',
		'rte-ck-hoverPreview-comment-intro',
		'rte-ck-hoverPreview-comment-title',
		'rte-ck-hoverPreview-confirmDelete',
		'rte-ck-hoverPreview-delete',
		'rte-ck-hoverPreview-edit',
		'rte-ck-hoverPreview-media-notExisting',
		'rte-ck-hoverPreview-template-intro',
		'rte-ck-hoverPreview-template-notExisting',
		'rte-ck-hoverPreview-video-notExisting',
		'rte-ck-image-add',
		'rte-ck-image-photo',
		'rte-ck-image-confirmDelete',
		'rte-ck-image-confirmDeleteTitle',
		'rte-ck-imagePlaceholder-confirmDelete',
		'rte-ck-imagePlaceholder-confirmDeleteTitle',
		'rte-ck-imagePlaceholder-tooltip',
		'rte-ck-justify-center',
		'rte-ck-link-add',
		'rte-ck-link-error-badPageTitle',
		'rte-ck-link-error-badUrl',
		'rte-ck-link-error-title',
		'rte-ck-link-external-linkText',
		'rte-ck-link-external-numberedLink',
		'rte-ck-link-external-tab',
		'rte-ck-link-external-url',
		'rte-ck-link-internal-linkText',
		'rte-ck-link-internal-pageName',
		'rte-ck-link-internal-tab',
		'rte-ck-link-title',
		'rte-ck-link-label-target',
		'rte-ck-link-label-display',
		'rte-ck-link-label-internal',
		'rte-ck-link-label-external',
		'rte-ck-link-status-checking',
		'rte-ck-link-status-exists',
		'rte-ck-link-status-notexists',
		'rte-ck-link-status-external',
		'rte-ck-media-delete',
		'rte-ck-media-edit',
		'rte-ck-modeSwitch-toSource',
		'rte-ck-modeSwitch-toWysiwyg',
		'rte-ck-modeSwitch-toSourceTooltip',
		'rte-ck-modeSwitch-toWysiwygTooltip',
		'rte-ck-modeSwitch-error',
		'rte-ck-photoGallery-gallery',
		'rte-ck-photoGallery-slideshow',
		'rte-ck-photoGallery-slider',
		'rte-ck-photoGallery-addGallery',
		'rte-ck-photoGallery-addSlideshow',
		'rte-ck-photoGallery-addSlider',
		'rte-ck-photoGallery-confirmDelete',
		'rte-ck-photoGallery-confirmDeleteTitle',
		'rte-ck-photoGallery-tooltip',
		'rte-ck-photoGallery-tooltipSlideshow',
		'rte-ck-photoGallery-tooltipSlider',
		'rte-ck-signature-add',
		'rte-ck-signature-label',
		'rte-ck-table-alignNotSet',
		'rte-ck-table-invalidCols',
		'rte-ck-table-invalidRows',
		'rte-ck-table-toolbarTooltip',
		'rte-ck-templateDropDown-chooseAnotherTpl',
		'rte-ck-templateDropDown-showUsedList',
		'rte-ck-templateDropDown-makeLayout',
		'rte-ck-templateDropDown-label',
		'rte-ck-templateDropDown-title',
		'rte-ck-templateEditor-dialog-browse',
		'rte-ck-templateEditor-dialog-insert',
		'rte-ck-templateEditor-dialog-magicWords',
		'rte-ck-templateEditor-dialog-magicWordsLink',
		'rte-ck-templateEditor-dialog-mostFrequentlyUsed',
		'rte-ck-templateEditor-dialog-search',
		'rte-ck-templateEditor-editor-chooseAnotherTpl',
		'rte-ck-templateEditor-editor-intro',
		'rte-ck-templateEditor-editor-parameters',
		'rte-ck-templateEditor-editor-previewButton',
		'rte-ck-templateEditor-editor-previewTitle',
		'rte-ck-templateEditor-editor-viewTemplate',
		'rte-ck-templateEditor-usedTemplates-title',
		'rte-ck-templateEditor-title',
		'rte-ck-unlink',
		'rte-ck-video-add',
		'rte-ck-video-video',
		'rte-ck-video-confirmDelete',
		'rte-ck-video-confirmDeleteTitle',
		'rte-ck-videoPlaceholder-confirmDelete',
		'rte-ck-videoPlaceholder-confirmDeleteTitle',
		'rte-ck-videoPlaceholder-tooltip',
		'rte-ck-mut-add',
		'rte-ck-mut-mut',
		'rte-ck-widescreen-toggle',
		'rte-ck-spellchecker-moreSuggestions',
		'rte-ck-pasteText-title',
		'rte-ck-clipboard-pasteMsg',
		'rte-ck-format-tag_p',
		'rte-ck-format-tag_pre',
		'rte-ck-format-tag_h2',
		'rte-ck-format-tag_h3',
		'rte-ck-format-tag_h4',
		'rte-ck-format-tag_h5',

	'rte-ck-anchor-toolbar',
	'rte-ck-anchor-menu',
	'rte-ck-anchor-title',
	'rte-ck-anchor-name',
	'rte-ck-anchor-errorName',
	'rte-ck-anchor-remove',
	'rte-ck-bidi-ltr',
	'rte-ck-bidi-rtl',
	'rte-ck-blockquote',
	'rte-ck-bold',
	'rte-ck-bulletedlist',
	'rte-ck-button-title',
	'rte-ck-button-text',
	'rte-ck-button-type',
	'rte-ck-button-typeBtn',
	'rte-ck-button-typeSbm',
	'rte-ck-button-typeRst',
	'rte-ck-checkboxAndRadio-checkboxTitle',
	'rte-ck-checkboxAndRadio-radioTitle',
	'rte-ck-checkboxAndRadio-value',
	'rte-ck-checkboxAndRadio-selected',
	'rte-ck-clipboard-title',
	'rte-ck-clipboard-cutError',
	'rte-ck-clipboard-copyError',
	'rte-ck-clipboard-pasteMsg',
	'rte-ck-clipboard-securityMsg',
	'rte-ck-clipboard-pasteArea',
	'rte-ck-colorButton-textColorTitle',
	'rte-ck-colorButton-bgColorTitle',
	'rte-ck-colorButton-panelTitle',
	'rte-ck-colorButton-auto',
	'rte-ck-colorButton-more',
	'rte-ck-colordialog-title',
	'rte-ck-colordialog-options',
	'rte-ck-colordialog-highlight',
	'rte-ck-colordialog-selected',
	'rte-ck-colordialog-clear',
	'rte-ck-colors-000',
	'rte-ck-colors-800000',
	'rte-ck-colors-8B4513',
	'rte-ck-colors-2F4F4F',
	'rte-ck-colors-008080',
	'rte-ck-colors-000080',
	'rte-ck-colors-4B0082',
	'rte-ck-colors-696969',
	'rte-ck-colors-B22222',
	'rte-ck-colors-A52A2A',
	'rte-ck-colors-DAA520',
	'rte-ck-colors-006400',
	'rte-ck-colors-40E0D0',
	'rte-ck-colors-0000CD',
	'rte-ck-colors-800080',
	'rte-ck-colors-808080',
	'rte-ck-colors-F00',
	'rte-ck-colors-FF8C00',
	'rte-ck-colors-FFD700',
	'rte-ck-colors-008000',
	'rte-ck-colors-0FF',
	'rte-ck-colors-00F',
	'rte-ck-colors-EE82EE',
	'rte-ck-colors-A9A9A9',
	'rte-ck-colors-FFA07A',
	'rte-ck-colors-FFA500',
	'rte-ck-colors-FFFF00',
	'rte-ck-colors-00FF00',
	'rte-ck-colors-AFEEEE',
	'rte-ck-colors-ADD8E6',
	'rte-ck-colors-DDA0DD',
	'rte-ck-colors-D3D3D3',
	'rte-ck-colors-FFF0F5',
	'rte-ck-colors-FAEBD7',
	'rte-ck-colors-FFFFE0',
	'rte-ck-colors-F0FFF0',
	'rte-ck-colors-F0FFFF',
	'rte-ck-colors-F0F8FF',
	'rte-ck-colors-E6E6FA',
	'rte-ck-colors-FFF',
	'rte-ck-common-browseServer',
	'rte-ck-common-url',
	'rte-ck-common-protocol',
	'rte-ck-common-upload',
	'rte-ck-common-uploadSubmit',
	'rte-ck-common-image',
	'rte-ck-common-flash',
	'rte-ck-common-form',
	'rte-ck-common-checkbox',
	'rte-ck-common-radio',
	'rte-ck-common-textField',
	'rte-ck-common-textarea',
	'rte-ck-common-hiddenField',
	'rte-ck-common-button',
	'rte-ck-common-select',
	'rte-ck-common-imageButton',
	'rte-ck-common-notSet',
	'rte-ck-common-id',
	'rte-ck-common-name',
	'rte-ck-common-langDir',
	'rte-ck-common-langDirLtr',
	'rte-ck-common-langDirRtl',
	'rte-ck-common-langCode',
	'rte-ck-common-longDescr',
	'rte-ck-common-cssClass',
	'rte-ck-common-advisoryTitle',
	'rte-ck-common-cssStyle',
	'rte-ck-common-ok',
	'rte-ck-common-cancel',
	'rte-ck-common-close',
	'rte-ck-common-preview',
	'rte-ck-common-generalTab',
	'rte-ck-common-advancedTab',
	'rte-ck-common-validateNumberFailed',
	'rte-ck-common-confirmNewPage',
	'rte-ck-common-confirmCancel',
	'rte-ck-common-options',
	'rte-ck-common-target',
	'rte-ck-common-targetNew',
	'rte-ck-common-targetTop',
	'rte-ck-common-targetSelf',
	'rte-ck-common-targetParent',
	'rte-ck-common-langDirLTR',
	'rte-ck-common-langDirRTL',
	'rte-ck-common-styles',
	'rte-ck-common-cssClasses',
	'rte-ck-common-width',
	'rte-ck-common-height',
	'rte-ck-common-align',
	'rte-ck-common-alignLeft',
	'rte-ck-common-alignRight',
	'rte-ck-common-alignCenter',
	'rte-ck-common-alignTop',
	'rte-ck-common-alignMiddle',
	'rte-ck-common-alignBottom',
	'rte-ck-common-invalidHeight',
	'rte-ck-common-invalidWidth',
	'rte-ck-common-invalidCssLength',
	'rte-ck-common-invalidHtmlLength',
	'rte-ck-common-unavailable',
	'rte-ck-contextmenu-options',
	'rte-ck-copy',
	'rte-ck-cut',
	'rte-ck-dir',
	'rte-ck-div-title',
	'rte-ck-div-toolbar',
	'rte-ck-div-cssClassInputLabel',
	'rte-ck-div-styleSelectLabel',
	'rte-ck-div-IdInputLabel',
	'rte-ck-div-languageCodeInputLabel',
	'rte-ck-div-inlineStyleInputLabel',
	'rte-ck-div-advisoryTitleInputLabel',
	'rte-ck-div-langDirLabel',
	'rte-ck-div-langDirLTRLabel',
	'rte-ck-div-langDirRTLLabel',
	'rte-ck-div-edit',
	'rte-ck-div-remove',
	'rte-ck-docprops-label',
	'rte-ck-docprops-title',
	'rte-ck-docprops-design',
	'rte-ck-docprops-meta',
	'rte-ck-docprops-chooseColor',
	'rte-ck-docprops-other',
	'rte-ck-docprops-docTitle',
	'rte-ck-docprops-charset',
	'rte-ck-docprops-charsetOther',
	'rte-ck-docprops-charsetASCII',
	'rte-ck-docprops-charsetCE',
	'rte-ck-docprops-charsetCT',
	'rte-ck-docprops-charsetCR',
	'rte-ck-docprops-charsetGR',
	'rte-ck-docprops-charsetJP',
	'rte-ck-docprops-charsetKR',
	'rte-ck-docprops-charsetTR',
	'rte-ck-docprops-charsetUN',
	'rte-ck-docprops-charsetWE',
	'rte-ck-docprops-docType',
	'rte-ck-docprops-docTypeOther',
	'rte-ck-docprops-xhtmlDec',
	'rte-ck-docprops-bgColor',
	'rte-ck-docprops-bgImage',
	'rte-ck-docprops-bgFixed',
	'rte-ck-docprops-txtColor',
	'rte-ck-docprops-margin',
	'rte-ck-docprops-marginTop',
	'rte-ck-docprops-marginLeft',
	'rte-ck-docprops-marginRight',
	'rte-ck-docprops-marginBottom',
	'rte-ck-docprops-metaKeywords',
	'rte-ck-docprops-metaDescription',
	'rte-ck-docprops-metaAuthor',
	'rte-ck-docprops-metaCopyright',
	'rte-ck-docprops-previewHtml',
	'rte-ck-editor',
	'rte-ck-editorTitle',
	'rte-ck-elementsPath-eleLabel',
	'rte-ck-elementsPath-eleTitle',
	'rte-ck-fakeobjects-anchor',
	'rte-ck-fakeobjects-flash',
	'rte-ck-fakeobjects-iframe',
	'rte-ck-fakeobjects-hiddenfield',
	'rte-ck-fakeobjects-unknown',
	'rte-ck-findAndReplace-title',
	'rte-ck-findAndReplace-find',
	'rte-ck-findAndReplace-replace',
	'rte-ck-findAndReplace-findWhat',
	'rte-ck-findAndReplace-replaceWith',
	'rte-ck-findAndReplace-notFoundMsg',
	'rte-ck-findAndReplace-matchCase',
	'rte-ck-findAndReplace-matchWord',
	'rte-ck-findAndReplace-matchCyclic',
	'rte-ck-findAndReplace-replaceAll',
	'rte-ck-findAndReplace-replaceSuccessMsg',
	'rte-ck-font-label',
	'rte-ck-font-voiceLabel',
	'rte-ck-font-panelTitle',
	'rte-ck-fontSize-label',
	'rte-ck-fontSize-voiceLabel',
	'rte-ck-fontSize-panelTitle',
	'rte-ck-form-title',
	'rte-ck-form-menu',
	'rte-ck-form-action',
	'rte-ck-form-method',
	'rte-ck-form-encoding',
	'rte-ck-format-label',
	'rte-ck-format-panelTitle',
	'rte-ck-format-tag_p',
	'rte-ck-format-tag_pre',
	'rte-ck-format-tag_address',
	'rte-ck-format-tag_h1',
	'rte-ck-format-tag_h2',
	'rte-ck-format-tag_h3',
	'rte-ck-format-tag_h4',
	'rte-ck-format-tag_h5',
	'rte-ck-format-tag_h6',
	'rte-ck-format-tag_div',
	'rte-ck-hidden-title',
	'rte-ck-hidden-name',
	'rte-ck-hidden-value',
	'rte-ck-horizontalrule',
	'rte-ck-iframe-title',
	'rte-ck-iframe-toolbar',
	'rte-ck-iframe-noUrl',
	'rte-ck-iframe-scrolling',
	'rte-ck-iframe-border',
	'rte-ck-indent',
	'rte-ck-italic',
	'rte-ck-justify-left',
	'rte-ck-justify-center',
	'rte-ck-justify-right',
	'rte-ck-justify-block',
	'rte-ck-link-toolbar',
	'rte-ck-link-other',
	'rte-ck-link-menu',
	'rte-ck-link-title',
	'rte-ck-link-info',
	'rte-ck-link-target',
	'rte-ck-link-upload',
	'rte-ck-link-advanced',
	'rte-ck-link-type',
	'rte-ck-link-toUrl',
	'rte-ck-link-toAnchor',
	'rte-ck-link-toEmail',
	'rte-ck-link-targetFrame',
	'rte-ck-link-targetPopup',
	'rte-ck-link-targetFrameName',
	'rte-ck-link-targetPopupName',
	'rte-ck-link-popupFeatures',
	'rte-ck-link-popupResizable',
	'rte-ck-link-popupStatusBar',
	'rte-ck-link-popupLocationBar',
	'rte-ck-link-popupToolbar',
	'rte-ck-link-popupMenuBar',
	'rte-ck-link-popupFullScreen',
	'rte-ck-link-popupScrollBars',
	'rte-ck-link-popupDependent',
	'rte-ck-link-popupLeft',
	'rte-ck-link-popupTop',
	'rte-ck-link-id',
	'rte-ck-link-langDir',
	'rte-ck-link-langDirLTR',
	'rte-ck-link-langDirRTL',
	'rte-ck-link-acccessKey',
	'rte-ck-link-name',
	'rte-ck-link-langCode',
	'rte-ck-link-tabIndex',
	'rte-ck-link-advisoryTitle',
	'rte-ck-link-advisoryContentType',
	'rte-ck-link-cssClasses',
	'rte-ck-link-charset',
	'rte-ck-link-styles',
	'rte-ck-link-rel',
	'rte-ck-link-selectAnchor',
	'rte-ck-link-anchorName',
	'rte-ck-link-anchorId',
	'rte-ck-link-emailAddress',
	'rte-ck-link-emailSubject',
	'rte-ck-link-emailBody',
	'rte-ck-link-noAnchors',
	'rte-ck-link-noUrl',
	'rte-ck-link-noEmail',
	'rte-ck-list-numberedTitle',
	'rte-ck-list-bulletedTitle',
	'rte-ck-list-type',
	'rte-ck-list-start',
	'rte-ck-list-validateStartNumber',
	'rte-ck-list-circle',
	'rte-ck-list-disc',
	'rte-ck-list-square',
	'rte-ck-list-none',
	'rte-ck-list-notset',
	'rte-ck-list-armenian',
	'rte-ck-list-georgian',
	'rte-ck-list-lowerRoman',
	'rte-ck-list-upperRoman',
	'rte-ck-list-lowerAlpha',
	'rte-ck-list-upperAlpha',
	'rte-ck-list-lowerGreek',
	'rte-ck-list-decimal',
	'rte-ck-list-decimalLeadingZero',
	'rte-ck-maximize',
	'rte-ck-minimize',
	'rte-ck-newPage',
	'rte-ck-numberedlist',
	'rte-ck-outdent',
	'rte-ck-pagebreak',
	'rte-ck-pagebreakAlt',
	'rte-ck-paste',
	'rte-ck-pasteText-button',
	'rte-ck-pasteText-title',
	'rte-ck-pastefromword-confirmCleanup',
	'rte-ck-pastefromword-toolbar',
	'rte-ck-pastefromword-title',
	'rte-ck-pastefromword-error',
	'rte-ck-preview',
	'rte-ck-print',
	'rte-ck-redo',
	'rte-ck-removeFormat',
	'rte-ck-resize',
	'rte-ck-save',
	'rte-ck-select-title',
	'rte-ck-select-selectInfo',
	'rte-ck-select-opAvail',
	'rte-ck-select-value',
	'rte-ck-select-size',
	'rte-ck-select-lines',
	'rte-ck-select-chkMulti',
	'rte-ck-select-opText',
	'rte-ck-select-opValue',
	'rte-ck-select-btnAdd',
	'rte-ck-select-btnModify',
	'rte-ck-select-btnUp',
	'rte-ck-select-btnDown',
	'rte-ck-select-btnSetValue',
	'rte-ck-select-btnDelete',
	'rte-ck-selectAll',
	'rte-ck-showBlocks',
	'rte-ck-smiley-toolbar',
	'rte-ck-smiley-title',
	'rte-ck-smiley-options',
	'rte-ck-source',
	'rte-ck-specialChar-toolbar',
	'rte-ck-specialChar-title',
	'rte-ck-specialChar-options',
	'rte-ck-strike',
	'rte-ck-stylesCombo-label',
	'rte-ck-stylesCombo-panelTitle',
	'rte-ck-stylesCombo-panelTitle1',
	'rte-ck-stylesCombo-panelTitle2',
	'rte-ck-stylesCombo-panelTitle3',
	'rte-ck-subscript',
	'rte-ck-superscript',
	'rte-ck-table-toolbar',
	'rte-ck-table-title',
	'rte-ck-table-menu',
	'rte-ck-table-deleteTable',
	'rte-ck-table-rows',
	'rte-ck-table-columns',
	'rte-ck-table-border',
	'rte-ck-table-widthPx',
	'rte-ck-table-widthPc',
	'rte-ck-table-widthUnit',
	'rte-ck-table-cellSpace',
	'rte-ck-table-cellPad',
	'rte-ck-table-caption',
	'rte-ck-table-summary',
	'rte-ck-table-headers',
	'rte-ck-table-headersNone',
	'rte-ck-table-headersColumn',
	'rte-ck-table-headersRow',
	'rte-ck-table-headersBoth',
	'rte-ck-table-invalidRows',
	'rte-ck-table-invalidCols',
	'rte-ck-table-invalidBorder',
	'rte-ck-table-invalidWidth',
	'rte-ck-table-invalidHeight',
	'rte-ck-table-invalidCellSpacing',
	'rte-ck-table-invalidCellPadding',
	'rte-ck-table-cell-menu',
	'rte-ck-table-cell-insertBefore',
	'rte-ck-table-cell-insertAfter',
	'rte-ck-table-cell-deleteCell',
	'rte-ck-table-cell-merge',
	'rte-ck-table-cell-mergeRight',
	'rte-ck-table-cell-mergeDown',
	'rte-ck-table-cell-splitHorizontal',
	'rte-ck-table-cell-splitVertical',
	'rte-ck-table-cell-title',
	'rte-ck-table-cell-cellType',
	'rte-ck-table-cell-rowSpan',
	'rte-ck-table-cell-colSpan',
	'rte-ck-table-cell-wordWrap',
	'rte-ck-table-cell-hAlign',
	'rte-ck-table-cell-vAlign',
	'rte-ck-table-cell-alignBaseline',
	'rte-ck-table-cell-bgColor',
	'rte-ck-table-cell-borderColor',
	'rte-ck-table-cell-data',
	'rte-ck-table-cell-header',
	'rte-ck-table-cell-yes',
	'rte-ck-table-cell-no',
	'rte-ck-table-cell-invalidWidth',
	'rte-ck-table-cell-invalidHeight',
	'rte-ck-table-cell-invalidRowSpan',
	'rte-ck-table-cell-invalidColSpan',
	'rte-ck-table-cell-chooseColor',
	'rte-ck-table-row-menu',
	'rte-ck-table-row-insertBefore',
	'rte-ck-table-row-insertAfter',
	'rte-ck-table-row-deleteRow',
	'rte-ck-table-column-menu',
	'rte-ck-table-column-insertBefore',
	'rte-ck-table-column-insertAfter',
	'rte-ck-table-column-deleteColumn',
	'rte-ck-templates-button',
	'rte-ck-templates-title',
	'rte-ck-templates-options',
	'rte-ck-templates-insertOption',
	'rte-ck-templates-selectPromptMsg',
	'rte-ck-templates-emptyListMsg',
	'rte-ck-textarea-title',
	'rte-ck-textarea-cols',
	'rte-ck-textarea-rows',
	'rte-ck-textfield-title',
	'rte-ck-textfield-name',
	'rte-ck-textfield-value',
	'rte-ck-textfield-charWidth',
	'rte-ck-textfield-maxChars',
	'rte-ck-textfield-type',
	'rte-ck-textfield-typeText',
	'rte-ck-textfield-typePass',
	'rte-ck-toolbarCollapse',
	'rte-ck-toolbarExpand',
	'rte-ck-toolbarGroups-document',
	'rte-ck-toolbarGroups-clipboard',
	'rte-ck-toolbarGroups-editing',
	'rte-ck-toolbarGroups-forms',
	'rte-ck-toolbarGroups-basicstyles',
	'rte-ck-toolbarGroups-paragraph',
	'rte-ck-toolbarGroups-links',
	'rte-ck-toolbarGroups-insert',
	'rte-ck-toolbarGroups-styles',
	'rte-ck-toolbarGroups-colors',
	'rte-ck-toolbarGroups-tools',
	'rte-ck-toolbars',
	'rte-ck-underline',
	'rte-ck-undo',
	'rte-ck-unlink',


	),
	'localBasePath' => __DIR__,
	'remoteExtPath' => 'wikia/PhalanxII'	
	);
*/
