<?php
/**
 * PostResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * discussion
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Discussion\Models;

use \ArrayAccess;

/**
 * PostResponse Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PostResponse implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'PostResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'id' => 'string',
        'site_id' => 'string',
        'thread_id' => 'string',
        'title' => 'string',
        'latest_revision_id' => 'string',
        'creator_id' => 'string',
        'raw_content' => 'string',
        'rendered_content' => 'string',
        'requester_id' => 'string',
        'user_block_details' => 'string',
        'position' => 'int',
        'upvote_count' => 'int',
        'created_by' => '\Swagger\Client\Discussion\Models\UserInfo',
        'last_edited_by' => '\Swagger\Client\Discussion\Models\UserInfo',
        'last_deleted_by' => '\Swagger\Client\Discussion\Models\UserInfo',
        'user_data' => '\Swagger\Client\Discussion\Models\PostUserData',
        'modification_date' => '\Swagger\Client\Discussion\Models\Instant',
        'creation_date' => '\Swagger\Client\Discussion\Models\Instant',
        'is_editable' => 'bool',
        'is_locked' => 'bool',
        'is_requester_blocked' => 'bool',
        'is_reported' => 'bool',
        'is_deleted' => 'bool',
        'is_held' => 'bool',
        'is_viewable' => 'bool',
        '_embedded' => '\Swagger\Client\Discussion\Models\PostEmbedded',
        '_links' => '\Swagger\Client\Discussion\Models\PostHalLinks'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'id' => 'id',
        'site_id' => 'siteId',
        'thread_id' => 'threadId',
        'title' => 'title',
        'latest_revision_id' => 'latestRevisionId',
        'creator_id' => 'creatorId',
        'raw_content' => 'rawContent',
        'rendered_content' => 'renderedContent',
        'requester_id' => 'requesterId',
        'user_block_details' => 'userBlockDetails',
        'position' => 'position',
        'upvote_count' => 'upvoteCount',
        'created_by' => 'createdBy',
        'last_edited_by' => 'lastEditedBy',
        'last_deleted_by' => 'lastDeletedBy',
        'user_data' => 'userData',
        'modification_date' => 'modificationDate',
        'creation_date' => 'creationDate',
        'is_editable' => 'isEditable',
        'is_locked' => 'isLocked',
        'is_requester_blocked' => 'isRequesterBlocked',
        'is_reported' => 'isReported',
        'is_deleted' => 'isDeleted',
        'is_held' => 'isHeld',
        'is_viewable' => 'isViewable',
        '_embedded' => '_embedded',
        '_links' => '_links'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'id' => 'setId',
        'site_id' => 'setSiteId',
        'thread_id' => 'setThreadId',
        'title' => 'setTitle',
        'latest_revision_id' => 'setLatestRevisionId',
        'creator_id' => 'setCreatorId',
        'raw_content' => 'setRawContent',
        'rendered_content' => 'setRenderedContent',
        'requester_id' => 'setRequesterId',
        'user_block_details' => 'setUserBlockDetails',
        'position' => 'setPosition',
        'upvote_count' => 'setUpvoteCount',
        'created_by' => 'setCreatedBy',
        'last_edited_by' => 'setLastEditedBy',
        'last_deleted_by' => 'setLastDeletedBy',
        'user_data' => 'setUserData',
        'modification_date' => 'setModificationDate',
        'creation_date' => 'setCreationDate',
        'is_editable' => 'setIsEditable',
        'is_locked' => 'setIsLocked',
        'is_requester_blocked' => 'setIsRequesterBlocked',
        'is_reported' => 'setIsReported',
        'is_deleted' => 'setIsDeleted',
        'is_held' => 'setIsHeld',
        'is_viewable' => 'setIsViewable',
        '_embedded' => 'setEmbedded',
        '_links' => 'setLinks'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'id' => 'getId',
        'site_id' => 'getSiteId',
        'thread_id' => 'getThreadId',
        'title' => 'getTitle',
        'latest_revision_id' => 'getLatestRevisionId',
        'creator_id' => 'getCreatorId',
        'raw_content' => 'getRawContent',
        'rendered_content' => 'getRenderedContent',
        'requester_id' => 'getRequesterId',
        'user_block_details' => 'getUserBlockDetails',
        'position' => 'getPosition',
        'upvote_count' => 'getUpvoteCount',
        'created_by' => 'getCreatedBy',
        'last_edited_by' => 'getLastEditedBy',
        'last_deleted_by' => 'getLastDeletedBy',
        'user_data' => 'getUserData',
        'modification_date' => 'getModificationDate',
        'creation_date' => 'getCreationDate',
        'is_editable' => 'getIsEditable',
        'is_locked' => 'getIsLocked',
        'is_requester_blocked' => 'getIsRequesterBlocked',
        'is_reported' => 'getIsReported',
        'is_deleted' => 'getIsDeleted',
        'is_held' => 'getIsHeld',
        'is_viewable' => 'getIsViewable',
        '_embedded' => 'getEmbedded',
        '_links' => 'getLinks'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
        $this->container['site_id'] = isset($data['site_id']) ? $data['site_id'] : null;
        $this->container['thread_id'] = isset($data['thread_id']) ? $data['thread_id'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['latest_revision_id'] = isset($data['latest_revision_id']) ? $data['latest_revision_id'] : null;
        $this->container['creator_id'] = isset($data['creator_id']) ? $data['creator_id'] : null;
        $this->container['raw_content'] = isset($data['raw_content']) ? $data['raw_content'] : null;
        $this->container['rendered_content'] = isset($data['rendered_content']) ? $data['rendered_content'] : null;
        $this->container['requester_id'] = isset($data['requester_id']) ? $data['requester_id'] : null;
        $this->container['user_block_details'] = isset($data['user_block_details']) ? $data['user_block_details'] : null;
        $this->container['position'] = isset($data['position']) ? $data['position'] : null;
        $this->container['upvote_count'] = isset($data['upvote_count']) ? $data['upvote_count'] : null;
        $this->container['created_by'] = isset($data['created_by']) ? $data['created_by'] : null;
        $this->container['last_edited_by'] = isset($data['last_edited_by']) ? $data['last_edited_by'] : null;
        $this->container['last_deleted_by'] = isset($data['last_deleted_by']) ? $data['last_deleted_by'] : null;
        $this->container['user_data'] = isset($data['user_data']) ? $data['user_data'] : null;
        $this->container['modification_date'] = isset($data['modification_date']) ? $data['modification_date'] : null;
        $this->container['creation_date'] = isset($data['creation_date']) ? $data['creation_date'] : null;
        $this->container['is_editable'] = isset($data['is_editable']) ? $data['is_editable'] : false;
        $this->container['is_locked'] = isset($data['is_locked']) ? $data['is_locked'] : false;
        $this->container['is_requester_blocked'] = isset($data['is_requester_blocked']) ? $data['is_requester_blocked'] : false;
        $this->container['is_reported'] = isset($data['is_reported']) ? $data['is_reported'] : false;
        $this->container['is_deleted'] = isset($data['is_deleted']) ? $data['is_deleted'] : false;
        $this->container['is_held'] = isset($data['is_held']) ? $data['is_held'] : false;
        $this->container['is_viewable'] = isset($data['is_viewable']) ? $data['is_viewable'] : false;
        $this->container['_embedded'] = isset($data['_embedded']) ? $data['_embedded'] : null;
        $this->container['_links'] = isset($data['_links']) ? $data['_links'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets id
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     * @param string $id
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets site_id
     * @return string
     */
    public function getSiteId()
    {
        return $this->container['site_id'];
    }

    /**
     * Sets site_id
     * @param string $site_id
     * @return $this
     */
    public function setSiteId($site_id)
    {
        $this->container['site_id'] = $site_id;

        return $this;
    }

    /**
     * Gets thread_id
     * @return string
     */
    public function getThreadId()
    {
        return $this->container['thread_id'];
    }

    /**
     * Sets thread_id
     * @param string $thread_id
     * @return $this
     */
    public function setThreadId($thread_id)
    {
        $this->container['thread_id'] = $thread_id;

        return $this;
    }

    /**
     * Gets title
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     * @param string $title
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets latest_revision_id
     * @return string
     */
    public function getLatestRevisionId()
    {
        return $this->container['latest_revision_id'];
    }

    /**
     * Sets latest_revision_id
     * @param string $latest_revision_id
     * @return $this
     */
    public function setLatestRevisionId($latest_revision_id)
    {
        $this->container['latest_revision_id'] = $latest_revision_id;

        return $this;
    }

    /**
     * Gets creator_id
     * @return string
     */
    public function getCreatorId()
    {
        return $this->container['creator_id'];
    }

    /**
     * Sets creator_id
     * @param string $creator_id
     * @return $this
     */
    public function setCreatorId($creator_id)
    {
        $this->container['creator_id'] = $creator_id;

        return $this;
    }

    /**
     * Gets raw_content
     * @return string
     */
    public function getRawContent()
    {
        return $this->container['raw_content'];
    }

    /**
     * Sets raw_content
     * @param string $raw_content
     * @return $this
     */
    public function setRawContent($raw_content)
    {
        $this->container['raw_content'] = $raw_content;

        return $this;
    }

    /**
     * Gets rendered_content
     * @return string
     */
    public function getRenderedContent()
    {
        return $this->container['rendered_content'];
    }

    /**
     * Sets rendered_content
     * @param string $rendered_content
     * @return $this
     */
    public function setRenderedContent($rendered_content)
    {
        $this->container['rendered_content'] = $rendered_content;

        return $this;
    }

    /**
     * Gets requester_id
     * @return string
     */
    public function getRequesterId()
    {
        return $this->container['requester_id'];
    }

    /**
     * Sets requester_id
     * @param string $requester_id
     * @return $this
     */
    public function setRequesterId($requester_id)
    {
        $this->container['requester_id'] = $requester_id;

        return $this;
    }

    /**
     * Gets user_block_details
     * @return string
     */
    public function getUserBlockDetails()
    {
        return $this->container['user_block_details'];
    }

    /**
     * Sets user_block_details
     * @param string $user_block_details
     * @return $this
     */
    public function setUserBlockDetails($user_block_details)
    {
        $this->container['user_block_details'] = $user_block_details;

        return $this;
    }

    /**
     * Gets position
     * @return int
     */
    public function getPosition()
    {
        return $this->container['position'];
    }

    /**
     * Sets position
     * @param int $position
     * @return $this
     */
    public function setPosition($position)
    {
        $this->container['position'] = $position;

        return $this;
    }

    /**
     * Gets upvote_count
     * @return int
     */
    public function getUpvoteCount()
    {
        return $this->container['upvote_count'];
    }

    /**
     * Sets upvote_count
     * @param int $upvote_count
     * @return $this
     */
    public function setUpvoteCount($upvote_count)
    {
        $this->container['upvote_count'] = $upvote_count;

        return $this;
    }

    /**
     * Gets created_by
     * @return \Swagger\Client\Discussion\Models\UserInfo
     */
    public function getCreatedBy()
    {
        return $this->container['created_by'];
    }

    /**
     * Sets created_by
     * @param \Swagger\Client\Discussion\Models\UserInfo $created_by
     * @return $this
     */
    public function setCreatedBy($created_by)
    {
        $this->container['created_by'] = $created_by;

        return $this;
    }

    /**
     * Gets last_edited_by
     * @return \Swagger\Client\Discussion\Models\UserInfo
     */
    public function getLastEditedBy()
    {
        return $this->container['last_edited_by'];
    }

    /**
     * Sets last_edited_by
     * @param \Swagger\Client\Discussion\Models\UserInfo $last_edited_by
     * @return $this
     */
    public function setLastEditedBy($last_edited_by)
    {
        $this->container['last_edited_by'] = $last_edited_by;

        return $this;
    }

    /**
     * Gets last_deleted_by
     * @return \Swagger\Client\Discussion\Models\UserInfo
     */
    public function getLastDeletedBy()
    {
        return $this->container['last_deleted_by'];
    }

    /**
     * Sets last_deleted_by
     * @param \Swagger\Client\Discussion\Models\UserInfo $last_deleted_by
     * @return $this
     */
    public function setLastDeletedBy($last_deleted_by)
    {
        $this->container['last_deleted_by'] = $last_deleted_by;

        return $this;
    }

    /**
     * Gets user_data
     * @return \Swagger\Client\Discussion\Models\PostUserData
     */
    public function getUserData()
    {
        return $this->container['user_data'];
    }

    /**
     * Sets user_data
     * @param \Swagger\Client\Discussion\Models\PostUserData $user_data
     * @return $this
     */
    public function setUserData($user_data)
    {
        $this->container['user_data'] = $user_data;

        return $this;
    }

    /**
     * Gets modification_date
     * @return \Swagger\Client\Discussion\Models\Instant
     */
    public function getModificationDate()
    {
        return $this->container['modification_date'];
    }

    /**
     * Sets modification_date
     * @param \Swagger\Client\Discussion\Models\Instant $modification_date
     * @return $this
     */
    public function setModificationDate($modification_date)
    {
        $this->container['modification_date'] = $modification_date;

        return $this;
    }

    /**
     * Gets creation_date
     * @return \Swagger\Client\Discussion\Models\Instant
     */
    public function getCreationDate()
    {
        return $this->container['creation_date'];
    }

    /**
     * Sets creation_date
     * @param \Swagger\Client\Discussion\Models\Instant $creation_date
     * @return $this
     */
    public function setCreationDate($creation_date)
    {
        $this->container['creation_date'] = $creation_date;

        return $this;
    }

    /**
     * Gets is_editable
     * @return bool
     */
    public function getIsEditable()
    {
        return $this->container['is_editable'];
    }

    /**
     * Sets is_editable
     * @param bool $is_editable
     * @return $this
     */
    public function setIsEditable($is_editable)
    {
        $this->container['is_editable'] = $is_editable;

        return $this;
    }

    /**
     * Gets is_locked
     * @return bool
     */
    public function getIsLocked()
    {
        return $this->container['is_locked'];
    }

    /**
     * Sets is_locked
     * @param bool $is_locked
     * @return $this
     */
    public function setIsLocked($is_locked)
    {
        $this->container['is_locked'] = $is_locked;

        return $this;
    }

    /**
     * Gets is_requester_blocked
     * @return bool
     */
    public function getIsRequesterBlocked()
    {
        return $this->container['is_requester_blocked'];
    }

    /**
     * Sets is_requester_blocked
     * @param bool $is_requester_blocked
     * @return $this
     */
    public function setIsRequesterBlocked($is_requester_blocked)
    {
        $this->container['is_requester_blocked'] = $is_requester_blocked;

        return $this;
    }

    /**
     * Gets is_reported
     * @return bool
     */
    public function getIsReported()
    {
        return $this->container['is_reported'];
    }

    /**
     * Sets is_reported
     * @param bool $is_reported
     * @return $this
     */
    public function setIsReported($is_reported)
    {
        $this->container['is_reported'] = $is_reported;

        return $this;
    }

    /**
     * Gets is_deleted
     * @return bool
     */
    public function getIsDeleted()
    {
        return $this->container['is_deleted'];
    }

    /**
     * Sets is_deleted
     * @param bool $is_deleted
     * @return $this
     */
    public function setIsDeleted($is_deleted)
    {
        $this->container['is_deleted'] = $is_deleted;

        return $this;
    }

    /**
     * Gets is_held
     * @return bool
     */
    public function getIsHeld()
    {
        return $this->container['is_held'];
    }

    /**
     * Sets is_held
     * @param bool $is_held
     * @return $this
     */
    public function setIsHeld($is_held)
    {
        $this->container['is_held'] = $is_held;

        return $this;
    }

    /**
     * Gets is_viewable
     * @return bool
     */
    public function getIsViewable()
    {
        return $this->container['is_viewable'];
    }

    /**
     * Sets is_viewable
     * @param bool $is_viewable
     * @return $this
     */
    public function setIsViewable($is_viewable)
    {
        $this->container['is_viewable'] = $is_viewable;

        return $this;
    }

    /**
     * Gets _embedded
     * @return \Swagger\Client\Discussion\Models\PostEmbedded
     */
    public function getEmbedded()
    {
        return $this->container['_embedded'];
    }

    /**
     * Sets _embedded
     * @param \Swagger\Client\Discussion\Models\PostEmbedded $_embedded
     * @return $this
     */
    public function setEmbedded($_embedded)
    {
        $this->container['_embedded'] = $_embedded;

        return $this;
    }

    /**
     * Gets _links
     * @return \Swagger\Client\Discussion\Models\PostHalLinks
     */
    public function getLinks()
    {
        return $this->container['_links'];
    }

    /**
     * Sets _links
     * @param \Swagger\Client\Discussion\Models\PostHalLinks $_links
     * @return $this
     */
    public function setLinks($_links)
    {
        $this->container['_links'] = $_links;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\Swagger\Client\ObjectSerializer::sanitizeForSerialization($this));
    }
}


