#!/bin/sh


grep -l 'wgAlternativeDefinitionAttributeName'  *
grep -l 'wgAlternativeDefinitionsAttributeName' *
grep -l 'wgAnnotationAttributeName' *
grep -l 'wgApproximateMeaningsAttributeName' *
grep -l 'wgClassAttributeAttributeAttributeName' *
grep -l 'wgClassAttributesAttributeName' *
grep -l 'wgClassAttributeLevelAttributeName' *
grep -l 'wgClassAttributeTypeAttributeName' *
grep -l 'wgClassMembershipAttributeName' *
grep -l 'wgCollectionAttributeName' *
grep -l 'wgCollectionMembershipAttributeName' *
grep -l 'wgDefinedMeaningAttributesAttributeName' *
grep -l 'wgDefinedMeaningAttributeName' *
grep -l 'wgDefinedMeaningReferenceAttributeName' *
grep -l 'wgDefinitionAttributeName' *
grep -l 'wgLanguageAttributeName' *
grep -l 'wgExactMeaningsAttributeName' *
grep -l 'wgExpressionAttributeName' *
grep -l 'wgExpressionMeaningsAttributeName' *
grep -l 'wgExpressionsAttributeName' *
grep -l 'wgGotoSourceAttributeName' *
grep -l 'wgIdenticalMeaningAttributeName' *
grep -l 'wgIncomingRelationsAttributeName'  *
grep -l 'wgLevelAnnotationAttributeName' *
grep -l 'wgLinkAttributeAttributeName' *
grep -l 'wgLinkAttributeValuesAttributeName' *
grep -l 'wgOptionAttributeOptionAttributeName' *
grep -l 'wgOptionAttributeOptionsAttributeName' *
grep -l 'wgOptionAttributeValuesAttributeName' *
grep -l 'wgOtherDefinedMeaningAttributeName' *
grep -l 'wgPopupAnnotationName'  *
grep -l 'wgPossibleSynonymAttributeName' *
grep -l 'wgPossiblySynonymousAttributeName' *
grep -l 'wgRelationsAttributeName'  *
grep -l 'wgRelationTypeAttributeName'  *
grep -l 'wgSourceAttributeName' *
grep -l 'wgSourceIdentifierAttributeName' *
grep -l 'wgSpellingAttributeName' *
grep -l 'wgSynonymsAttributeName' *
grep -l 'wgSynonymsAndTranslationsAttributeName' *
grep -l 'wgTextAttributeAttributeName' *
grep -l 'wgTextAttributeName' *
grep -l 'wgTextAttributeValuesAttributeName' *
grep -l 'wgTranslatedTextAttributeAttributeName' *
grep -l 'wgTranslatedTextAttributeName' *
grep -l 'wgTranslatedTextAttributeValueAttributeName' *
grep -l 'wgTranslatedTextAttributeValuesAttributeName' *
