<?php
/**
 * Define the messages structure in the messages file, for an automated rewriting. 
 * Wikia additions
 *
 * @file
 * @ingroup MaintenanceLanguage
 */


$wgMessageStructure[ 'button-labels' ] = array( 'button-createpage' );
$wgMessageStructure[ 'oasis' ] = array(
                'oasis-more',
                'oasis-mytools',
                'oasis-follow',
                'oasis-share',
                'oasis-like',
                'oasis-activity-header',
                'oasis-total-articles',
); 

/** Comments for each block */
$wgBlockComments[ 'button-labels' ] = 'User Interface Labels for Oasis skin';
$wgBlockComments[ 'oasis' ] = 'Messages specific to Oasis skin';

