language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  include:
    - env: DBTYPE=mysql; MW=master
      php: 5.6
    - env: DBTYPE=mysql; MW=master
      php: 7
    - env: DBTYPE=sqlite; MW=1.21.0
      php: 5.3
    - env: DBTYPE=mysql; MW=1.23.0
      php: 5.5
    - env: DBTYPE=sqlite; MW=master; TYPE=coverage
      php: 5.6
  exclude:
    - env: THENEEDFORTHIS=FAIL

install: travis_retry composer self-update

before_script: bash ./build/travis/before_script.sh

script: bash ./build/travis/script.sh

after_success: bash ./build/travis/after_success.sh
